#pragma once

#include <string>
#include <vector>
#include <map>

#include <wx/string.h>

#include "Shared functions/StringFunctions.h"

using std::string;
using std::vector;
using std::map;

/// <summary>
/// Item matches LuaItem
/// <para>https://lua-api.factorio.com/latest/classes/LuaItemPrototype.html</para>
/// </summary>
struct Item
{
	/// <summary> Enumeration of all items, matching vector:names. </summary>
	enum ItemType
	{
		wooden_chest,
		iron_chest,
		steel_chest,
		storage_tank,
		transport_belt,
		fast_transport_belt,
		express_transport_belt,
		underground_belt,
		fast_underground_belt,
		express_underground_belt,
		splitter,
		fast_splitter,
		express_splitter,
		burner_inserter,
		inserter,
		long_handed_inserter,
		fast_inserter,
		filter_inserter,
		stack_inserter,
		stack_filter_inserter,
		small_electric_pole,
		medium_electric_pole,
		big_electric_pole,
		substation,
		pipe,
		pipe_to_ground,
		pump,
		rail,
		train_stop,
		rail_signal,
		rail_chain_signal,
		locomotive,
		cargo_wagon,
		fluid_wagon,
		artillery_wagon,
		car,
		tank,
		spidertron,
		logistic_robot,
		construction_robot,
		logistic_chest_active_provider,
		logistic_chest_passive_provider,
		logistic_chest_storage,
		logistic_chest_buffer,
		logistic_chest_requester,
		roboport,
		small_lamp,
		red_wire,
		green_wire,
		arithmetic_combinator,
		decider_combinator,
		constant_combinator,
		power_switch,
		programmable_speaker,
		stone_brick,
		concrete,
		hazard_concrete,
		refined_concrete,
		refined_hazard_concrete,
		landfill,
		repair_pack,
		boiler,
		steam_engine,
		solar_panel,
		accumulator,
		nuclear_reactor,
		heat_pipe,
		heat_exchanger,
		steam_turbine,
		burner_mining_drill,
		electric_mining_drill,
		offshore_pump,
		pumpjack,
		stone_furnace,
		steel_furnace,
		electric_furnace,
		assembling_machine_1,
		assembling_machine_2,
		assembling_machine_3,
		oil_refinery,
		chemical_plant,
		centrifuge,
		lab,
		beacon,
		speed_module,
		speed_module_2,
		speed_module_3,
		effectivity_module,
		effectivity_module_2,
		effectivity_module_3,
		productivity_module,
		productivity_module_2,
		productivity_module_3,
		rocket_silo,
		satellite,
		wood,
		coal,
		stone,
		iron_ore,
		copper_ore,
		uranium_ore,
		raw_fish,
		iron_plate,
		copper_plate,
		solid_fuel,
		steel_plate,
		plastic_bar,
		sulfur,
		battery,
		explosives,
		crude_oil_barrel,
		heavy_oil_barrel,
		light_oil_barrel,
		lubricant_barrel,
		petroleum_gas_barrel,
		sulfuric_acid_barrel,
		water_barrel,
		copper_cable,
		iron_stick,
		iron_gear_wheel,
		empty_barrel,
		electronic_circuit,
		advanced_circuit,
		processing_unit,
		engine_unit,
		electric_engine_unit,
		flying_robot_frame,
		rocket_control_unit,
		low_density_structure,
		rocket_fuel,
		nuclear_fuel,
		uranium_235,
		uranium_238,
		uranium_fuel_cell,
		used_up_uranium_fuel_cell,
		automation_science_pack,
		logistic_science_pack,
		military_science_pack,
		chemical_science_pack,
		production_science_pack,
		utility_science_pack,
		space_science_pack,
		pistol,
		submachine_gun,
		shotgun,
		combat_shotgun,
		rocket_launcher,
		flamethrower,
		land_mine,
		firearm_magazine,
		piercing_rounds_magazine,
		uranium_rounds_magazine,
		shotgun_shell,
		piercing_shotgun_shell,
		cannon_shell,
		explosive_cannon_shell,
		uranium_cannon_shell,
		explosive_uranium_cannon_shell,
		artillery_shell,
		rocket,
		explosive_rocket,
		atomic_bomb,
		flamethrower_ammo,
		grenade,
		cluster_grenade,
		poison_capsule,
		slowdown_capsule,
		defender_capsule,
		distractor_capsule,
		destroyer_capsule,
		light_armor,
		heavy_armor,
		solar_panel_equipment,
		fusion_reactor_equipment,
		battery_equipment,
		battery_mk2_equipment,
		belt_immunity_equipment,
		exoskeleton_equipment,
		personal_roboport_equipment,
		personal_roboport_mk2_equipment,
		night_vision_equipment,
		energy_shield_equipment,
		energy_shield_mk2_equipment,
		personal_laser_defense_equipment,
		discharge_defense_equipment,
		discharge_defense_remote,
		stone_wall,
		gate,
		gun_turret,
		laser_turret,
		flamethrower_turret,
		artillery_turret,
		artillery_targeting_remote,
		radar,
	} type;
	
	// Categorisation of items. 
	// An item can only fit into 1 of [building, tile, vehicle & item].
	// It is possible an item is in multiple other categories.
	struct Category
	{
		enum ItemCategory
		{
			c_building = 1 << 0, // placeable as a building [transport belt, inserter, rocket silo, etc]
			c_tile = 1 << 1, // placeable as a tile [stone brick, landfill, etc]
			c_vehicle = 1 << 2, // placeable as a vehicle [car, spidertron, cargowagon, etc]
			c_item = 1 << 3, // not a placeable item

			c_product = 1 << 4, // the result of a recipe
			c_ingredient = 1 << 5, // an ingredient to a recipe

			c_module = 1 << 6, // can be used in the module slot
			c_fuel = 1 << 7, // can be used in the fuel slot
			c_sciencepack = 1 << 8, // can be used in a lab

			c_capsule = 1 << 9, // can be thrown [grendades, defender robots, etc]
			c_ammo = 1 << 10, // can be placed in an ammo slot, maybe in a vehicle
			c_weapon = 1 << 11, // can be placed in a weapon slot
			c_armor = 1 << 12, // can be placed in the armor slot
			c_equipment = 1 << 13, // can be placed in an armors equipment grid

			c_repairpack = 1 << 14, // repair pack is the only item in this category
		};
		
		int bit_vector;

		Category(int);
		bool IsCategory(ItemCategory);
		bool IsPlaceable();
	} category;

	static inline const vector<Category> map_itemtype_to_category = {
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_vehicle | Category::c_product,
		Category::c_vehicle | Category::c_product,
		Category::c_vehicle | Category::c_product,
		Category::c_vehicle | Category::c_product,
		Category::c_vehicle | Category::c_product,
		Category::c_vehicle | Category::c_product,
		Category::c_vehicle | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_item | Category::c_product,
		Category::c_item | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_tile | Category::c_ingredient | Category::c_product,
		Category::c_tile | Category::c_ingredient | Category::c_product,
		Category::c_tile | Category::c_product,
		Category::c_tile | Category::c_ingredient | Category::c_product,
		Category::c_tile | Category::c_product,
		Category::c_tile | Category::c_product,
		Category::c_item | Category::c_product | Category::c_repairpack,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_item | Category::c_module | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_module | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_module | Category::c_product,
		Category::c_item | Category::c_module | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_module | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_module | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_module | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_module | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_module | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_item | Category::c_product,
		Category::c_item | Category::c_fuel | Category::c_ingredient,
		Category::c_item | Category::c_fuel | Category::c_ingredient,
		Category::c_item | Category::c_ingredient,
		Category::c_item | Category::c_ingredient,
		Category::c_item | Category::c_ingredient,
		Category::c_item | Category::c_ingredient,
		Category::c_item | Category::c_capsule | Category::c_ingredient,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_fuel | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_fuel | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_fuel | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_product,
		Category::c_item | Category::c_ingredient,
		Category::c_item | Category::c_sciencepack | Category::c_product,
		Category::c_item | Category::c_sciencepack | Category::c_product,
		Category::c_item | Category::c_sciencepack | Category::c_product,
		Category::c_item | Category::c_sciencepack | Category::c_product,
		Category::c_item | Category::c_sciencepack | Category::c_product,
		Category::c_item | Category::c_sciencepack | Category::c_product,
		Category::c_item | Category::c_sciencepack,
		Category::c_item | Category::c_weapon | Category::c_product,
		Category::c_item | Category::c_weapon | Category::c_product,
		Category::c_item | Category::c_weapon | Category::c_product,
		Category::c_item | Category::c_weapon | Category::c_product,
		Category::c_item | Category::c_weapon | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_weapon | Category::c_product,
		Category::c_building | Category::c_weapon | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_product,
		Category::c_item | Category::c_ammo | Category::c_product,
		Category::c_item | Category::c_capsule | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_capsule | Category::c_product,
		Category::c_item | Category::c_capsule | Category::c_product,
		Category::c_item | Category::c_capsule | Category::c_product,
		Category::c_item | Category::c_capsule | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_capsule | Category::c_ingredient | Category::c_product,
		Category::c_item | Category::c_capsule | Category::c_product,
		Category::c_item | Category::c_armor | Category::c_product,
		Category::c_item | Category::c_armor | Category::c_product,
		Category::c_item | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_ingredient | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_ingredient | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_ingredient | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_ingredient | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_ingredient | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_product | Category::c_equipment,
		Category::c_item | Category::c_capsule | Category::c_product | Category::c_equipment,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_building | Category::c_product,
		Category::c_item | Category::c_capsule | Category::c_product,
		Category::c_building | Category::c_ingredient | Category::c_product,
};

	Item();
	Item(int);
	string Name();

	// Finds the Item matching or throws an error
	static Item MapStringToItem(const string str); 
	// Finds the Item matching or throws an error
	static Item MapStringToItem(const wxString str); 
	// Finds the Item matching and assigns it to item. Returns whether an Item was found
	static bool MapStringToItem(const string str, Item& item); 
	// Finds the Item matching and assigns it to item. Returns whether an Item was found
	static bool MapStringToItem(const wxString str, Item& item);

	static inline const vector<string> names = {
		"Wooden chest",
		"Iron chest",
		"Steel chest",
		"Storage tank",
		"Transport belt",
		"Fast transport belt",
		"Express transport belt",
		"Underground belt",
		"Fast underground belt",
		"Express underground belt",
		"Splitter",
		"Fast splitter",
		"Express splitter",
		"Burner inserter",
		"Inserter",
		"Long-handed inserter",
		"Fast inserter",
		"Filter inserter",
		"Stack inserter",
		"Stack filter inserter",
		"Small electric pole",
		"Medium electric pole",
		"Big electric pole",
		"Substation",
		"Pipe",
		"Pipe to ground",
		"Pump",
		"Rail",
		"Train stop",
		"Rail signal",
		"Rail chain signal",
		"Locomotive",
		"Cargo wagon",
		"Fluid wagon",
		"Artillery wagon",
		"Car",
		"Tank",
		"Spidertron",
		"Logistic robot",
		"Construction robot",
		"Active provider chest",
		"Passive provider chest",
		"Storage chest",
		"Buffer chest",
		"Requester chest",
		"Roboport",
		"Lamp",
		"Red wire",
		"Green wire",
		"Arithmetic combinator",
		"Decider combinator",
		"Constant combinator",
		"Power switch",
		"Programmable speaker",
		"Stone brick",
		"Concrete",
		"Hazard concrete",
		"Refined concrete",
		"Refined hazard concrete",
		"Landfill",
		"Repair pack",
		"Boiler",
		"Steam engine",
		"Solar panel",
		"Accumulator",
		"Nuclear reactor",
		"Heat pipe",
		"Heat exchanger",
		"Steam turbine",
		"Burner mining drill",
		"Electric mining drill",
		"Offshore pump",
		"Pumpjack",
		"Stone furnace",
		"Steel furnace",
		"Electric furnace",
		"Assembling machine 1",
		"Assembling machine 2",
		"Assembling machine 3",
		"Oil refinery",
		"Chemical plant",
		"Centrifuge",
		"Lab",
		"Beacon",
		"Speed module",
		"Speed module 2",
		"Speed module 3",
		"Efficiency module",
		"Efficiency module 2",
		"Efficiency module 3",
		"Productivity module",
		"Productivity module 2",
		"Productivity module 3",
		"Rocket silo",
		"Satellite",
		"Wood",
		"Coal",
		"Stone",
		"Iron ore",
		"Copper ore",
		"Uranium ore",
		"Raw fish",
		"Iron plate",
		"Copper plate",
		"Solid fuel",
		"Steel plate",
		"Plastic bar",
		"Sulfur",
		"Battery",
		"Explosives",
		"Crude oil barrel",
		"Heavy oil barrel",
		"Light oil barrel",
		"Lubricant barrel",
		"Petroleum gas barrel",
		"Sulfuric acid barrel",
		"Water barrel",
		"Copper cable",
		"Iron stick",
		"Iron gear wheel",
		"Empty barrel",
		"Electronic circuit",
		"Advanced circuit",
		"Processing unit",
		"Engine unit",
		"Electric engine unit",
		"Flying robot frame",
		"Rocket control unit",
		"Low density structure",
		"Rocket fuel",
		"Nuclear fuel",
		"Uranium-235",
		"Uranium-238",
		"Uranium fuel cell",
		"Used-up uranium fuel cell",
		"Automation science pack",
		"Logistic science pack",
		"Military science pack",
		"Chemical science pack",
		"Production science pack",
		"Utility science pack",
		"Space science pack",
		"Pistol",
		"Submachine gun",
		"Shotgun",
		"Combat shotgun",
		"Rocket launcher",
		"Flamethrower",
		"Land mine",
		"Firearm magazine",
		"Piercing rounds magazine",
		"Uranium rounds magazine",
		"Shotgun shells",
		"Piercing shotgun shells",
		"Cannon shell",
		"Explosive cannon shell",
		"Uranium cannon shell",
		"Explosive uranium cannon shell",
		"Artillery shell",
		"Rocket",
		"Explosive rocket",
		"Atomic bomb",
		"Flamethrower ammo",
		"Grenade",
		"Cluster grenade",
		"Poison capsule",
		"Slowdown capsule",
		"Defender capsule",
		"Distractor capsule",
		"Destroyer capsule",
		"Light armor",
		"Heavy armor",
		"Portable solar panel",
		"Portable fusion reactor",
		"Personal battery",
		"Personal battery MK2",
		"Belt immunity equipment",
		"Exoskeleton",
		"Personal roboport",
		"Personal roboport MK2",
		"Nightvision",
		"Energy shield",
		"Energy shield MK2",
		"Personal laser defense",
		"Discharge defense",
		"Discharge defense remote",
		"Wall",
		"Gate",
		"Gun turret",
		"Laser turret",
		"Flamethrower turret",
		"Artillery turret",
		"Artillery targeting remote",
		"Radar",
	};

	static inline const vector<string> itemtype_to_luaname{
		"wooden-chest",
		"iron-chest",
		"steel-chest",
		"storage-tank",
		"transport-belt",
		"fast-transport-belt",
		"express-transport-belt",
		"underground-belt",
		"fast-underground-belt",
		"express-underground-belt",
		"splitter",
		"fast-splitter",
		"express-splitter",
		"burner-inserter",
		"inserter",
		"long-handed-inserter",
		"fast-inserter",
		"filter-inserter",
		"stack-inserter",
		"stack-filter-inserter",
		"small-electric-pole",
		"medium-electric-pole",
		"big-electric-pole",
		"substation",
		"pipe",
		"pipe-to-ground",
		"pump",
		"rail",
		"train-stop",
		"rail-signal",
		"rail-chain-signal",
		"locomotive",
		"cargo-wagon",
		"fluid-wagon",
		"artillery-wagon",
		"car",
		"tank",
		"spidertron",
		"logistic-robot",
		"construction-robot",
		"logistic-chest-active-provider",
		"logistic-chest-passive-provider",
		"logistic-chest-storage",
		"logistic-chest-buffer",
		"logistic-chest-requester",
		"roboport",
		"small-lamp",
		"red-wire",
		"green-wire",
		"arithmetic-combinator",
		"decider-combinator",
		"constant-combinator",
		"power-switch",
		"programmable-speaker",
		"stone-brick",
		"concrete",
		"hazard-concrete",
		"refined-concrete",
		"refined-hazard-concrete",
		"landfill",
		"repair-pack",
		"boiler",
		"steam-engine",
		"solar-panel",
		"accumulator",
		"nuclear-reactor",
		"heat-pipe",
		"heat-exchanger",
		"steam-turbine",
		"burner-mining-drill",
		"electric-mining-drill",
		"offshore-pump",
		"pumpjack",
		"stone-furnace",
		"steel-furnace",
		"electric-furnace",
		"assembling-machine-1",
		"assembling-machine-2",
		"assembling-machine-3",
		"oil-refinery",
		"chemical-plant",
		"centrifuge",
		"lab",
		"beacon",
		"speed-module",
		"speed-module-2",
		"speed-module-3",
		"effectivity-module",
		"effectivity-module-2",
		"effectivity-module-3",
		"productivity-module",
		"productivity-module-2",
		"productivity-module-3",
		"rocket-silo",
		"satellite",
		"wood",
		"coal",
		"stone",
		"iron-ore",
		"copper-ore",
		"uranium-ore",
		"raw-fish",
		"iron-plate",
		"copper-plate",
		"solid-fuel",
		"steel-plate",
		"plastic-bar",
		"sulfur",
		"battery",
		"explosives",
		"crude-oil-barrel",
		"heavy-oil-barrel",
		"light-oil-barrel",
		"lubricant-barrel",
		"petroleum-gas-barrel",
		"sulfuric-acid-barrel",
		"water-barrel",
		"copper-cable",
		"iron-stick",
		"iron-gear-wheel",
		"empty-barrel",
		"electronic-circuit",
		"advanced-circuit",
		"processing-unit",
		"engine-unit",
		"electric-engine-unit",
		"flying-robot-frame",
		"rocket-control-unit",
		"low-density-structure",
		"rocket-fuel",
		"nuclear-fuel",
		"uranium-235",
		"uranium-238",
		"uranium-fuel-cell",
		"used-up-uranium-fuel-cell",
		"automation-science-pack",
		"logistic-science-pack",
		"military-science-pack",
		"chemical-science-pack",
		"production-science-pack",
		"utility-science-pack",
		"space-science-pack",
		"pistol",
		"submachine-gun",
		"shotgun",
		"combat-shotgun",
		"rocket-launcher",
		"flamethrower",
		"land-mine",
		"firearm-magazine",
		"piercing-rounds-magazine",
		"uranium-rounds-magazine",
		"shotgun-shell",
		"piercing-shotgun-shell",
		"cannon-shell",
		"explosive-cannon-shell",
		"uranium-cannon-shell",
		"explosive-uranium-cannon-shell",
		"artillery-shell",
		"rocket",
		"explosive-rocket",
		"atomic-bomb",
		"flamethrower-ammo",
		"grenade",
		"cluster-grenade",
		"poison-capsule",
		"slowdown-capsule",
		"defender-capsule",
		"distractor-capsule",
		"destroyer-capsule",
		"light-armor",
		"heavy-armor",
		"solar-panel-equipment",
		"fusion-reactor-equipment",
		"battery-equipment",
		"battery-mk2-equipment",
		"belt-immunity-equipment",
		"exoskeleton-equipment",
		"personal-roboport-equipment",
		"personal-roboport-mk2-equipment",
		"night-vision-equipment",
		"energy-shield-equipment",
		"energy-shield-mk2-equipment",
		"personal-laser-defense-equipment",
		"discharge-defense-equipment",
		"discharge-defense-remote",
		"stone-wall",
		"gate",
		"gun-turret",
		"laser-turret",
		"flamethrower-turret",
		"artillery-turret",
		"artillery-targeting-remote",
		"radar",
	};

	static inline const map<string, ItemType> map_itemname_to_itemtype{
		{names[wooden_chest], wooden_chest},
		{names[iron_chest], iron_chest},
		{names[steel_chest], steel_chest},
		{names[storage_tank], storage_tank},
		{names[transport_belt], transport_belt},
		{names[fast_transport_belt], fast_transport_belt},
		{names[express_transport_belt], express_transport_belt},
		{names[underground_belt], underground_belt},
		{names[fast_underground_belt], fast_underground_belt},
		{names[express_underground_belt], express_underground_belt},
		{names[splitter], splitter},
		{names[fast_splitter], fast_splitter},
		{names[express_splitter], express_splitter},
		{names[burner_inserter], burner_inserter},
		{names[inserter], inserter},
		{names[long_handed_inserter], long_handed_inserter},
		{names[fast_inserter], fast_inserter},
		{names[filter_inserter], filter_inserter},
		{names[stack_inserter], stack_inserter},
		{names[stack_filter_inserter], stack_filter_inserter},
		{names[small_electric_pole], small_electric_pole},
		{names[medium_electric_pole], medium_electric_pole},
		{names[big_electric_pole], big_electric_pole},
		{names[substation], substation},
		{names[pipe], pipe},
		{names[pipe_to_ground], pipe_to_ground},
		{names[pump], pump},
		{names[rail], rail},
		{names[train_stop], train_stop},
		{names[rail_signal], rail_signal},
		{names[rail_chain_signal], rail_chain_signal},
		{names[locomotive], locomotive},
		{names[cargo_wagon], cargo_wagon},
		{names[fluid_wagon], fluid_wagon},
		{names[artillery_wagon], artillery_wagon},
		{names[car], car},
		{names[tank], tank},
		{names[spidertron], spidertron},
		{names[logistic_robot], logistic_robot},
		{names[construction_robot], construction_robot},
		{names[logistic_chest_active_provider], logistic_chest_active_provider},
		{names[logistic_chest_passive_provider], logistic_chest_passive_provider},
		{names[logistic_chest_storage], logistic_chest_storage},
		{names[logistic_chest_buffer], logistic_chest_buffer},
		{names[logistic_chest_requester], logistic_chest_requester},
		{names[roboport], roboport},
		{names[small_lamp], small_lamp},
		{names[red_wire], red_wire},
		{names[green_wire], green_wire},
		{names[arithmetic_combinator], arithmetic_combinator},
		{names[decider_combinator], decider_combinator},
		{names[constant_combinator], constant_combinator},
		{names[power_switch], power_switch},
		{names[programmable_speaker], programmable_speaker},
		{names[stone_brick], stone_brick},
		{names[concrete], concrete},
		{names[hazard_concrete], hazard_concrete},
		{names[refined_concrete], refined_concrete},
		{names[refined_hazard_concrete], refined_hazard_concrete},
		{names[landfill], landfill},
		{names[repair_pack], repair_pack},
		{names[boiler], boiler},
		{names[steam_engine], steam_engine},
		{names[solar_panel], solar_panel},
		{names[accumulator], accumulator},
		{names[nuclear_reactor], nuclear_reactor},
		{names[heat_pipe], heat_pipe},
		{names[heat_exchanger], heat_exchanger},
		{names[steam_turbine], steam_turbine},
		{names[burner_mining_drill], burner_mining_drill},
		{names[electric_mining_drill], electric_mining_drill},
		{names[offshore_pump], offshore_pump},
		{names[pumpjack], pumpjack},
		{names[stone_furnace], stone_furnace},
		{names[steel_furnace], steel_furnace},
		{names[electric_furnace], electric_furnace},
		{names[assembling_machine_1], assembling_machine_1},
		{names[assembling_machine_2], assembling_machine_2},
		{names[assembling_machine_3], assembling_machine_3},
		{names[oil_refinery], oil_refinery},
		{names[chemical_plant], chemical_plant},
		{names[centrifuge], centrifuge},
		{names[lab], lab},
		{names[beacon], beacon},
		{names[speed_module], speed_module},
		{names[speed_module_2], speed_module_2},
		{names[speed_module_3], speed_module_3},
		{names[effectivity_module], effectivity_module},
		{names[effectivity_module_2], effectivity_module_2},
		{names[effectivity_module_3], effectivity_module_3},
		{names[productivity_module], productivity_module},
		{names[productivity_module_2], productivity_module_2},
		{names[productivity_module_3], productivity_module_3},
		{names[rocket_silo], rocket_silo},
		{names[satellite], satellite},
		{names[wood], wood},
		{names[coal], coal},
		{names[stone], stone},
		{names[iron_ore], iron_ore},
		{names[copper_ore], copper_ore},
		{names[uranium_ore], uranium_ore},
		{names[raw_fish], raw_fish},
		{names[iron_plate], iron_plate},
		{names[copper_plate], copper_plate},
		{names[solid_fuel], solid_fuel},
		{names[steel_plate], steel_plate},
		{names[plastic_bar], plastic_bar},
		{names[sulfur], sulfur},
		{names[battery], battery},
		{names[explosives], explosives},
		{names[crude_oil_barrel], crude_oil_barrel},
		{names[heavy_oil_barrel], heavy_oil_barrel},
		{names[light_oil_barrel], light_oil_barrel},
		{names[lubricant_barrel], lubricant_barrel},
		{names[petroleum_gas_barrel], petroleum_gas_barrel},
		{names[sulfuric_acid_barrel], sulfuric_acid_barrel},
		{names[water_barrel], water_barrel},
		{names[copper_cable], copper_cable},
		{names[iron_stick], iron_stick},
		{names[iron_gear_wheel], iron_gear_wheel},
		{names[empty_barrel], empty_barrel},
		{names[electronic_circuit], electronic_circuit},
		{names[advanced_circuit], advanced_circuit},
		{names[processing_unit], processing_unit},
		{names[engine_unit], engine_unit},
		{names[electric_engine_unit], electric_engine_unit},
		{names[flying_robot_frame], flying_robot_frame},
		{names[rocket_control_unit], rocket_control_unit},
		{names[low_density_structure], low_density_structure},
		{names[rocket_fuel], rocket_fuel},
		{names[nuclear_fuel], nuclear_fuel},
		{names[uranium_235], uranium_235},
		{names[uranium_238], uranium_238},
		{names[uranium_fuel_cell], uranium_fuel_cell},
		{names[used_up_uranium_fuel_cell], used_up_uranium_fuel_cell},
		{names[automation_science_pack], automation_science_pack},
		{names[logistic_science_pack], logistic_science_pack},
		{names[military_science_pack], military_science_pack},
		{names[chemical_science_pack], chemical_science_pack},
		{names[production_science_pack], production_science_pack},
		{names[utility_science_pack], utility_science_pack},
		{names[space_science_pack], space_science_pack},
		{names[pistol], pistol},
		{names[submachine_gun], submachine_gun},
		{names[shotgun], shotgun},
		{names[combat_shotgun], combat_shotgun},
		{names[rocket_launcher], rocket_launcher},
		{names[flamethrower], flamethrower},
		{names[land_mine], land_mine},
		{names[firearm_magazine], firearm_magazine},
		{names[piercing_rounds_magazine], piercing_rounds_magazine},
		{names[uranium_rounds_magazine], uranium_rounds_magazine},
		{names[shotgun_shell], shotgun_shell},
		{names[piercing_shotgun_shell], piercing_shotgun_shell},
		{names[cannon_shell], cannon_shell},
		{names[explosive_cannon_shell], explosive_cannon_shell},
		{names[uranium_cannon_shell], uranium_cannon_shell},
		{names[explosive_uranium_cannon_shell], explosive_uranium_cannon_shell},
		{names[artillery_shell], artillery_shell},
		{names[rocket], rocket},
		{names[explosive_rocket], explosive_rocket},
		{names[atomic_bomb], atomic_bomb},
		{names[flamethrower_ammo], flamethrower_ammo},
		{names[grenade], grenade},
		{names[cluster_grenade], cluster_grenade},
		{names[poison_capsule], poison_capsule},
		{names[slowdown_capsule], slowdown_capsule},
		{names[defender_capsule], defender_capsule},
		{names[distractor_capsule], distractor_capsule},
		{names[destroyer_capsule], destroyer_capsule},
		{names[light_armor], light_armor},
		{names[heavy_armor], heavy_armor},
		{names[solar_panel_equipment], solar_panel_equipment},
		{names[fusion_reactor_equipment], fusion_reactor_equipment},
		{names[battery_equipment], battery_equipment},
		{names[battery_mk2_equipment], battery_mk2_equipment},
		{names[belt_immunity_equipment], belt_immunity_equipment},
		{names[exoskeleton_equipment], exoskeleton_equipment},
		{names[personal_roboport_equipment], personal_roboport_equipment},
		{names[personal_roboport_mk2_equipment], personal_roboport_mk2_equipment},
		{names[night_vision_equipment], night_vision_equipment},
		{names[energy_shield_equipment], energy_shield_equipment},
		{names[energy_shield_mk2_equipment], energy_shield_mk2_equipment},
		{names[personal_laser_defense_equipment], personal_laser_defense_equipment},
		{names[discharge_defense_equipment], discharge_defense_equipment},
		{names[discharge_defense_remote], discharge_defense_remote},
		{names[stone_wall], stone_wall},
		{names[gate], gate},
		{names[gun_turret], gun_turret},
		{names[laser_turret], laser_turret},
		{names[flamethrower_turret], flamethrower_turret},
		{names[artillery_turret], artillery_turret},
		{names[artillery_targeting_remote], artillery_targeting_remote},
		{names[radar], radar},

		{to_lower(names[wooden_chest]), wooden_chest},
		{to_lower(names[iron_chest]), iron_chest},
		{to_lower(names[steel_chest]), steel_chest},
		{to_lower(names[storage_tank]), storage_tank},
		{to_lower(names[transport_belt]), transport_belt},
		{to_lower(names[fast_transport_belt]), fast_transport_belt},
		{to_lower(names[express_transport_belt]), express_transport_belt},
		{to_lower(names[underground_belt]), underground_belt},
		{to_lower(names[fast_underground_belt]), fast_underground_belt},
		{to_lower(names[express_underground_belt]), express_underground_belt},
		{to_lower(names[splitter]), splitter},
		{to_lower(names[fast_splitter]), fast_splitter},
		{to_lower(names[express_splitter]), express_splitter},
		{to_lower(names[burner_inserter]), burner_inserter},
		{to_lower(names[inserter]), inserter},
		{to_lower(names[long_handed_inserter]), long_handed_inserter},
		{to_lower(names[fast_inserter]), fast_inserter},
		{to_lower(names[filter_inserter]), filter_inserter},
		{to_lower(names[stack_inserter]), stack_inserter},
		{to_lower(names[stack_filter_inserter]), stack_filter_inserter},
		{to_lower(names[small_electric_pole]), small_electric_pole},
		{to_lower(names[medium_electric_pole]), medium_electric_pole},
		{to_lower(names[big_electric_pole]), big_electric_pole},
		{to_lower(names[substation]), substation},
		{to_lower(names[pipe]), pipe},
		{to_lower(names[pipe_to_ground]), pipe_to_ground},
		{to_lower(names[pump]), pump},
		{to_lower(names[rail]), rail},
		{to_lower(names[train_stop]), train_stop},
		{to_lower(names[rail_signal]), rail_signal},
		{to_lower(names[rail_chain_signal]), rail_chain_signal},
		{to_lower(names[locomotive]), locomotive},
		{to_lower(names[cargo_wagon]), cargo_wagon},
		{to_lower(names[fluid_wagon]), fluid_wagon},
		{to_lower(names[artillery_wagon]), artillery_wagon},
		{to_lower(names[car]), car},
		{to_lower(names[tank]), tank},
		{to_lower(names[spidertron]), spidertron},
		{to_lower(names[logistic_robot]), logistic_robot},
		{to_lower(names[construction_robot]), construction_robot},
		{to_lower(names[logistic_chest_active_provider]), logistic_chest_active_provider},
		{to_lower(names[logistic_chest_passive_provider]), logistic_chest_passive_provider},
		{to_lower(names[logistic_chest_storage]), logistic_chest_storage},
		{to_lower(names[logistic_chest_buffer]), logistic_chest_buffer},
		{to_lower(names[logistic_chest_requester]), logistic_chest_requester},
		{to_lower(names[roboport]), roboport},
		{to_lower(names[small_lamp]), small_lamp},
		{to_lower(names[red_wire]), red_wire},
		{to_lower(names[green_wire]), green_wire},
		{to_lower(names[arithmetic_combinator]), arithmetic_combinator},
		{to_lower(names[decider_combinator]), decider_combinator},
		{to_lower(names[constant_combinator]), constant_combinator},
		{to_lower(names[power_switch]), power_switch},
		{to_lower(names[programmable_speaker]), programmable_speaker},
		{to_lower(names[stone_brick]), stone_brick},
		{to_lower(names[concrete]), concrete},
		{to_lower(names[hazard_concrete]), hazard_concrete},
		{to_lower(names[refined_concrete]), refined_concrete},
		{to_lower(names[refined_hazard_concrete]), refined_hazard_concrete},
		{to_lower(names[landfill]), landfill},
		{to_lower(names[repair_pack]), repair_pack},
		{to_lower(names[boiler]), boiler},
		{to_lower(names[steam_engine]), steam_engine},
		{to_lower(names[solar_panel]), solar_panel},
		{to_lower(names[accumulator]), accumulator},
		{to_lower(names[nuclear_reactor]), nuclear_reactor},
		{to_lower(names[heat_pipe]), heat_pipe},
		{to_lower(names[heat_exchanger]), heat_exchanger},
		{to_lower(names[steam_turbine]), steam_turbine},
		{to_lower(names[burner_mining_drill]), burner_mining_drill},
		{to_lower(names[electric_mining_drill]), electric_mining_drill},
		{to_lower(names[offshore_pump]), offshore_pump},
		{to_lower(names[pumpjack]), pumpjack},
		{to_lower(names[stone_furnace]), stone_furnace},
		{to_lower(names[steel_furnace]), steel_furnace},
		{to_lower(names[electric_furnace]), electric_furnace},
		{to_lower(names[assembling_machine_1]), assembling_machine_1},
		{to_lower(names[assembling_machine_2]), assembling_machine_2},
		{to_lower(names[assembling_machine_3]), assembling_machine_3},
		{to_lower(names[oil_refinery]), oil_refinery},
		{to_lower(names[chemical_plant]), chemical_plant},
		{to_lower(names[centrifuge]), centrifuge},
		{to_lower(names[lab]), lab},
		{to_lower(names[beacon]), beacon},
		{to_lower(names[speed_module]), speed_module},
		{to_lower(names[speed_module_2]), speed_module_2},
		{to_lower(names[speed_module_3]), speed_module_3},
		{to_lower(names[effectivity_module]), effectivity_module},
		{to_lower(names[effectivity_module_2]), effectivity_module_2},
		{to_lower(names[effectivity_module_3]), effectivity_module_3},
		{to_lower(names[productivity_module]), productivity_module},
		{to_lower(names[productivity_module_2]), productivity_module_2},
		{to_lower(names[productivity_module_3]), productivity_module_3},
		{to_lower(names[rocket_silo]), rocket_silo},
		{to_lower(names[satellite]), satellite},
		{to_lower(names[wood]), wood},
		{to_lower(names[coal]), coal},
		{to_lower(names[stone]), stone},
		{to_lower(names[iron_ore]), iron_ore},
		{to_lower(names[copper_ore]), copper_ore},
		{to_lower(names[uranium_ore]), uranium_ore},
		{to_lower(names[raw_fish]), raw_fish},
		{to_lower(names[iron_plate]), iron_plate},
		{to_lower(names[copper_plate]), copper_plate},
		{to_lower(names[solid_fuel]), solid_fuel},
		{to_lower(names[steel_plate]), steel_plate},
		{to_lower(names[plastic_bar]), plastic_bar},
		{to_lower(names[sulfur]), sulfur},
		{to_lower(names[battery]), battery},
		{to_lower(names[explosives]), explosives},
		{to_lower(names[crude_oil_barrel]), crude_oil_barrel},
		{to_lower(names[heavy_oil_barrel]), heavy_oil_barrel},
		{to_lower(names[light_oil_barrel]), light_oil_barrel},
		{to_lower(names[lubricant_barrel]), lubricant_barrel},
		{to_lower(names[petroleum_gas_barrel]), petroleum_gas_barrel},
		{to_lower(names[sulfuric_acid_barrel]), sulfuric_acid_barrel},
		{to_lower(names[water_barrel]), water_barrel},
		{to_lower(names[copper_cable]), copper_cable},
		{to_lower(names[iron_stick]), iron_stick},
		{to_lower(names[iron_gear_wheel]), iron_gear_wheel},
		{to_lower(names[empty_barrel]), empty_barrel},
		{to_lower(names[electronic_circuit]), electronic_circuit},
		{to_lower(names[advanced_circuit]), advanced_circuit},
		{to_lower(names[processing_unit]), processing_unit},
		{to_lower(names[engine_unit]), engine_unit},
		{to_lower(names[electric_engine_unit]), electric_engine_unit},
		{to_lower(names[flying_robot_frame]), flying_robot_frame},
		{to_lower(names[rocket_control_unit]), rocket_control_unit},
		{to_lower(names[low_density_structure]), low_density_structure},
		{to_lower(names[rocket_fuel]), rocket_fuel},
		{to_lower(names[nuclear_fuel]), nuclear_fuel},
		{to_lower(names[uranium_235]), uranium_235},
		{to_lower(names[uranium_238]), uranium_238},
		{to_lower(names[uranium_fuel_cell]), uranium_fuel_cell},
		{to_lower(names[used_up_uranium_fuel_cell]), used_up_uranium_fuel_cell},
		{to_lower(names[automation_science_pack]), automation_science_pack},
		{to_lower(names[logistic_science_pack]), logistic_science_pack},
		{to_lower(names[military_science_pack]), military_science_pack},
		{to_lower(names[chemical_science_pack]), chemical_science_pack},
		{to_lower(names[production_science_pack]), production_science_pack},
		{to_lower(names[utility_science_pack]), utility_science_pack},
		{to_lower(names[space_science_pack]), space_science_pack},
		{to_lower(names[pistol]), pistol},
		{to_lower(names[submachine_gun]), submachine_gun},
		{to_lower(names[shotgun]), shotgun},
		{to_lower(names[combat_shotgun]), combat_shotgun},
		{to_lower(names[rocket_launcher]), rocket_launcher},
		{to_lower(names[flamethrower]), flamethrower},
		{to_lower(names[land_mine]), land_mine},
		{to_lower(names[firearm_magazine]), firearm_magazine},
		{to_lower(names[piercing_rounds_magazine]), piercing_rounds_magazine},
		{to_lower(names[uranium_rounds_magazine]), uranium_rounds_magazine},
		{to_lower(names[shotgun_shell]), shotgun_shell},
		{to_lower(names[piercing_shotgun_shell]), piercing_shotgun_shell},
		{to_lower(names[cannon_shell]), cannon_shell},
		{to_lower(names[explosive_cannon_shell]), explosive_cannon_shell},
		{to_lower(names[uranium_cannon_shell]), uranium_cannon_shell},
		{to_lower(names[explosive_uranium_cannon_shell]), explosive_uranium_cannon_shell},
		{to_lower(names[artillery_shell]), artillery_shell},
		{to_lower(names[rocket]), rocket},
		{to_lower(names[explosive_rocket]), explosive_rocket},
		{to_lower(names[atomic_bomb]), atomic_bomb},
		{to_lower(names[flamethrower_ammo]), flamethrower_ammo},
		{to_lower(names[grenade]), grenade},
		{to_lower(names[cluster_grenade]), cluster_grenade},
		{to_lower(names[poison_capsule]), poison_capsule},
		{to_lower(names[slowdown_capsule]), slowdown_capsule},
		{to_lower(names[defender_capsule]), defender_capsule},
		{to_lower(names[distractor_capsule]), distractor_capsule},
		{to_lower(names[destroyer_capsule]), destroyer_capsule},
		{to_lower(names[light_armor]), light_armor},
		{to_lower(names[heavy_armor]), heavy_armor},
		{to_lower(names[solar_panel_equipment]), solar_panel_equipment},
		{to_lower(names[fusion_reactor_equipment]), fusion_reactor_equipment},
		{to_lower(names[battery_equipment]), battery_equipment},
		{to_lower(names[battery_mk2_equipment]), battery_mk2_equipment},
		{to_lower(names[belt_immunity_equipment]), belt_immunity_equipment},
		{to_lower(names[exoskeleton_equipment]), exoskeleton_equipment},
		{to_lower(names[personal_roboport_equipment]), personal_roboport_equipment},
		{to_lower(names[personal_roboport_mk2_equipment]), personal_roboport_mk2_equipment},
		{to_lower(names[night_vision_equipment]), night_vision_equipment},
		{to_lower(names[energy_shield_equipment]), energy_shield_equipment},
		{to_lower(names[energy_shield_mk2_equipment]), energy_shield_mk2_equipment},
		{to_lower(names[personal_laser_defense_equipment]), personal_laser_defense_equipment},
		{to_lower(names[discharge_defense_equipment]), discharge_defense_equipment},
		{to_lower(names[discharge_defense_remote]), discharge_defense_remote},
		{to_lower(names[stone_wall]), stone_wall},
		{to_lower(names[gate]), gate},
		{to_lower(names[gun_turret]), gun_turret},
		{to_lower(names[laser_turret]), laser_turret},
		{to_lower(names[flamethrower_turret]), flamethrower_turret},
		{to_lower(names[artillery_turret]), artillery_turret},
		{to_lower(names[artillery_targeting_remote]), artillery_targeting_remote},
		{to_lower(names[radar]), radar},
	};

};
