#include "Recipe.h"

using namespace CRAFTING;

string Ingredient::Name()
{
	return IngredientNames[type];
}

bool Ingredient::IsValid()
{
	return count > 0 && type != Ingredient::none;
}

// Returns the IngredientType that matches the string, defaults to none
Ingredient::IngredientType Ingredient::MapStringToIngredientType(const string str)
{
	auto mapped = map_ingredientname_to_ingredienttype.find(str);
	return mapped != map_ingredientname_to_ingredienttype.end() ? mapped->second : IngredientType::none;
}

// Returns the IngredientType that matches the string, defaults to None
Ingredient::IngredientType Ingredient::MapStringToIngredientType(const wxString str)
{
	return MapStringToIngredientType(str.ToStdString());
}

string Recipe::Name()
{
	return RecipeNames[type];
}

bool Recipe::IsMadeBy(CRAFTING::CraftingMachines machine)
{
	return (made_in & machine) == machine;
}

vector<Ingredient> Recipe::GetItemIngredients()
{
	vector<Ingredient> return_items{};
	for (auto& ingredient : ingredients)
		if (ingredient.is_item)
			return_items.push_back(ingredient);
	return return_items;
}

bool Recipe::MapStringToRecipeType(const string str, RecipeType& type) {
	auto found = map_recipename_to_recipetype.find(str);
	if (found == map_recipename_to_recipetype.end())
		return false;
	type = found->second;
	return true;
}
bool Recipe::MapStringToRecipeType(const wxString str, RecipeType& type) {
	return MapStringToRecipeType(str.ToStdString(), type);
}
Recipe::RecipeType Recipe::MapStringToRecipeType(const string str) {
	RecipeType type = Recipe::none;
	MapStringToRecipeType(str, type);
	return type;
}
Recipe::RecipeType Recipe::MapStringToRecipeType(const wxString str) {
	return MapStringToRecipeType(str.ToStdString());
}

vector<Recipe> Recipes = {
	{Recipe::RecipeType::none, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3 | CraftingMachines::ChemicalPlant | CraftingMachines::OilRefinery, {}},

	{Recipe::RecipeType::assembling_machine_1, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 9, true}, {Ingredient::IngredientType::iron_gear_wheel, 5, true}, {Ingredient::IngredientType::electronic_circuit, 3, true}, }},
	{Recipe::RecipeType::automation_science_pack, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 1, true}, {Ingredient::IngredientType::iron_gear_wheel, 1, true}, }},
	{Recipe::RecipeType::firearm_magazine, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 4, true}, }},
	{Recipe::RecipeType::pistol, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 5, true}, {Ingredient::IngredientType::copper_plate, 5, true}, }},
	{Recipe::RecipeType::piercing_rounds_magazine, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 5, true}, {Ingredient::IngredientType::steel_plate, 1, true}, {Ingredient::IngredientType::firearm_magazine, 1, true}, }},
	{Recipe::RecipeType::submachine_gun, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 10, true}, {Ingredient::IngredientType::copper_plate, 5, true}, {Ingredient::IngredientType::iron_gear_wheel, 10, true}, }},
	{Recipe::RecipeType::uranium_rounds_magazine, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::uranium_238, 1, true}, {Ingredient::IngredientType::piercing_rounds_magazine, 1, true}, }},
	{Recipe::RecipeType::beacon, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 10, true}, {Ingredient::IngredientType::copper_cable, 10, true}, {Ingredient::IngredientType::electronic_circuit, 20, true}, {Ingredient::IngredientType::advanced_circuit, 20, true}, }},
	{Recipe::RecipeType::burner_inserter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 1, true}, {Ingredient::IngredientType::iron_gear_wheel, 1, true}, }},
	{Recipe::RecipeType::copper_cable, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 1, true}, }},
	{Recipe::RecipeType::electric_energy_interface, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 2, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, }},
	{Recipe::RecipeType::solar_panel_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::advanced_circuit, 2, true}, {Ingredient::IngredientType::solar_panel, 1, true}, }},
	{Recipe::RecipeType::fusion_reactor_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 200, true}, {Ingredient::IngredientType::low_density_structure, 50, true}, }},
	{Recipe::RecipeType::small_electric_pole, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::wood, 1, true}, {Ingredient::IngredientType::copper_cable, 2, true}, }},
	{Recipe::RecipeType::medium_electric_pole, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 2, true}, {Ingredient::IngredientType::steel_plate, 2, true}, {Ingredient::IngredientType::iron_stick, 4, true}, }},
	{Recipe::RecipeType::big_electric_pole, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 5, true}, {Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::iron_stick, 8, true}, }},
	{Recipe::RecipeType::substation, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 5, true}, {Ingredient::IngredientType::steel_plate, 10, true}, {Ingredient::IngredientType::advanced_circuit, 5, true}, }},
	{Recipe::RecipeType::sulfuric_acid, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::iron_plate, 1, true}, {Ingredient::IngredientType::sulfur, 5, true}, {Ingredient::IngredientType::water, 100, false}, }},
	{Recipe::RecipeType::grenade, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::coal, 10, true}, {Ingredient::IngredientType::iron_plate, 5, true}, }},
	{Recipe::RecipeType::cluster_grenade, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::explosives, 5, true}, {Ingredient::IngredientType::grenade, 7, true}, }},
	{Recipe::RecipeType::burner_mining_drill, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 3, true}, {Ingredient::IngredientType::iron_gear_wheel, 3, true}, {Ingredient::IngredientType::stone_furnace, 1, true}, }},
	{Recipe::RecipeType::wooden_chest, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::wood, 2, true}, }},
	{Recipe::RecipeType::electric_mining_drill, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 10, true}, {Ingredient::IngredientType::iron_gear_wheel, 5, true}, {Ingredient::IngredientType::electronic_circuit, 3, true}, }},
	{Recipe::RecipeType::iron_chest, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 8, true}, }},
	{Recipe::RecipeType::steel_chest, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 8, true}, }},
	{Recipe::RecipeType::light_armor, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 40, true}, }},
	{Recipe::RecipeType::small_lamp, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 1, true}, {Ingredient::IngredientType::copper_cable, 3, true}, {Ingredient::IngredientType::electronic_circuit, 1, true}, }},
	{Recipe::RecipeType::basic_oil_processing, CraftingMachines::OilRefinery, {{Ingredient::IngredientType::crude_oil, 100, false}, }},
	{Recipe::RecipeType::advanced_oil_processing, CraftingMachines::OilRefinery, {{Ingredient::IngredientType::water, 50, false}, {Ingredient::IngredientType::crude_oil, 100, false}, }},
	{Recipe::RecipeType::coal_liquefaction, CraftingMachines::OilRefinery, {{Ingredient::IngredientType::coal, 10, true}, {Ingredient::IngredientType::heavy_oil, 25, false}, {Ingredient::IngredientType::steam, 50, false}, }},
	{Recipe::RecipeType::pipe, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 1, true}, }},
	{Recipe::RecipeType::pipe_to_ground, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 5, true}, {Ingredient::IngredientType::pipe, 10, true}, }},
	{Recipe::RecipeType::logistic_robot, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::advanced_circuit, 2, true}, {Ingredient::IngredientType::flying_robot_frame, 1, true}, }},
	{Recipe::RecipeType::construction_robot, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 2, true}, {Ingredient::IngredientType::flying_robot_frame, 1, true}, }},
	{Recipe::RecipeType::energy_shield_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 10, true}, {Ingredient::IngredientType::advanced_circuit, 5, true}, }},
	{Recipe::RecipeType::energy_shield_mk2_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 5, true}, {Ingredient::IngredientType::low_density_structure, 5, true}, {Ingredient::IngredientType::energy_shield_equipment, 10, true}, }},
	{Recipe::RecipeType::speed_module, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 5, true}, {Ingredient::IngredientType::advanced_circuit, 5, true}, }},
	{Recipe::RecipeType::speed_module_2, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::advanced_circuit, 5, true}, {Ingredient::IngredientType::processing_unit, 5, true}, {Ingredient::IngredientType::speed_module, 4, true}, }},
	{Recipe::RecipeType::speed_module_3, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::advanced_circuit, 5, true}, {Ingredient::IngredientType::processing_unit, 5, true}, {Ingredient::IngredientType::speed_module_2, 5, true}, }},
	{Recipe::RecipeType::stone_brick, CraftingMachines::StoneFurnace | CraftingMachines::SteelFurnace | CraftingMachines::ElectricFurnace, {{Ingredient::IngredientType::stone, 2, true}, }},
	{Recipe::RecipeType::stone_furnace, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::stone, 5, true}, }},
	{Recipe::RecipeType::stone_wall, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::stone_brick, 5, true}, }},
	{Recipe::RecipeType::rail, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::stone, 1, true}, {Ingredient::IngredientType::steel_plate, 1, true}, {Ingredient::IngredientType::iron_stick, 1, true}, }},
	{Recipe::RecipeType::train_stop, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 6, true}, {Ingredient::IngredientType::steel_plate, 3, true}, {Ingredient::IngredientType::iron_stick, 6, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, }},
	{Recipe::RecipeType::rail_signal, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 5, true}, {Ingredient::IngredientType::electronic_circuit, 1, true}, }},
	{Recipe::RecipeType::rail_chain_signal, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 5, true}, {Ingredient::IngredientType::electronic_circuit, 1, true}, }},
	{Recipe::RecipeType::locomotive, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 30, true}, {Ingredient::IngredientType::electronic_circuit, 10, true}, {Ingredient::IngredientType::engine_unit, 20, true}, }},
	{Recipe::RecipeType::cargo_wagon, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 20, true}, {Ingredient::IngredientType::steel_plate, 20, true}, {Ingredient::IngredientType::iron_gear_wheel, 10, true}, }},
	{Recipe::RecipeType::fluid_wagon, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 16, true}, {Ingredient::IngredientType::iron_gear_wheel, 10, true}, {Ingredient::IngredientType::storage_tank, 1, true}, {Ingredient::IngredientType::pipe, 8, true}, }},
	{Recipe::RecipeType::artillery_wagon, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 40, true}, {Ingredient::IngredientType::iron_gear_wheel, 10, true}, {Ingredient::IngredientType::advanced_circuit, 20, true}, {Ingredient::IngredientType::engine_unit, 64, true}, {Ingredient::IngredientType::pipe, 16, true}, }},
	{Recipe::RecipeType::transport_belt, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 1, true}, {Ingredient::IngredientType::iron_gear_wheel, 1, true}, }},
	{Recipe::RecipeType::fast_transport_belt, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 5, true}, {Ingredient::IngredientType::transport_belt, 1, true}, }},
	{Recipe::RecipeType::express_transport_belt, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 10, true}, {Ingredient::IngredientType::fast_transport_belt, 1, true}, {Ingredient::IngredientType::lubricant, 20, false}, }},
	{Recipe::RecipeType::gate, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 2, true}, {Ingredient::IngredientType::electronic_circuit, 2, true}, {Ingredient::IngredientType::stone_wall, 1, true}, }},
	{Recipe::RecipeType::personal_laser_defense_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 20, true}, {Ingredient::IngredientType::low_density_structure, 5, true}, {Ingredient::IngredientType::laser_turret, 5, true}, }},
	{Recipe::RecipeType::discharge_defense_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 20, true}, {Ingredient::IngredientType::processing_unit, 5, true}, {Ingredient::IngredientType::laser_turret, 10, true}, }},
	{Recipe::RecipeType::discharge_defense_remote, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 1, true}, }},
	{Recipe::RecipeType::assembling_machine_2, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 2, true}, {Ingredient::IngredientType::iron_gear_wheel, 5, true}, {Ingredient::IngredientType::electronic_circuit, 3, true}, {Ingredient::IngredientType::assembling_machine_1, 1, true}, }},
	{Recipe::RecipeType::battery_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 10, true}, {Ingredient::IngredientType::battery, 5, true}, }},
	{Recipe::RecipeType::battery_mk2_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 15, true}, {Ingredient::IngredientType::low_density_structure, 5, true}, {Ingredient::IngredientType::battery_equipment, 10, true}, }},
	{Recipe::RecipeType::concrete, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_ore, 1, true}, {Ingredient::IngredientType::stone_brick, 5, true}, {Ingredient::IngredientType::water, 100, false}, }},
	{Recipe::RecipeType::hazard_concrete, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::concrete, 10, true}, }},
	{Recipe::RecipeType::refined_concrete, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 1, true}, {Ingredient::IngredientType::iron_stick, 8, true}, {Ingredient::IngredientType::concrete, 20, true}, {Ingredient::IngredientType::water, 100, false}, }},
	{Recipe::RecipeType::refined_hazard_concrete, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::refined_concrete, 10, true}, }},
	{Recipe::RecipeType::fill_crude_oil_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::empty_barrel, 1, true}, {Ingredient::IngredientType::crude_oil, 50, false}, }},
	{Recipe::RecipeType::fill_heavy_oil_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::empty_barrel, 1, true}, {Ingredient::IngredientType::heavy_oil, 50, false}, }},
	{Recipe::RecipeType::fill_light_oil_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::empty_barrel, 1, true}, {Ingredient::IngredientType::light_oil, 50, false}, }},
	{Recipe::RecipeType::fill_lubricant_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::empty_barrel, 1, true}, {Ingredient::IngredientType::lubricant, 50, false}, }},
	{Recipe::RecipeType::fill_petroleum_gas_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::empty_barrel, 1, true}, {Ingredient::IngredientType::petroleum_gas, 50, false}, }},
	{Recipe::RecipeType::fill_sulfuric_acid_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::empty_barrel, 1, true}, {Ingredient::IngredientType::sulfuric_acid, 50, false}, }},
	{Recipe::RecipeType::fill_water_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::empty_barrel, 1, true}, {Ingredient::IngredientType::water, 50, false}, }},
	{Recipe::RecipeType::heavy_oil_cracking, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::water, 30, false}, {Ingredient::IngredientType::heavy_oil, 40, false}, }},
	{Recipe::RecipeType::light_oil_cracking, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::water, 30, false}, {Ingredient::IngredientType::light_oil, 30, false}, }},
	{Recipe::RecipeType::solid_fuel_from_light_oil, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::light_oil, 10, false}, }},
	{Recipe::RecipeType::solid_fuel_from_petroleum_gas, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::petroleum_gas, 20, false}, }},
	{Recipe::RecipeType::solid_fuel_from_heavy_oil, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::heavy_oil, 20, false}, }},
	{Recipe::RecipeType::storage_tank, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 20, true}, {Ingredient::IngredientType::steel_plate, 5, true}, }},
	{Recipe::RecipeType::offshore_pump, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 1, true}, {Ingredient::IngredientType::electronic_circuit, 2, true}, {Ingredient::IngredientType::pipe, 1, true}, }},
	{Recipe::RecipeType::pumpjack, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::iron_gear_wheel, 10, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, {Ingredient::IngredientType::pipe, 10, true}, }},
	{Recipe::RecipeType::heavy_armor, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 100, true}, {Ingredient::IngredientType::steel_plate, 50, true}, }},
	{Recipe::RecipeType::inserter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 1, true}, {Ingredient::IngredientType::iron_gear_wheel, 1, true}, {Ingredient::IngredientType::electronic_circuit, 1, true}, }},
	{Recipe::RecipeType::iron_plate, CraftingMachines::StoneFurnace | CraftingMachines::SteelFurnace | CraftingMachines::ElectricFurnace, {{Ingredient::IngredientType::iron_ore, 1, true}, }},
	{Recipe::RecipeType::iron_stick, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 1, true}, }},
	{Recipe::RecipeType::logistic_science_pack, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::transport_belt, 1, true}, {Ingredient::IngredientType::inserter, 1, true}, }},
	{Recipe::RecipeType::car, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 20, true}, {Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::engine_unit, 8, true}, }},
	{Recipe::RecipeType::tank, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 50, true}, {Ingredient::IngredientType::iron_gear_wheel, 15, true}, {Ingredient::IngredientType::advanced_circuit, 10, true}, {Ingredient::IngredientType::engine_unit, 32, true}, }},
	{Recipe::RecipeType::spidertron, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::raw_fish, 1, true}, {Ingredient::IngredientType::rocket_control_unit, 16, true}, {Ingredient::IngredientType::low_density_structure, 150, true}, {Ingredient::IngredientType::effectivity_module_3, 2, true}, {Ingredient::IngredientType::rocket_launcher, 4, true}, {Ingredient::IngredientType::fusion_reactor_equipment, 2, true}, {Ingredient::IngredientType::exoskeleton_equipment, 4, true}, {Ingredient::IngredientType::radar, 2, true}, }},
	{Recipe::RecipeType::spidertron_remote, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::rocket_control_unit, 1, true}, {Ingredient::IngredientType::radar, 1, true}, }},
	{Recipe::RecipeType::pump, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 1, true}, {Ingredient::IngredientType::engine_unit, 1, true}, {Ingredient::IngredientType::pipe, 1, true}, }},
	{Recipe::RecipeType::poison_capsule, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::coal, 10, true}, {Ingredient::IngredientType::steel_plate, 3, true}, {Ingredient::IngredientType::electronic_circuit, 3, true}, }},
	{Recipe::RecipeType::repair_pack, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 2, true}, {Ingredient::IngredientType::electronic_circuit, 2, true}, }},
	{Recipe::RecipeType::shotgun, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::wood, 5, true}, {Ingredient::IngredientType::iron_plate, 15, true}, {Ingredient::IngredientType::copper_plate, 10, true}, {Ingredient::IngredientType::iron_gear_wheel, 5, true}, }},
	{Recipe::RecipeType::shotgun_shell, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 2, true}, {Ingredient::IngredientType::copper_plate, 2, true}, }},
	{Recipe::RecipeType::combat_shotgun, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::wood, 10, true}, {Ingredient::IngredientType::copper_plate, 10, true}, {Ingredient::IngredientType::steel_plate, 15, true}, {Ingredient::IngredientType::iron_gear_wheel, 5, true}, }},
	{Recipe::RecipeType::piercing_shotgun_shell, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 5, true}, {Ingredient::IngredientType::steel_plate, 2, true}, {Ingredient::IngredientType::shotgun_shell, 2, true}, }},
	{Recipe::RecipeType::boiler, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::pipe, 4, true}, {Ingredient::IngredientType::stone_furnace, 1, true}, }},
	{Recipe::RecipeType::steam_engine, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 10, true}, {Ingredient::IngredientType::iron_gear_wheel, 8, true}, {Ingredient::IngredientType::pipe, 5, true}, }},
	{Recipe::RecipeType::steel_furnace, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 6, true}, {Ingredient::IngredientType::stone_brick, 10, true}, }},
	{Recipe::RecipeType::logistic_chest_active_provider, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 3, true}, {Ingredient::IngredientType::advanced_circuit, 1, true}, {Ingredient::IngredientType::steel_chest, 1, true}, }},
	{Recipe::RecipeType::logistic_chest_passive_provider, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 3, true}, {Ingredient::IngredientType::advanced_circuit, 1, true}, {Ingredient::IngredientType::steel_chest, 1, true}, }},
	{Recipe::RecipeType::logistic_chest_storage, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 3, true}, {Ingredient::IngredientType::advanced_circuit, 1, true}, {Ingredient::IngredientType::steel_chest, 1, true}, }},
	{Recipe::RecipeType::logistic_chest_buffer, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 3, true}, {Ingredient::IngredientType::advanced_circuit, 1, true}, {Ingredient::IngredientType::steel_chest, 1, true}, }},
	{Recipe::RecipeType::logistic_chest_requester, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 3, true}, {Ingredient::IngredientType::advanced_circuit, 1, true}, {Ingredient::IngredientType::steel_chest, 1, true}, }},
	{Recipe::RecipeType::gun_turret, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 20, true}, {Ingredient::IngredientType::copper_plate, 10, true}, {Ingredient::IngredientType::iron_gear_wheel, 10, true}, }},
	{Recipe::RecipeType::laser_turret, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 20, true}, {Ingredient::IngredientType::battery, 12, true}, {Ingredient::IngredientType::electronic_circuit, 20, true}, }},
	{Recipe::RecipeType::flamethrower_turret, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 30, true}, {Ingredient::IngredientType::iron_gear_wheel, 15, true}, {Ingredient::IngredientType::engine_unit, 5, true}, {Ingredient::IngredientType::pipe, 10, true}, }},
	{Recipe::RecipeType::artillery_turret, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 60, true}, {Ingredient::IngredientType::iron_gear_wheel, 40, true}, {Ingredient::IngredientType::advanced_circuit, 20, true}, {Ingredient::IngredientType::concrete, 60, true}, }},
	{Recipe::RecipeType::artillery_targeting_remote, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 1, true}, {Ingredient::IngredientType::radar, 1, true}, }},
	{Recipe::RecipeType::underground_belt, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 10, true}, {Ingredient::IngredientType::transport_belt, 5, true}, }},
	{Recipe::RecipeType::fast_underground_belt, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 40, true}, {Ingredient::IngredientType::underground_belt, 2, true}, }},
	{Recipe::RecipeType::express_underground_belt, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 80, true}, {Ingredient::IngredientType::fast_underground_belt, 2, true}, {Ingredient::IngredientType::lubricant, 40, false}, }},
	{Recipe::RecipeType::red_wire, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_cable, 1, true}, {Ingredient::IngredientType::electronic_circuit, 1, true}, }},
	{Recipe::RecipeType::green_wire, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_cable, 1, true}, {Ingredient::IngredientType::electronic_circuit, 1, true}, }},
	{Recipe::RecipeType::assembling_machine_3, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::assembling_machine_2, 2, true}, {Ingredient::IngredientType::speed_module, 4, true}, }},
	{Recipe::RecipeType::belt_immunity_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 10, true}, {Ingredient::IngredientType::advanced_circuit, 5, true}, }},
	{Recipe::RecipeType::arithmetic_combinator, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_cable, 5, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, }},
	{Recipe::RecipeType::decider_combinator, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_cable, 5, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, }},
	{Recipe::RecipeType::constant_combinator, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_cable, 5, true}, {Ingredient::IngredientType::electronic_circuit, 2, true}, }},
	{Recipe::RecipeType::copper_plate, CraftingMachines::StoneFurnace | CraftingMachines::SteelFurnace | CraftingMachines::ElectricFurnace, {{Ingredient::IngredientType::copper_ore, 1, true}, }},
	{Recipe::RecipeType::empty_heavy_oil_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::heavy_oil_barrel, 1, true}, }},
	{Recipe::RecipeType::empty_light_oil_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::light_oil_barrel, 1, true}, }},
	{Recipe::RecipeType::empty_lubricant_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::lubricant_barrel, 1, true}, }},
	{Recipe::RecipeType::empty_petroleum_gas_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::petroleum_gas_barrel, 1, true}, }},
	{Recipe::RecipeType::empty_sulfuric_acid_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::sulfuric_acid_barrel, 1, true}, }},
	{Recipe::RecipeType::empty_water_barrel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::water_barrel, 1, true}, }},
	{Recipe::RecipeType::iron_gear_wheel, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 2, true}, }},
	{Recipe::RecipeType::landfill, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::stone, 20, true}, }},
	{Recipe::RecipeType::long_handed_inserter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 1, true}, {Ingredient::IngredientType::iron_gear_wheel, 1, true}, {Ingredient::IngredientType::inserter, 1, true}, }},
	{Recipe::RecipeType::military_science_pack, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::piercing_rounds_magazine, 1, true}, {Ingredient::IngredientType::grenade, 1, true}, {Ingredient::IngredientType::stone_wall, 2, true}, }},
	{Recipe::RecipeType::modular_armor, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 50, true}, {Ingredient::IngredientType::advanced_circuit, 30, true}, }},
	{Recipe::RecipeType::productivity_module, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 5, true}, {Ingredient::IngredientType::advanced_circuit, 5, true}, }},
	{Recipe::RecipeType::productivity_module_2, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::advanced_circuit, 5, true}, {Ingredient::IngredientType::processing_unit, 5, true}, {Ingredient::IngredientType::productivity_module, 4, true}, }},
	{Recipe::RecipeType::productivity_module_3, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::advanced_circuit, 5, true}, {Ingredient::IngredientType::processing_unit, 5, true}, {Ingredient::IngredientType::productivity_module_2, 5, true}, }},
	{Recipe::RecipeType::roboport, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 45, true}, {Ingredient::IngredientType::iron_gear_wheel, 45, true}, {Ingredient::IngredientType::advanced_circuit, 45, true}, }},
	{Recipe::RecipeType::slowdown_capsule, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::coal, 5, true}, {Ingredient::IngredientType::steel_plate, 2, true}, {Ingredient::IngredientType::electronic_circuit, 2, true}, }},
	{Recipe::RecipeType::splitter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 5, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, {Ingredient::IngredientType::transport_belt, 4, true}, }},
	{Recipe::RecipeType::fast_splitter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 10, true}, {Ingredient::IngredientType::electronic_circuit, 10, true}, {Ingredient::IngredientType::splitter, 1, true}, }},
	{Recipe::RecipeType::express_splitter, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 10, true}, {Ingredient::IngredientType::advanced_circuit, 10, true}, {Ingredient::IngredientType::fast_splitter, 1, true}, {Ingredient::IngredientType::lubricant, 80, false}, }},
	{Recipe::RecipeType::cannon_shell, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 2, true}, {Ingredient::IngredientType::plastic_bar, 2, true}, {Ingredient::IngredientType::explosives, 1, true}, }},
	{Recipe::RecipeType::explosive_cannon_shell, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 2, true}, {Ingredient::IngredientType::plastic_bar, 2, true}, {Ingredient::IngredientType::explosives, 2, true}, }},
	{Recipe::RecipeType::uranium_cannon_shell, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::uranium_238, 1, true}, {Ingredient::IngredientType::cannon_shell, 1, true}, }},
	{Recipe::RecipeType::chemical_science_pack, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::sulfur, 1, true}, {Ingredient::IngredientType::advanced_circuit, 3, true}, {Ingredient::IngredientType::engine_unit, 2, true}, }},
	{Recipe::RecipeType::cliff_explosives, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::explosives, 10, true}, {Ingredient::IngredientType::empty_barrel, 1, true}, {Ingredient::IngredientType::grenade, 1, true}, }},
	{Recipe::RecipeType::defender_capsule, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 3, true}, {Ingredient::IngredientType::electronic_circuit, 3, true}, {Ingredient::IngredientType::piercing_rounds_magazine, 3, true}, }},
	{Recipe::RecipeType::empty_barrel, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 1, true}, }},
	{Recipe::RecipeType::exoskeleton_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 20, true}, {Ingredient::IngredientType::processing_unit, 10, true}, {Ingredient::IngredientType::electric_engine_unit, 30, true}, }},
	{Recipe::RecipeType::explosive_uranium_cannon_shell, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::uranium_238, 1, true}, {Ingredient::IngredientType::explosive_cannon_shell, 1, true}, }},
	{Recipe::RecipeType::artillery_shell, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::explosives, 8, true}, {Ingredient::IngredientType::explosive_cannon_shell, 4, true}, {Ingredient::IngredientType::radar, 1, true}, }},
	{Recipe::RecipeType::fast_inserter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 2, true}, {Ingredient::IngredientType::electronic_circuit, 2, true}, {Ingredient::IngredientType::inserter, 1, true}, }},
	{Recipe::RecipeType::power_switch, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 5, true}, {Ingredient::IngredientType::copper_cable, 5, true}, {Ingredient::IngredientType::electronic_circuit, 2, true}, }},
	{Recipe::RecipeType::programmable_speaker, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 3, true}, {Ingredient::IngredientType::copper_cable, 5, true}, {Ingredient::IngredientType::iron_stick, 4, true}, {Ingredient::IngredientType::electronic_circuit, 4, true}, }},
	{Recipe::RecipeType::power_armor, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 40, true}, {Ingredient::IngredientType::processing_unit, 40, true}, {Ingredient::IngredientType::electric_engine_unit, 20, true}, }},
	{Recipe::RecipeType::radar, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 10, true}, {Ingredient::IngredientType::iron_gear_wheel, 5, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, }},
	{Recipe::RecipeType::oil_refinery, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 15, true}, {Ingredient::IngredientType::iron_gear_wheel, 10, true}, {Ingredient::IngredientType::electronic_circuit, 10, true}, {Ingredient::IngredientType::pipe, 10, true}, {Ingredient::IngredientType::stone_brick, 10, true}, }},
	{Recipe::RecipeType::rocket_launcher, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 5, true}, {Ingredient::IngredientType::iron_gear_wheel, 5, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, }},
	{Recipe::RecipeType::rocket, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 2, true}, {Ingredient::IngredientType::explosives, 1, true}, {Ingredient::IngredientType::electronic_circuit, 1, true}, }},
	{Recipe::RecipeType::explosive_rocket, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::explosives, 2, true}, {Ingredient::IngredientType::rocket, 1, true}, }},
	{Recipe::RecipeType::atomic_bomb, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::explosives, 10, true}, {Ingredient::IngredientType::rocket_control_unit, 10, true}, {Ingredient::IngredientType::uranium_235, 30, true}, }},
	{Recipe::RecipeType::solar_panel, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 5, true}, {Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::electronic_circuit, 15, true}, }},
	{Recipe::RecipeType::steel_plate, CraftingMachines::StoneFurnace | CraftingMachines::SteelFurnace | CraftingMachines::ElectricFurnace, {{Ingredient::IngredientType::iron_plate, 5, true}, }},
	{Recipe::RecipeType::accumulator, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 2, true}, {Ingredient::IngredientType::battery, 5, true}, }},
	{Recipe::RecipeType::chemical_plant, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::iron_gear_wheel, 5, true}, {Ingredient::IngredientType::electronic_circuit, 5, true}, {Ingredient::IngredientType::pipe, 5, true}, }},
	{Recipe::RecipeType::distractor_capsule, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::advanced_circuit, 3, true}, {Ingredient::IngredientType::defender_capsule, 4, true}, }},
	{Recipe::RecipeType::electronic_circuit, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 1, true}, {Ingredient::IngredientType::copper_cable, 3, true}, }},
	{Recipe::RecipeType::filter_inserter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 4, true}, {Ingredient::IngredientType::fast_inserter, 1, true}, }},
	{Recipe::RecipeType::flamethrower, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::iron_gear_wheel, 10, true}, }},
	{Recipe::RecipeType::flamethrower_ammo, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::steel_plate, 5, true}, {Ingredient::IngredientType::crude_oil, 100, false}, }},
	{Recipe::RecipeType::lubricant, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::heavy_oil, 10, false}, }},
	{Recipe::RecipeType::power_armor_mk2, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 60, true}, {Ingredient::IngredientType::electric_engine_unit, 40, true}, {Ingredient::IngredientType::low_density_structure, 30, true}, {Ingredient::IngredientType::speed_module_2, 25, true}, {Ingredient::IngredientType::effectivity_module_2, 25, true}, }},
	{Recipe::RecipeType::production_science_pack, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::rail, 30, true}, {Ingredient::IngredientType::electric_furnace, 1, true}, {Ingredient::IngredientType::productivity_module, 1, true}, }},
	{Recipe::RecipeType::personal_roboport_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 20, true}, {Ingredient::IngredientType::battery, 45, true}, {Ingredient::IngredientType::iron_gear_wheel, 40, true}, {Ingredient::IngredientType::advanced_circuit, 10, true}, }},
	{Recipe::RecipeType::personal_roboport_mk2_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 100, true}, {Ingredient::IngredientType::low_density_structure, 20, true}, {Ingredient::IngredientType::personal_roboport_equipment, 5, true}, }},
	{Recipe::RecipeType::rocket_silo, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 1000, true}, {Ingredient::IngredientType::processing_unit, 200, true}, {Ingredient::IngredientType::electric_engine_unit, 200, true}, {Ingredient::IngredientType::pipe, 100, true}, {Ingredient::IngredientType::concrete, 1000, true}, }},
	{Recipe::RecipeType::advanced_circuit, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::plastic_bar, 2, true}, {Ingredient::IngredientType::copper_cable, 4, true}, {Ingredient::IngredientType::electronic_circuit, 2, true}, }},
	{Recipe::RecipeType::destroyer_capsule, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::speed_module, 1, true}, {Ingredient::IngredientType::distractor_capsule, 4, true}, }},
	{Recipe::RecipeType::land_mine, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 1, true}, {Ingredient::IngredientType::explosives, 2, true}, }},
	{Recipe::RecipeType::night_vision_equipment, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 10, true}, {Ingredient::IngredientType::advanced_circuit, 5, true}, }},
	{Recipe::RecipeType::nuclear_reactor, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 500, true}, {Ingredient::IngredientType::steel_plate, 500, true}, {Ingredient::IngredientType::advanced_circuit, 500, true}, {Ingredient::IngredientType::concrete, 500, true}, }},
	{Recipe::RecipeType::heat_pipe, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 20, true}, {Ingredient::IngredientType::steel_plate, 10, true}, }},
	{Recipe::RecipeType::heat_exchanger, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 100, true}, {Ingredient::IngredientType::steel_plate, 10, true}, {Ingredient::IngredientType::pipe, 10, true}, }},
	{Recipe::RecipeType::steam_turbine, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 50, true}, {Ingredient::IngredientType::iron_gear_wheel, 50, true}, {Ingredient::IngredientType::pipe, 20, true}, }},
	{Recipe::RecipeType::plastic_bar, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::coal, 1, true}, {Ingredient::IngredientType::petroleum_gas, 20, false}, }},
	{Recipe::RecipeType::stack_inserter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 15, true}, {Ingredient::IngredientType::electronic_circuit, 15, true}, {Ingredient::IngredientType::advanced_circuit, 1, true}, {Ingredient::IngredientType::fast_inserter, 1, true}, }},
	{Recipe::RecipeType::utility_science_pack, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 2, true}, {Ingredient::IngredientType::flying_robot_frame, 1, true}, {Ingredient::IngredientType::low_density_structure, 3, true}, }},
	{Recipe::RecipeType::centrifuge, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 50, true}, {Ingredient::IngredientType::iron_gear_wheel, 100, true}, {Ingredient::IngredientType::advanced_circuit, 100, true}, {Ingredient::IngredientType::concrete, 100, true}, }},
	{Recipe::RecipeType::lab, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_gear_wheel, 10, true}, {Ingredient::IngredientType::electronic_circuit, 10, true}, {Ingredient::IngredientType::transport_belt, 4, true}, }},
	{Recipe::RecipeType::processing_unit, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 20, true}, {Ingredient::IngredientType::advanced_circuit, 2, true}, {Ingredient::IngredientType::sulfuric_acid, 5, false}, }},
	{Recipe::RecipeType::stack_filter_inserter, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 5, true}, {Ingredient::IngredientType::stack_inserter, 1, true}, }},
	{Recipe::RecipeType::sulfur, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::water, 30, false}, {Ingredient::IngredientType::petroleum_gas, 30, false}, }},
	{Recipe::RecipeType::battery, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::iron_plate, 1, true}, {Ingredient::IngredientType::copper_plate, 1, true}, {Ingredient::IngredientType::sulfuric_acid, 20, false}, }},
	{Recipe::RecipeType::engine_unit, CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 1, true}, {Ingredient::IngredientType::iron_gear_wheel, 1, true}, {Ingredient::IngredientType::pipe, 2, true}, }},
	{Recipe::RecipeType::electric_engine_unit, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::electronic_circuit, 2, true}, {Ingredient::IngredientType::engine_unit, 1, true}, {Ingredient::IngredientType::lubricant, 15, false}, }},
	{Recipe::RecipeType::explosives, CraftingMachines::ChemicalPlant, {{Ingredient::IngredientType::coal, 1, true}, {Ingredient::IngredientType::sulfur, 1, true}, {Ingredient::IngredientType::water, 10, false}, }},
	{Recipe::RecipeType::uranium_processing, CraftingMachines::Centrifuge, {{Ingredient::IngredientType::uranium_ore, 10, true}, }},
	{Recipe::RecipeType::flying_robot_frame, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::steel_plate, 1, true}, {Ingredient::IngredientType::battery, 2, true}, {Ingredient::IngredientType::electronic_circuit, 3, true}, {Ingredient::IngredientType::electric_engine_unit, 1, true}, }},
	{Recipe::RecipeType::satellite, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 100, true}, {Ingredient::IngredientType::low_density_structure, 100, true}, {Ingredient::IngredientType::rocket_fuel, 50, true}, {Ingredient::IngredientType::solar_panel, 100, true}, {Ingredient::IngredientType::accumulator, 100, true}, {Ingredient::IngredientType::radar, 5, true}, }},
	{Recipe::RecipeType::rocket_control_unit, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::processing_unit, 1, true}, {Ingredient::IngredientType::speed_module, 1, true}, }},
	{Recipe::RecipeType::low_density_structure, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::copper_plate, 20, true}, {Ingredient::IngredientType::steel_plate, 2, true}, {Ingredient::IngredientType::plastic_bar, 5, true}, }},
	{Recipe::RecipeType::rocket_fuel, CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::solid_fuel, 10, true}, {Ingredient::IngredientType::light_oil, 10, false}, }},
	{Recipe::RecipeType::nuclear_fuel, CraftingMachines::Centrifuge, {{Ingredient::IngredientType::rocket_fuel, 1, true}, {Ingredient::IngredientType::uranium_235, 1, true}, }},
	{Recipe::RecipeType::uranium_fuel_cell, CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3, {{Ingredient::IngredientType::iron_plate, 10, true}, {Ingredient::IngredientType::uranium_235, 1, true}, {Ingredient::IngredientType::uranium_238, 19, true}, }},
	{Recipe::RecipeType::nuclear_fuel_reprocessing, CraftingMachines::Centrifuge, {{Ingredient::IngredientType::used_up_uranium_fuel_cell, 5, true}, }},
	{Recipe::RecipeType::kovarex_enrichment_process, CraftingMachines::Centrifuge, {{Ingredient::IngredientType::uranium_235, 40, true}, {Ingredient::IngredientType::uranium_238, 5, true}, }},
};
