#pragma once

#include <vector>
#include <map>
#include <string>

#include <wx/string.h>

#include "Shared functions/StringFunctions.h"

using std::vector;
using std::map;
using std::string;

/* LUA CODE

game.write_file(file,"")

	game.write_file(file, "\nenum ItemType{\n", true)
	for _, prototype in pairs(game.item_prototypes) do
		if not prototype.flags then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t%s,\n", name), true)
		end
	end
	for _, prototype in pairs(game.fluid_prototypes) do
		if not prototype.hidden then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t%s,\n", name), true)
		end
	end
	game.write_file(file, "};\n", true)

	game.write_file(file, "\nstatic inline const vector<string> ItemNames = {\n", true)
	for _, prototype in pairs(game.item_prototypes) do
		if not prototype.flags then
			game.write_file(file, "\t\"", true)
			game.write_file(file, prototype.localised_name, true)
			game.write_file(file, "\",\n", true)
		end
	end
	for _, prototype in pairs(game.fluid_prototypes) do
		if not prototype.hidden then
			game.write_file(file, "\t\"", true)
			game.write_file(file, prototype.localised_name, true)
			game.write_file(file, "\",\n", true)
		end
	end
	game.write_file(file, "};\n", true)

	game.write_file(file, "\nstatic inline map<string, ItemType> map_itemname_to_itemtype = {\n", true)
	for _, prototype in pairs(game.item_prototypes) do
		if not prototype.flags then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t{ItemNames[ItemType::%s], ItemType::%s},\n", name, name), true)
		end
	end
	for _, prototype in pairs(game.fluid_prototypes) do
		if not prototype.hidden then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t{ItemNames[ItemType::%s], ItemType::%s},\n", name, name), true)
		end
	end
	game.write_file(file, "\n", true)
	for _, prototype in pairs(game.item_prototypes) do
		if not prototype.flags then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t{to_lower(ItemNames[ItemType::%s]), ItemType::%s},\n", name, name), true)
		end
	end
	for _, prototype in pairs(game.fluid_prototypes) do
		if not prototype.hidden then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t{to_lower(ItemNames[ItemType::%s]), ItemType::%s},\n", name, name), true)
		end
	end
	game.write_file(file, "};\n", true)

	game.write_file(file, "\nenum RecipeType{\n", true)
	for _,prototype in pairs(game.recipe_prototypes) do
		if not prototype.hidden then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t%s,\n", name), true)
		end
	end
	game.write_file(file, "};\n", true)

	game.write_file(file, "\n\nstatic inline const vector<string> RecipeNames = {\n", true)
	for _,prototype in pairs(game.recipe_prototypes) do
		if not prototype.hidden then
			game.write_file(file, "\t\"", true)
			game.write_file(file, prototype.localised_name, true)
			game.write_file(file, "\",\n", true)
		end
	end
	game.write_file(file, "};\n", true)

	game.write_file(file, "\nstatic inline const map<string, RecipeType> map_recipename_to_recipetype = {\n", true)

	for _,prototype in pairs(game.recipe_prototypes) do
		if not prototype.hidden then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t{RecipeNames[RecipeType::%s], RecipeType::%s},\n", name, name), true)
		end
	end
	game.write_file(file, "\n", true)
	for _,prototype in pairs(game.recipe_prototypes) do
		if not prototype.hidden then
			local name = prototype.name:gsub("-", "_")
			game.write_file(file, string.format("\t{to_lower(RecipeNames[RecipeType::%s]), RecipeType::%s},\n", name, name), true)
		end
	end
	game.write_file(file, "};\n", true)

	local map_categories = {
		["crafting"] = "CraftingMachines::Character | CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3",
		["basic-crafting"] = "",
		["advanced-crafting"] = "CraftingMachines::AssemblingMachine1 | CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3",
		["crafting-with-fluid"] = "CraftingMachines::AssemblingMachine2 | CraftingMachines::AssemblingMachine3",
		["chemistry"] = "CraftingMachines::ChemicalPlant",
		["centrifuging"] = "CraftingMachines::Centrifuge",
		["oil-processing"] = "CraftingMachines::OilRefinery",
		["rocket-building"] = "CraftingMachines::RocketSilo",
		["smelting"] = "CraftingMachines::StoneFurnace | CraftingMachines::SteelFurnace | CraftingMachines::ElectricFurnace",
	}

	game.write_file(file, "\nstatic vector<Recipe> Recipes = {\n", true)
	for _,prototype in pairs(game.recipe_prototypes) do
		if not prototype.hidden then
			local name = prototype.name:gsub("-", "_")
			local ingredients = "{ "
			for __, ingredient in pairs(prototype.ingredients) do
				ingredients = ingredients..string.format("{ ItemType::%s, %d, %s}, ", ingredient.name:gsub("-", "_"), ingredient.amount, ingredient.type == "item" and "true" or "false")
			end
			ingredients = ingredients.."}"
			local made_in = map_categories[prototype.category]
			game.write_file(file, string.format("\t{RecipeType::%s, %s, %s},\n", name, made_in, ingredients), true)
		end
	end
	game.write_file(file, "};\n", true)

*/

namespace CRAFTING
{
	enum CraftingMachines
	{
		Character = 1 << 0,
		StoneFurnace = 1 << 1,
		SteelFurnace = 1 << 2,
		ElectricFurnace = 1 << 3,
		AssemblingMachine1 = 1 << 4,
		AssemblingMachine2 = 1 << 5,
		AssemblingMachine3 = 1 << 6,
		OilRefinery = 1 << 7,
		ChemicalPlant = 1 << 8,
		Centrifuge = 1 << 9,
		RocketSilo = 1 << 10,
	};
}

struct Ingredient
{
	// Ingredient types contain all item types and all fluid types
	enum IngredientType
	{
		none, // None is not a valid type

		wooden_chest,
		iron_chest,
		steel_chest,
		storage_tank,
		transport_belt,
		fast_transport_belt,
		express_transport_belt,
		underground_belt,
		fast_underground_belt,
		express_underground_belt,
		splitter,
		fast_splitter,
		express_splitter,
		burner_inserter,
		inserter,
		long_handed_inserter,
		fast_inserter,
		filter_inserter,
		stack_inserter,
		stack_filter_inserter,
		small_electric_pole,
		medium_electric_pole,
		big_electric_pole,
		substation,
		pipe,
		pipe_to_ground,
		pump,
		rail,
		train_stop,
		rail_signal,
		rail_chain_signal,
		locomotive,
		cargo_wagon,
		fluid_wagon,
		artillery_wagon,
		car,
		tank,
		spidertron,
		logistic_robot,
		construction_robot,
		logistic_chest_active_provider,
		logistic_chest_passive_provider,
		logistic_chest_storage,
		logistic_chest_buffer,
		logistic_chest_requester,
		roboport,
		small_lamp,
		red_wire,
		green_wire,
		arithmetic_combinator,
		decider_combinator,
		constant_combinator,
		power_switch,
		programmable_speaker,
		stone_brick,
		concrete,
		hazard_concrete,
		refined_concrete,
		refined_hazard_concrete,
		landfill,
		repair_pack,
		boiler,
		steam_engine,
		solar_panel,
		accumulator,
		nuclear_reactor,
		heat_pipe,
		heat_exchanger,
		steam_turbine,
		burner_mining_drill,
		electric_mining_drill,
		offshore_pump,
		pumpjack,
		stone_furnace,
		steel_furnace,
		electric_furnace,
		assembling_machine_1,
		assembling_machine_2,
		assembling_machine_3,
		oil_refinery,
		chemical_plant,
		centrifuge,
		lab,
		beacon,
		speed_module,
		speed_module_2,
		speed_module_3,
		effectivity_module,
		effectivity_module_2,
		effectivity_module_3,
		productivity_module,
		productivity_module_2,
		productivity_module_3,
		rocket_silo,
		satellite,
		wood,
		coal,
		stone,
		iron_ore,
		copper_ore,
		uranium_ore,
		raw_fish,
		iron_plate,
		copper_plate,
		solid_fuel,
		steel_plate,
		plastic_bar,
		sulfur,
		battery,
		explosives,
		crude_oil_barrel,
		heavy_oil_barrel,
		light_oil_barrel,
		lubricant_barrel,
		petroleum_gas_barrel,
		sulfuric_acid_barrel,
		water_barrel,
		copper_cable,
		iron_stick,
		iron_gear_wheel,
		empty_barrel,
		electronic_circuit,
		advanced_circuit,
		processing_unit,
		engine_unit,
		electric_engine_unit,
		flying_robot_frame,
		rocket_control_unit,
		low_density_structure,
		rocket_fuel,
		nuclear_fuel,
		uranium_235,
		uranium_238,
		uranium_fuel_cell,
		used_up_uranium_fuel_cell,
		automation_science_pack,
		logistic_science_pack,
		military_science_pack,
		chemical_science_pack,
		production_science_pack,
		utility_science_pack,
		space_science_pack,
		pistol,
		submachine_gun,
		shotgun,
		combat_shotgun,
		rocket_launcher,
		flamethrower,
		land_mine,
		firearm_magazine,
		piercing_rounds_magazine,
		uranium_rounds_magazine,
		shotgun_shell,
		piercing_shotgun_shell,
		cannon_shell,
		explosive_cannon_shell,
		uranium_cannon_shell,
		explosive_uranium_cannon_shell,
		artillery_shell,
		rocket,
		explosive_rocket,
		atomic_bomb,
		flamethrower_ammo,
		grenade,
		cluster_grenade,
		poison_capsule,
		slowdown_capsule,
		defender_capsule,
		distractor_capsule,
		destroyer_capsule,
		light_armor,
		heavy_armor,
		solar_panel_equipment,
		fusion_reactor_equipment,
		battery_equipment,
		battery_mk2_equipment,
		belt_immunity_equipment,
		exoskeleton_equipment,
		personal_roboport_equipment,
		personal_roboport_mk2_equipment,
		night_vision_equipment,
		energy_shield_equipment,
		energy_shield_mk2_equipment,
		personal_laser_defense_equipment,
		discharge_defense_equipment,
		discharge_defense_remote,
		stone_wall,
		gate,
		gun_turret,
		laser_turret,
		flamethrower_turret,
		artillery_turret,
		artillery_targeting_remote,
		radar,
		water,
		crude_oil,
		steam,
		heavy_oil,
		light_oil,
		petroleum_gas,
		sulfuric_acid,
		lubricant,
	} type;
	
	int count; // The number of items required for the craft, should always be above 0. In lua this is a double.
	bool is_item; // Some ingredients are fluids

	// Simple lookup for name that matches the ingredient type
	string Name();
	// Validates the ingredient
	bool IsValid();

	static inline const vector<string> IngredientNames = {
		"None",

		"Wooden chest",
		"Iron chest",
		"Steel chest",
		"Storage tank",
		"Transport belt",
		"Fast transport belt",
		"Express transport belt",
		"Underground belt",
		"Fast underground belt",
		"Express underground belt",
		"Splitter",
		"Fast splitter",
		"Express splitter",
		"Burner inserter",
		"Inserter",
		"Long-handed inserter",
		"Fast inserter",
		"Filter inserter",
		"Stack inserter",
		"Stack filter inserter",
		"Small electric pole",
		"Medium electric pole",
		"Big electric pole",
		"Substation",
		"Pipe",
		"Pipe to ground",
		"Pump",
		"Rail",
		"Train stop",
		"Rail signal",
		"Rail chain signal",
		"Locomotive",
		"Cargo wagon",
		"Fluid wagon",
		"Artillery wagon",
		"Car",
		"Tank",
		"Spidertron",
		"Logistic robot",
		"Construction robot",
		"Active provider chest",
		"Passive provider chest",
		"Storage chest",
		"Buffer chest",
		"Requester chest",
		"Roboport",
		"Lamp",
		"Red wire",
		"Green wire",
		"Arithmetic combinator",
		"Decider combinator",
		"Constant combinator",
		"Power switch",
		"Programmable speaker",
		"Stone brick",
		"Concrete",
		"Hazard concrete",
		"Refined concrete",
		"Refined hazard concrete",
		"Landfill",
		"Repair pack",
		"Boiler",
		"Steam engine",
		"Solar panel",
		"Accumulator",
		"Nuclear reactor",
		"Heat pipe",
		"Heat exchanger",
		"Steam turbine",
		"Burner mining drill",
		"Electric mining drill",
		"Offshore pump",
		"Pumpjack",
		"Stone furnace",
		"Steel furnace",
		"Electric furnace",
		"Assembling machine 1",
		"Assembling machine 2",
		"Assembling machine 3",
		"Oil refinery",
		"Chemical plant",
		"Centrifuge",
		"Lab",
		"Beacon",
		"Speed module",
		"Speed module 2",
		"Speed module 3",
		"Efficiency module",
		"Efficiency module 2",
		"Efficiency module 3",
		"Productivity module",
		"Productivity module 2",
		"Productivity module 3",
		"Rocket silo",
		"Satellite",
		"Wood",
		"Coal",
		"Stone",
		"Iron ore",
		"Copper ore",
		"Uranium ore",
		"Raw fish",
		"Iron plate",
		"Copper plate",
		"Solid fuel",
		"Steel plate",
		"Plastic bar",
		"Sulfur",
		"Battery",
		"Explosives",
		"Crude oil barrel",
		"Heavy oil barrel",
		"Light oil barrel",
		"Lubricant barrel",
		"Petroleum gas barrel",
		"Sulfuric acid barrel",
		"Water barrel",
		"Copper cable",
		"Iron stick",
		"Iron gear wheel",
		"Empty barrel",
		"Electronic circuit",
		"Advanced circuit",
		"Processing unit",
		"Engine unit",
		"Electric engine unit",
		"Flying robot frame",
		"Rocket control unit",
		"Low density structure",
		"Rocket fuel",
		"Nuclear fuel",
		"Uranium-235",
		"Uranium-238",
		"Uranium fuel cell",
		"Used-up uranium fuel cell",
		"Automation science pack",
		"Logistic science pack",
		"Military science pack",
		"Chemical science pack",
		"Production science pack",
		"Utility science pack",
		"Space science pack",
		"Pistol",
		"Submachine gun",
		"Shotgun",
		"Combat shotgun",
		"Rocket launcher",
		"Flamethrower",
		"Land mine",
		"Firearm magazine",
		"Piercing rounds magazine",
		"Uranium rounds magazine",
		"Shotgun shells",
		"Piercing shotgun shells",
		"Cannon shell",
		"Explosive cannon shell",
		"Uranium cannon shell",
		"Explosive uranium cannon shell",
		"Artillery shell",
		"Rocket",
		"Explosive rocket",
		"Atomic bomb",
		"Flamethrower ammo",
		"Grenade",
		"Cluster grenade",
		"Poison capsule",
		"Slowdown capsule",
		"Defender capsule",
		"Distractor capsule",
		"Destroyer capsule",
		"Light armor",
		"Heavy armor",
		"Portable solar panel",
		"Portable fusion reactor",
		"Personal battery",
		"Personal battery MK2",
		"Belt immunity equipment",
		"Exoskeleton",
		"Personal roboport",
		"Personal roboport MK2",
		"Nightvision",
		"Energy shield",
		"Energy shield MK2",
		"Personal laser defense",
		"Discharge defense",
		"Discharge defense remote",
		"Wall",
		"Gate",
		"Gun turret",
		"Laser turret",
		"Flamethrower turret",
		"Artillery turret",
		"Artillery targeting remote",
		"Radar",
		"Water",
		"Crude oil",
		"Steam",
		"Heavy oil",
		"Light oil",
		"Petroleum gas",
		"Sulfuric acid",
		"Lubricant",
	};

	static inline const map<string, IngredientType> map_ingredientname_to_ingredienttype = {
		{IngredientNames[IngredientType::wooden_chest], IngredientType::wooden_chest},
		{IngredientNames[IngredientType::iron_chest], IngredientType::iron_chest},
		{IngredientNames[IngredientType::steel_chest], IngredientType::steel_chest},
		{IngredientNames[IngredientType::storage_tank], IngredientType::storage_tank},
		{IngredientNames[IngredientType::transport_belt], IngredientType::transport_belt},
		{IngredientNames[IngredientType::fast_transport_belt], IngredientType::fast_transport_belt},
		{IngredientNames[IngredientType::express_transport_belt], IngredientType::express_transport_belt},
		{IngredientNames[IngredientType::underground_belt], IngredientType::underground_belt},
		{IngredientNames[IngredientType::fast_underground_belt], IngredientType::fast_underground_belt},
		{IngredientNames[IngredientType::express_underground_belt], IngredientType::express_underground_belt},
		{IngredientNames[IngredientType::splitter], IngredientType::splitter},
		{IngredientNames[IngredientType::fast_splitter], IngredientType::fast_splitter},
		{IngredientNames[IngredientType::express_splitter], IngredientType::express_splitter},
		{IngredientNames[IngredientType::burner_inserter], IngredientType::burner_inserter},
		{IngredientNames[IngredientType::inserter], IngredientType::inserter},
		{IngredientNames[IngredientType::long_handed_inserter], IngredientType::long_handed_inserter},
		{IngredientNames[IngredientType::fast_inserter], IngredientType::fast_inserter},
		{IngredientNames[IngredientType::filter_inserter], IngredientType::filter_inserter},
		{IngredientNames[IngredientType::stack_inserter], IngredientType::stack_inserter},
		{IngredientNames[IngredientType::stack_filter_inserter], IngredientType::stack_filter_inserter},
		{IngredientNames[IngredientType::small_electric_pole], IngredientType::small_electric_pole},
		{IngredientNames[IngredientType::medium_electric_pole], IngredientType::medium_electric_pole},
		{IngredientNames[IngredientType::big_electric_pole], IngredientType::big_electric_pole},
		{IngredientNames[IngredientType::substation], IngredientType::substation},
		{IngredientNames[IngredientType::pipe], IngredientType::pipe},
		{IngredientNames[IngredientType::pipe_to_ground], IngredientType::pipe_to_ground},
		{IngredientNames[IngredientType::pump], IngredientType::pump},
		{IngredientNames[IngredientType::rail], IngredientType::rail},
		{IngredientNames[IngredientType::train_stop], IngredientType::train_stop},
		{IngredientNames[IngredientType::rail_signal], IngredientType::rail_signal},
		{IngredientNames[IngredientType::rail_chain_signal], IngredientType::rail_chain_signal},
		{IngredientNames[IngredientType::locomotive], IngredientType::locomotive},
		{IngredientNames[IngredientType::cargo_wagon], IngredientType::cargo_wagon},
		{IngredientNames[IngredientType::fluid_wagon], IngredientType::fluid_wagon},
		{IngredientNames[IngredientType::artillery_wagon], IngredientType::artillery_wagon},
		{IngredientNames[IngredientType::car], IngredientType::car},
		{IngredientNames[IngredientType::tank], IngredientType::tank},
		{IngredientNames[IngredientType::spidertron], IngredientType::spidertron},
		{IngredientNames[IngredientType::logistic_robot], IngredientType::logistic_robot},
		{IngredientNames[IngredientType::construction_robot], IngredientType::construction_robot},
		{IngredientNames[IngredientType::logistic_chest_active_provider], IngredientType::logistic_chest_active_provider},
		{IngredientNames[IngredientType::logistic_chest_passive_provider], IngredientType::logistic_chest_passive_provider},
		{IngredientNames[IngredientType::logistic_chest_storage], IngredientType::logistic_chest_storage},
		{IngredientNames[IngredientType::logistic_chest_buffer], IngredientType::logistic_chest_buffer},
		{IngredientNames[IngredientType::logistic_chest_requester], IngredientType::logistic_chest_requester},
		{IngredientNames[IngredientType::roboport], IngredientType::roboport},
		{IngredientNames[IngredientType::small_lamp], IngredientType::small_lamp},
		{IngredientNames[IngredientType::red_wire], IngredientType::red_wire},
		{IngredientNames[IngredientType::green_wire], IngredientType::green_wire},
		{IngredientNames[IngredientType::arithmetic_combinator], IngredientType::arithmetic_combinator},
		{IngredientNames[IngredientType::decider_combinator], IngredientType::decider_combinator},
		{IngredientNames[IngredientType::constant_combinator], IngredientType::constant_combinator},
		{IngredientNames[IngredientType::power_switch], IngredientType::power_switch},
		{IngredientNames[IngredientType::programmable_speaker], IngredientType::programmable_speaker},
		{IngredientNames[IngredientType::stone_brick], IngredientType::stone_brick},
		{IngredientNames[IngredientType::concrete], IngredientType::concrete},
		{IngredientNames[IngredientType::hazard_concrete], IngredientType::hazard_concrete},
		{IngredientNames[IngredientType::refined_concrete], IngredientType::refined_concrete},
		{IngredientNames[IngredientType::refined_hazard_concrete], IngredientType::refined_hazard_concrete},
		{IngredientNames[IngredientType::landfill], IngredientType::landfill},
		{IngredientNames[IngredientType::repair_pack], IngredientType::repair_pack},
		{IngredientNames[IngredientType::boiler], IngredientType::boiler},
		{IngredientNames[IngredientType::steam_engine], IngredientType::steam_engine},
		{IngredientNames[IngredientType::solar_panel], IngredientType::solar_panel},
		{IngredientNames[IngredientType::accumulator], IngredientType::accumulator},
		{IngredientNames[IngredientType::nuclear_reactor], IngredientType::nuclear_reactor},
		{IngredientNames[IngredientType::heat_pipe], IngredientType::heat_pipe},
		{IngredientNames[IngredientType::heat_exchanger], IngredientType::heat_exchanger},
		{IngredientNames[IngredientType::steam_turbine], IngredientType::steam_turbine},
		{IngredientNames[IngredientType::burner_mining_drill], IngredientType::burner_mining_drill},
		{IngredientNames[IngredientType::electric_mining_drill], IngredientType::electric_mining_drill},
		{IngredientNames[IngredientType::offshore_pump], IngredientType::offshore_pump},
		{IngredientNames[IngredientType::pumpjack], IngredientType::pumpjack},
		{IngredientNames[IngredientType::stone_furnace], IngredientType::stone_furnace},
		{IngredientNames[IngredientType::steel_furnace], IngredientType::steel_furnace},
		{IngredientNames[IngredientType::electric_furnace], IngredientType::electric_furnace},
		{IngredientNames[IngredientType::assembling_machine_1], IngredientType::assembling_machine_1},
		{IngredientNames[IngredientType::assembling_machine_2], IngredientType::assembling_machine_2},
		{IngredientNames[IngredientType::assembling_machine_3], IngredientType::assembling_machine_3},
		{IngredientNames[IngredientType::oil_refinery], IngredientType::oil_refinery},
		{IngredientNames[IngredientType::chemical_plant], IngredientType::chemical_plant},
		{IngredientNames[IngredientType::centrifuge], IngredientType::centrifuge},
		{IngredientNames[IngredientType::lab], IngredientType::lab},
		{IngredientNames[IngredientType::beacon], IngredientType::beacon},
		{IngredientNames[IngredientType::speed_module], IngredientType::speed_module},
		{IngredientNames[IngredientType::speed_module_2], IngredientType::speed_module_2},
		{IngredientNames[IngredientType::speed_module_3], IngredientType::speed_module_3},
		{IngredientNames[IngredientType::effectivity_module], IngredientType::effectivity_module},
		{IngredientNames[IngredientType::effectivity_module_2], IngredientType::effectivity_module_2},
		{IngredientNames[IngredientType::effectivity_module_3], IngredientType::effectivity_module_3},
		{IngredientNames[IngredientType::productivity_module], IngredientType::productivity_module},
		{IngredientNames[IngredientType::productivity_module_2], IngredientType::productivity_module_2},
		{IngredientNames[IngredientType::productivity_module_3], IngredientType::productivity_module_3},
		{IngredientNames[IngredientType::rocket_silo], IngredientType::rocket_silo},
		{IngredientNames[IngredientType::satellite], IngredientType::satellite},
		{IngredientNames[IngredientType::wood], IngredientType::wood},
		{IngredientNames[IngredientType::coal], IngredientType::coal},
		{IngredientNames[IngredientType::stone], IngredientType::stone},
		{IngredientNames[IngredientType::iron_ore], IngredientType::iron_ore},
		{IngredientNames[IngredientType::copper_ore], IngredientType::copper_ore},
		{IngredientNames[IngredientType::uranium_ore], IngredientType::uranium_ore},
		{IngredientNames[IngredientType::raw_fish], IngredientType::raw_fish},
		{IngredientNames[IngredientType::iron_plate], IngredientType::iron_plate},
		{IngredientNames[IngredientType::copper_plate], IngredientType::copper_plate},
		{IngredientNames[IngredientType::solid_fuel], IngredientType::solid_fuel},
		{IngredientNames[IngredientType::steel_plate], IngredientType::steel_plate},
		{IngredientNames[IngredientType::plastic_bar], IngredientType::plastic_bar},
		{IngredientNames[IngredientType::sulfur], IngredientType::sulfur},
		{IngredientNames[IngredientType::battery], IngredientType::battery},
		{IngredientNames[IngredientType::explosives], IngredientType::explosives},
		{IngredientNames[IngredientType::crude_oil_barrel], IngredientType::crude_oil_barrel},
		{IngredientNames[IngredientType::heavy_oil_barrel], IngredientType::heavy_oil_barrel},
		{IngredientNames[IngredientType::light_oil_barrel], IngredientType::light_oil_barrel},
		{IngredientNames[IngredientType::lubricant_barrel], IngredientType::lubricant_barrel},
		{IngredientNames[IngredientType::petroleum_gas_barrel], IngredientType::petroleum_gas_barrel},
		{IngredientNames[IngredientType::sulfuric_acid_barrel], IngredientType::sulfuric_acid_barrel},
		{IngredientNames[IngredientType::water_barrel], IngredientType::water_barrel},
		{IngredientNames[IngredientType::copper_cable], IngredientType::copper_cable},
		{IngredientNames[IngredientType::iron_stick], IngredientType::iron_stick},
		{IngredientNames[IngredientType::iron_gear_wheel], IngredientType::iron_gear_wheel},
		{IngredientNames[IngredientType::empty_barrel], IngredientType::empty_barrel},
		{IngredientNames[IngredientType::electronic_circuit], IngredientType::electronic_circuit},
		{IngredientNames[IngredientType::advanced_circuit], IngredientType::advanced_circuit},
		{IngredientNames[IngredientType::processing_unit], IngredientType::processing_unit},
		{IngredientNames[IngredientType::engine_unit], IngredientType::engine_unit},
		{IngredientNames[IngredientType::electric_engine_unit], IngredientType::electric_engine_unit},
		{IngredientNames[IngredientType::flying_robot_frame], IngredientType::flying_robot_frame},
		{IngredientNames[IngredientType::rocket_control_unit], IngredientType::rocket_control_unit},
		{IngredientNames[IngredientType::low_density_structure], IngredientType::low_density_structure},
		{IngredientNames[IngredientType::rocket_fuel], IngredientType::rocket_fuel},
		{IngredientNames[IngredientType::nuclear_fuel], IngredientType::nuclear_fuel},
		{IngredientNames[IngredientType::uranium_235], IngredientType::uranium_235},
		{IngredientNames[IngredientType::uranium_238], IngredientType::uranium_238},
		{IngredientNames[IngredientType::uranium_fuel_cell], IngredientType::uranium_fuel_cell},
		{IngredientNames[IngredientType::used_up_uranium_fuel_cell], IngredientType::used_up_uranium_fuel_cell},
		{IngredientNames[IngredientType::automation_science_pack], IngredientType::automation_science_pack},
		{IngredientNames[IngredientType::logistic_science_pack], IngredientType::logistic_science_pack},
		{IngredientNames[IngredientType::military_science_pack], IngredientType::military_science_pack},
		{IngredientNames[IngredientType::chemical_science_pack], IngredientType::chemical_science_pack},
		{IngredientNames[IngredientType::production_science_pack], IngredientType::production_science_pack},
		{IngredientNames[IngredientType::utility_science_pack], IngredientType::utility_science_pack},
		{IngredientNames[IngredientType::space_science_pack], IngredientType::space_science_pack},
		{IngredientNames[IngredientType::pistol], IngredientType::pistol},
		{IngredientNames[IngredientType::submachine_gun], IngredientType::submachine_gun},
		{IngredientNames[IngredientType::shotgun], IngredientType::shotgun},
		{IngredientNames[IngredientType::combat_shotgun], IngredientType::combat_shotgun},
		{IngredientNames[IngredientType::rocket_launcher], IngredientType::rocket_launcher},
		{IngredientNames[IngredientType::flamethrower], IngredientType::flamethrower},
		{IngredientNames[IngredientType::land_mine], IngredientType::land_mine},
		{IngredientNames[IngredientType::firearm_magazine], IngredientType::firearm_magazine},
		{IngredientNames[IngredientType::piercing_rounds_magazine], IngredientType::piercing_rounds_magazine},
		{IngredientNames[IngredientType::uranium_rounds_magazine], IngredientType::uranium_rounds_magazine},
		{IngredientNames[IngredientType::shotgun_shell], IngredientType::shotgun_shell},
		{IngredientNames[IngredientType::piercing_shotgun_shell], IngredientType::piercing_shotgun_shell},
		{IngredientNames[IngredientType::cannon_shell], IngredientType::cannon_shell},
		{IngredientNames[IngredientType::explosive_cannon_shell], IngredientType::explosive_cannon_shell},
		{IngredientNames[IngredientType::uranium_cannon_shell], IngredientType::uranium_cannon_shell},
		{IngredientNames[IngredientType::explosive_uranium_cannon_shell], IngredientType::explosive_uranium_cannon_shell},
		{IngredientNames[IngredientType::artillery_shell], IngredientType::artillery_shell},
		{IngredientNames[IngredientType::rocket], IngredientType::rocket},
		{IngredientNames[IngredientType::explosive_rocket], IngredientType::explosive_rocket},
		{IngredientNames[IngredientType::atomic_bomb], IngredientType::atomic_bomb},
		{IngredientNames[IngredientType::flamethrower_ammo], IngredientType::flamethrower_ammo},
		{IngredientNames[IngredientType::grenade], IngredientType::grenade},
		{IngredientNames[IngredientType::cluster_grenade], IngredientType::cluster_grenade},
		{IngredientNames[IngredientType::poison_capsule], IngredientType::poison_capsule},
		{IngredientNames[IngredientType::slowdown_capsule], IngredientType::slowdown_capsule},
		{IngredientNames[IngredientType::defender_capsule], IngredientType::defender_capsule},
		{IngredientNames[IngredientType::distractor_capsule], IngredientType::distractor_capsule},
		{IngredientNames[IngredientType::destroyer_capsule], IngredientType::destroyer_capsule},
		{IngredientNames[IngredientType::light_armor], IngredientType::light_armor},
		{IngredientNames[IngredientType::heavy_armor], IngredientType::heavy_armor},
		{IngredientNames[IngredientType::solar_panel_equipment], IngredientType::solar_panel_equipment},
		{IngredientNames[IngredientType::fusion_reactor_equipment], IngredientType::fusion_reactor_equipment},
		{IngredientNames[IngredientType::battery_equipment], IngredientType::battery_equipment},
		{IngredientNames[IngredientType::battery_mk2_equipment], IngredientType::battery_mk2_equipment},
		{IngredientNames[IngredientType::belt_immunity_equipment], IngredientType::belt_immunity_equipment},
		{IngredientNames[IngredientType::exoskeleton_equipment], IngredientType::exoskeleton_equipment},
		{IngredientNames[IngredientType::personal_roboport_equipment], IngredientType::personal_roboport_equipment},
		{IngredientNames[IngredientType::personal_roboport_mk2_equipment], IngredientType::personal_roboport_mk2_equipment},
		{IngredientNames[IngredientType::night_vision_equipment], IngredientType::night_vision_equipment},
		{IngredientNames[IngredientType::energy_shield_equipment], IngredientType::energy_shield_equipment},
		{IngredientNames[IngredientType::energy_shield_mk2_equipment], IngredientType::energy_shield_mk2_equipment},
		{IngredientNames[IngredientType::personal_laser_defense_equipment], IngredientType::personal_laser_defense_equipment},
		{IngredientNames[IngredientType::discharge_defense_equipment], IngredientType::discharge_defense_equipment},
		{IngredientNames[IngredientType::discharge_defense_remote], IngredientType::discharge_defense_remote},
		{IngredientNames[IngredientType::stone_wall], IngredientType::stone_wall},
		{IngredientNames[IngredientType::gate], IngredientType::gate},
		{IngredientNames[IngredientType::gun_turret], IngredientType::gun_turret},
		{IngredientNames[IngredientType::laser_turret], IngredientType::laser_turret},
		{IngredientNames[IngredientType::flamethrower_turret], IngredientType::flamethrower_turret},
		{IngredientNames[IngredientType::artillery_turret], IngredientType::artillery_turret},
		{IngredientNames[IngredientType::artillery_targeting_remote], IngredientType::artillery_targeting_remote},
		{IngredientNames[IngredientType::radar], IngredientType::radar},
		{IngredientNames[IngredientType::water], IngredientType::water},
		{IngredientNames[IngredientType::crude_oil], IngredientType::crude_oil},
		{IngredientNames[IngredientType::steam], IngredientType::steam},
		{IngredientNames[IngredientType::heavy_oil], IngredientType::heavy_oil},
		{IngredientNames[IngredientType::light_oil], IngredientType::light_oil},
		{IngredientNames[IngredientType::petroleum_gas], IngredientType::petroleum_gas},
		{IngredientNames[IngredientType::sulfuric_acid], IngredientType::sulfuric_acid},
		{IngredientNames[IngredientType::lubricant], IngredientType::lubricant},

		{to_lower(IngredientNames[IngredientType::wooden_chest]), IngredientType::wooden_chest},
		{to_lower(IngredientNames[IngredientType::iron_chest]), IngredientType::iron_chest},
		{to_lower(IngredientNames[IngredientType::steel_chest]), IngredientType::steel_chest},
		{to_lower(IngredientNames[IngredientType::storage_tank]), IngredientType::storage_tank},
		{to_lower(IngredientNames[IngredientType::transport_belt]), IngredientType::transport_belt},
		{to_lower(IngredientNames[IngredientType::fast_transport_belt]), IngredientType::fast_transport_belt},
		{to_lower(IngredientNames[IngredientType::express_transport_belt]), IngredientType::express_transport_belt},
		{to_lower(IngredientNames[IngredientType::underground_belt]), IngredientType::underground_belt},
		{to_lower(IngredientNames[IngredientType::fast_underground_belt]), IngredientType::fast_underground_belt},
		{to_lower(IngredientNames[IngredientType::express_underground_belt]), IngredientType::express_underground_belt},
		{to_lower(IngredientNames[IngredientType::splitter]), IngredientType::splitter},
		{to_lower(IngredientNames[IngredientType::fast_splitter]), IngredientType::fast_splitter},
		{to_lower(IngredientNames[IngredientType::express_splitter]), IngredientType::express_splitter},
		{to_lower(IngredientNames[IngredientType::burner_inserter]), IngredientType::burner_inserter},
		{to_lower(IngredientNames[IngredientType::inserter]), IngredientType::inserter},
		{to_lower(IngredientNames[IngredientType::long_handed_inserter]), IngredientType::long_handed_inserter},
		{to_lower(IngredientNames[IngredientType::fast_inserter]), IngredientType::fast_inserter},
		{to_lower(IngredientNames[IngredientType::filter_inserter]), IngredientType::filter_inserter},
		{to_lower(IngredientNames[IngredientType::stack_inserter]), IngredientType::stack_inserter},
		{to_lower(IngredientNames[IngredientType::stack_filter_inserter]), IngredientType::stack_filter_inserter},
		{to_lower(IngredientNames[IngredientType::small_electric_pole]), IngredientType::small_electric_pole},
		{to_lower(IngredientNames[IngredientType::medium_electric_pole]), IngredientType::medium_electric_pole},
		{to_lower(IngredientNames[IngredientType::big_electric_pole]), IngredientType::big_electric_pole},
		{to_lower(IngredientNames[IngredientType::substation]), IngredientType::substation},
		{to_lower(IngredientNames[IngredientType::pipe]), IngredientType::pipe},
		{to_lower(IngredientNames[IngredientType::pipe_to_ground]), IngredientType::pipe_to_ground},
		{to_lower(IngredientNames[IngredientType::pump]), IngredientType::pump},
		{to_lower(IngredientNames[IngredientType::rail]), IngredientType::rail},
		{to_lower(IngredientNames[IngredientType::train_stop]), IngredientType::train_stop},
		{to_lower(IngredientNames[IngredientType::rail_signal]), IngredientType::rail_signal},
		{to_lower(IngredientNames[IngredientType::rail_chain_signal]), IngredientType::rail_chain_signal},
		{to_lower(IngredientNames[IngredientType::locomotive]), IngredientType::locomotive},
		{to_lower(IngredientNames[IngredientType::cargo_wagon]), IngredientType::cargo_wagon},
		{to_lower(IngredientNames[IngredientType::fluid_wagon]), IngredientType::fluid_wagon},
		{to_lower(IngredientNames[IngredientType::artillery_wagon]), IngredientType::artillery_wagon},
		{to_lower(IngredientNames[IngredientType::car]), IngredientType::car},
		{to_lower(IngredientNames[IngredientType::tank]), IngredientType::tank},
		{to_lower(IngredientNames[IngredientType::spidertron]), IngredientType::spidertron},
		{to_lower(IngredientNames[IngredientType::logistic_robot]), IngredientType::logistic_robot},
		{to_lower(IngredientNames[IngredientType::construction_robot]), IngredientType::construction_robot},
		{to_lower(IngredientNames[IngredientType::logistic_chest_active_provider]), IngredientType::logistic_chest_active_provider},
		{to_lower(IngredientNames[IngredientType::logistic_chest_passive_provider]), IngredientType::logistic_chest_passive_provider},
		{to_lower(IngredientNames[IngredientType::logistic_chest_storage]), IngredientType::logistic_chest_storage},
		{to_lower(IngredientNames[IngredientType::logistic_chest_buffer]), IngredientType::logistic_chest_buffer},
		{to_lower(IngredientNames[IngredientType::logistic_chest_requester]), IngredientType::logistic_chest_requester},
		{to_lower(IngredientNames[IngredientType::roboport]), IngredientType::roboport},
		{to_lower(IngredientNames[IngredientType::small_lamp]), IngredientType::small_lamp},
		{to_lower(IngredientNames[IngredientType::red_wire]), IngredientType::red_wire},
		{to_lower(IngredientNames[IngredientType::green_wire]), IngredientType::green_wire},
		{to_lower(IngredientNames[IngredientType::arithmetic_combinator]), IngredientType::arithmetic_combinator},
		{to_lower(IngredientNames[IngredientType::decider_combinator]), IngredientType::decider_combinator},
		{to_lower(IngredientNames[IngredientType::constant_combinator]), IngredientType::constant_combinator},
		{to_lower(IngredientNames[IngredientType::power_switch]), IngredientType::power_switch},
		{to_lower(IngredientNames[IngredientType::programmable_speaker]), IngredientType::programmable_speaker},
		{to_lower(IngredientNames[IngredientType::stone_brick]), IngredientType::stone_brick},
		{to_lower(IngredientNames[IngredientType::concrete]), IngredientType::concrete},
		{to_lower(IngredientNames[IngredientType::hazard_concrete]), IngredientType::hazard_concrete},
		{to_lower(IngredientNames[IngredientType::refined_concrete]), IngredientType::refined_concrete},
		{to_lower(IngredientNames[IngredientType::refined_hazard_concrete]), IngredientType::refined_hazard_concrete},
		{to_lower(IngredientNames[IngredientType::landfill]), IngredientType::landfill},
		{to_lower(IngredientNames[IngredientType::repair_pack]), IngredientType::repair_pack},
		{to_lower(IngredientNames[IngredientType::boiler]), IngredientType::boiler},
		{to_lower(IngredientNames[IngredientType::steam_engine]), IngredientType::steam_engine},
		{to_lower(IngredientNames[IngredientType::solar_panel]), IngredientType::solar_panel},
		{to_lower(IngredientNames[IngredientType::accumulator]), IngredientType::accumulator},
		{to_lower(IngredientNames[IngredientType::nuclear_reactor]), IngredientType::nuclear_reactor},
		{to_lower(IngredientNames[IngredientType::heat_pipe]), IngredientType::heat_pipe},
		{to_lower(IngredientNames[IngredientType::heat_exchanger]), IngredientType::heat_exchanger},
		{to_lower(IngredientNames[IngredientType::steam_turbine]), IngredientType::steam_turbine},
		{to_lower(IngredientNames[IngredientType::burner_mining_drill]), IngredientType::burner_mining_drill},
		{to_lower(IngredientNames[IngredientType::electric_mining_drill]), IngredientType::electric_mining_drill},
		{to_lower(IngredientNames[IngredientType::offshore_pump]), IngredientType::offshore_pump},
		{to_lower(IngredientNames[IngredientType::pumpjack]), IngredientType::pumpjack},
		{to_lower(IngredientNames[IngredientType::stone_furnace]), IngredientType::stone_furnace},
		{to_lower(IngredientNames[IngredientType::steel_furnace]), IngredientType::steel_furnace},
		{to_lower(IngredientNames[IngredientType::electric_furnace]), IngredientType::electric_furnace},
		{to_lower(IngredientNames[IngredientType::assembling_machine_1]), IngredientType::assembling_machine_1},
		{to_lower(IngredientNames[IngredientType::assembling_machine_2]), IngredientType::assembling_machine_2},
		{to_lower(IngredientNames[IngredientType::assembling_machine_3]), IngredientType::assembling_machine_3},
		{to_lower(IngredientNames[IngredientType::oil_refinery]), IngredientType::oil_refinery},
		{to_lower(IngredientNames[IngredientType::chemical_plant]), IngredientType::chemical_plant},
		{to_lower(IngredientNames[IngredientType::centrifuge]), IngredientType::centrifuge},
		{to_lower(IngredientNames[IngredientType::lab]), IngredientType::lab},
		{to_lower(IngredientNames[IngredientType::beacon]), IngredientType::beacon},
		{to_lower(IngredientNames[IngredientType::speed_module]), IngredientType::speed_module},
		{to_lower(IngredientNames[IngredientType::speed_module_2]), IngredientType::speed_module_2},
		{to_lower(IngredientNames[IngredientType::speed_module_3]), IngredientType::speed_module_3},
		{to_lower(IngredientNames[IngredientType::effectivity_module]), IngredientType::effectivity_module},
		{to_lower(IngredientNames[IngredientType::effectivity_module_2]), IngredientType::effectivity_module_2},
		{to_lower(IngredientNames[IngredientType::effectivity_module_3]), IngredientType::effectivity_module_3},
		{to_lower(IngredientNames[IngredientType::productivity_module]), IngredientType::productivity_module},
		{to_lower(IngredientNames[IngredientType::productivity_module_2]), IngredientType::productivity_module_2},
		{to_lower(IngredientNames[IngredientType::productivity_module_3]), IngredientType::productivity_module_3},
		{to_lower(IngredientNames[IngredientType::rocket_silo]), IngredientType::rocket_silo},
		{to_lower(IngredientNames[IngredientType::satellite]), IngredientType::satellite},
		{to_lower(IngredientNames[IngredientType::wood]), IngredientType::wood},
		{to_lower(IngredientNames[IngredientType::coal]), IngredientType::coal},
		{to_lower(IngredientNames[IngredientType::stone]), IngredientType::stone},
		{to_lower(IngredientNames[IngredientType::iron_ore]), IngredientType::iron_ore},
		{to_lower(IngredientNames[IngredientType::copper_ore]), IngredientType::copper_ore},
		{to_lower(IngredientNames[IngredientType::uranium_ore]), IngredientType::uranium_ore},
		{to_lower(IngredientNames[IngredientType::raw_fish]), IngredientType::raw_fish},
		{to_lower(IngredientNames[IngredientType::iron_plate]), IngredientType::iron_plate},
		{to_lower(IngredientNames[IngredientType::copper_plate]), IngredientType::copper_plate},
		{to_lower(IngredientNames[IngredientType::solid_fuel]), IngredientType::solid_fuel},
		{to_lower(IngredientNames[IngredientType::steel_plate]), IngredientType::steel_plate},
		{to_lower(IngredientNames[IngredientType::plastic_bar]), IngredientType::plastic_bar},
		{to_lower(IngredientNames[IngredientType::sulfur]), IngredientType::sulfur},
		{to_lower(IngredientNames[IngredientType::battery]), IngredientType::battery},
		{to_lower(IngredientNames[IngredientType::explosives]), IngredientType::explosives},
		{to_lower(IngredientNames[IngredientType::crude_oil_barrel]), IngredientType::crude_oil_barrel},
		{to_lower(IngredientNames[IngredientType::heavy_oil_barrel]), IngredientType::heavy_oil_barrel},
		{to_lower(IngredientNames[IngredientType::light_oil_barrel]), IngredientType::light_oil_barrel},
		{to_lower(IngredientNames[IngredientType::lubricant_barrel]), IngredientType::lubricant_barrel},
		{to_lower(IngredientNames[IngredientType::petroleum_gas_barrel]), IngredientType::petroleum_gas_barrel},
		{to_lower(IngredientNames[IngredientType::sulfuric_acid_barrel]), IngredientType::sulfuric_acid_barrel},
		{to_lower(IngredientNames[IngredientType::water_barrel]), IngredientType::water_barrel},
		{to_lower(IngredientNames[IngredientType::copper_cable]), IngredientType::copper_cable},
		{to_lower(IngredientNames[IngredientType::iron_stick]), IngredientType::iron_stick},
		{to_lower(IngredientNames[IngredientType::iron_gear_wheel]), IngredientType::iron_gear_wheel},
		{to_lower(IngredientNames[IngredientType::empty_barrel]), IngredientType::empty_barrel},
		{to_lower(IngredientNames[IngredientType::electronic_circuit]), IngredientType::electronic_circuit},
		{to_lower(IngredientNames[IngredientType::advanced_circuit]), IngredientType::advanced_circuit},
		{to_lower(IngredientNames[IngredientType::processing_unit]), IngredientType::processing_unit},
		{to_lower(IngredientNames[IngredientType::engine_unit]), IngredientType::engine_unit},
		{to_lower(IngredientNames[IngredientType::electric_engine_unit]), IngredientType::electric_engine_unit},
		{to_lower(IngredientNames[IngredientType::flying_robot_frame]), IngredientType::flying_robot_frame},
		{to_lower(IngredientNames[IngredientType::rocket_control_unit]), IngredientType::rocket_control_unit},
		{to_lower(IngredientNames[IngredientType::low_density_structure]), IngredientType::low_density_structure},
		{to_lower(IngredientNames[IngredientType::rocket_fuel]), IngredientType::rocket_fuel},
		{to_lower(IngredientNames[IngredientType::nuclear_fuel]), IngredientType::nuclear_fuel},
		{to_lower(IngredientNames[IngredientType::uranium_235]), IngredientType::uranium_235},
		{to_lower(IngredientNames[IngredientType::uranium_238]), IngredientType::uranium_238},
		{to_lower(IngredientNames[IngredientType::uranium_fuel_cell]), IngredientType::uranium_fuel_cell},
		{to_lower(IngredientNames[IngredientType::used_up_uranium_fuel_cell]), IngredientType::used_up_uranium_fuel_cell},
		{to_lower(IngredientNames[IngredientType::automation_science_pack]), IngredientType::automation_science_pack},
		{to_lower(IngredientNames[IngredientType::logistic_science_pack]), IngredientType::logistic_science_pack},
		{to_lower(IngredientNames[IngredientType::military_science_pack]), IngredientType::military_science_pack},
		{to_lower(IngredientNames[IngredientType::chemical_science_pack]), IngredientType::chemical_science_pack},
		{to_lower(IngredientNames[IngredientType::production_science_pack]), IngredientType::production_science_pack},
		{to_lower(IngredientNames[IngredientType::utility_science_pack]), IngredientType::utility_science_pack},
		{to_lower(IngredientNames[IngredientType::space_science_pack]), IngredientType::space_science_pack},
		{to_lower(IngredientNames[IngredientType::pistol]), IngredientType::pistol},
		{to_lower(IngredientNames[IngredientType::submachine_gun]), IngredientType::submachine_gun},
		{to_lower(IngredientNames[IngredientType::shotgun]), IngredientType::shotgun},
		{to_lower(IngredientNames[IngredientType::combat_shotgun]), IngredientType::combat_shotgun},
		{to_lower(IngredientNames[IngredientType::rocket_launcher]), IngredientType::rocket_launcher},
		{to_lower(IngredientNames[IngredientType::flamethrower]), IngredientType::flamethrower},
		{to_lower(IngredientNames[IngredientType::land_mine]), IngredientType::land_mine},
		{to_lower(IngredientNames[IngredientType::firearm_magazine]), IngredientType::firearm_magazine},
		{to_lower(IngredientNames[IngredientType::piercing_rounds_magazine]), IngredientType::piercing_rounds_magazine},
		{to_lower(IngredientNames[IngredientType::uranium_rounds_magazine]), IngredientType::uranium_rounds_magazine},
		{to_lower(IngredientNames[IngredientType::shotgun_shell]), IngredientType::shotgun_shell},
		{to_lower(IngredientNames[IngredientType::piercing_shotgun_shell]), IngredientType::piercing_shotgun_shell},
		{to_lower(IngredientNames[IngredientType::cannon_shell]), IngredientType::cannon_shell},
		{to_lower(IngredientNames[IngredientType::explosive_cannon_shell]), IngredientType::explosive_cannon_shell},
		{to_lower(IngredientNames[IngredientType::uranium_cannon_shell]), IngredientType::uranium_cannon_shell},
		{to_lower(IngredientNames[IngredientType::explosive_uranium_cannon_shell]), IngredientType::explosive_uranium_cannon_shell},
		{to_lower(IngredientNames[IngredientType::artillery_shell]), IngredientType::artillery_shell},
		{to_lower(IngredientNames[IngredientType::rocket]), IngredientType::rocket},
		{to_lower(IngredientNames[IngredientType::explosive_rocket]), IngredientType::explosive_rocket},
		{to_lower(IngredientNames[IngredientType::atomic_bomb]), IngredientType::atomic_bomb},
		{to_lower(IngredientNames[IngredientType::flamethrower_ammo]), IngredientType::flamethrower_ammo},
		{to_lower(IngredientNames[IngredientType::grenade]), IngredientType::grenade},
		{to_lower(IngredientNames[IngredientType::cluster_grenade]), IngredientType::cluster_grenade},
		{to_lower(IngredientNames[IngredientType::poison_capsule]), IngredientType::poison_capsule},
		{to_lower(IngredientNames[IngredientType::slowdown_capsule]), IngredientType::slowdown_capsule},
		{to_lower(IngredientNames[IngredientType::defender_capsule]), IngredientType::defender_capsule},
		{to_lower(IngredientNames[IngredientType::distractor_capsule]), IngredientType::distractor_capsule},
		{to_lower(IngredientNames[IngredientType::destroyer_capsule]), IngredientType::destroyer_capsule},
		{to_lower(IngredientNames[IngredientType::light_armor]), IngredientType::light_armor},
		{to_lower(IngredientNames[IngredientType::heavy_armor]), IngredientType::heavy_armor},
		{to_lower(IngredientNames[IngredientType::solar_panel_equipment]), IngredientType::solar_panel_equipment},
		{to_lower(IngredientNames[IngredientType::fusion_reactor_equipment]), IngredientType::fusion_reactor_equipment},
		{to_lower(IngredientNames[IngredientType::battery_equipment]), IngredientType::battery_equipment},
		{to_lower(IngredientNames[IngredientType::battery_mk2_equipment]), IngredientType::battery_mk2_equipment},
		{to_lower(IngredientNames[IngredientType::belt_immunity_equipment]), IngredientType::belt_immunity_equipment},
		{to_lower(IngredientNames[IngredientType::exoskeleton_equipment]), IngredientType::exoskeleton_equipment},
		{to_lower(IngredientNames[IngredientType::personal_roboport_equipment]), IngredientType::personal_roboport_equipment},
		{to_lower(IngredientNames[IngredientType::personal_roboport_mk2_equipment]), IngredientType::personal_roboport_mk2_equipment},
		{to_lower(IngredientNames[IngredientType::night_vision_equipment]), IngredientType::night_vision_equipment},
		{to_lower(IngredientNames[IngredientType::energy_shield_equipment]), IngredientType::energy_shield_equipment},
		{to_lower(IngredientNames[IngredientType::energy_shield_mk2_equipment]), IngredientType::energy_shield_mk2_equipment},
		{to_lower(IngredientNames[IngredientType::personal_laser_defense_equipment]), IngredientType::personal_laser_defense_equipment},
		{to_lower(IngredientNames[IngredientType::discharge_defense_equipment]), IngredientType::discharge_defense_equipment},
		{to_lower(IngredientNames[IngredientType::discharge_defense_remote]), IngredientType::discharge_defense_remote},
		{to_lower(IngredientNames[IngredientType::stone_wall]), IngredientType::stone_wall},
		{to_lower(IngredientNames[IngredientType::gate]), IngredientType::gate},
		{to_lower(IngredientNames[IngredientType::gun_turret]), IngredientType::gun_turret},
		{to_lower(IngredientNames[IngredientType::laser_turret]), IngredientType::laser_turret},
		{to_lower(IngredientNames[IngredientType::flamethrower_turret]), IngredientType::flamethrower_turret},
		{to_lower(IngredientNames[IngredientType::artillery_turret]), IngredientType::artillery_turret},
		{to_lower(IngredientNames[IngredientType::artillery_targeting_remote]), IngredientType::artillery_targeting_remote},
		{to_lower(IngredientNames[IngredientType::radar]), IngredientType::radar},
		{to_lower(IngredientNames[IngredientType::water]), IngredientType::water},
		{to_lower(IngredientNames[IngredientType::crude_oil]), IngredientType::crude_oil},
		{to_lower(IngredientNames[IngredientType::steam]), IngredientType::steam},
		{to_lower(IngredientNames[IngredientType::heavy_oil]), IngredientType::heavy_oil},
		{to_lower(IngredientNames[IngredientType::light_oil]), IngredientType::light_oil},
		{to_lower(IngredientNames[IngredientType::petroleum_gas]), IngredientType::petroleum_gas},
		{to_lower(IngredientNames[IngredientType::sulfuric_acid]), IngredientType::sulfuric_acid},
		{to_lower(IngredientNames[IngredientType::lubricant]), IngredientType::lubricant},
	};

	static IngredientType MapStringToIngredientType(const string str);
	static IngredientType MapStringToIngredientType(const wxString str);
};

struct Recipe
{
	enum RecipeType
	{
		none,
		assembling_machine_1,
		automation_science_pack,
		firearm_magazine,
		pistol,
		piercing_rounds_magazine,
		submachine_gun,
		uranium_rounds_magazine,
		beacon,
		burner_inserter,
		copper_cable,
		electric_energy_interface,
		solar_panel_equipment,
		fusion_reactor_equipment,
		small_electric_pole,
		medium_electric_pole,
		big_electric_pole,
		substation,
		sulfuric_acid,
		grenade,
		cluster_grenade,
		burner_mining_drill,
		wooden_chest,
		electric_mining_drill,
		iron_chest,
		steel_chest,
		light_armor,
		small_lamp,
		basic_oil_processing,
		advanced_oil_processing,
		coal_liquefaction,
		pipe,
		pipe_to_ground,
		logistic_robot,
		construction_robot,
		energy_shield_equipment,
		energy_shield_mk2_equipment,
		speed_module,
		speed_module_2,
		speed_module_3,
		stone_brick,
		stone_furnace,
		stone_wall,
		rail,
		train_stop,
		rail_signal,
		rail_chain_signal,
		locomotive,
		cargo_wagon,
		fluid_wagon,
		artillery_wagon,
		transport_belt,
		fast_transport_belt,
		express_transport_belt,
		gate,
		personal_laser_defense_equipment,
		discharge_defense_equipment,
		discharge_defense_remote,
		assembling_machine_2,
		battery_equipment,
		battery_mk2_equipment,
		concrete,
		hazard_concrete,
		refined_concrete,
		refined_hazard_concrete,
		fill_crude_oil_barrel,
		fill_heavy_oil_barrel,
		fill_light_oil_barrel,
		fill_lubricant_barrel,
		fill_petroleum_gas_barrel,
		fill_sulfuric_acid_barrel,
		fill_water_barrel,
		heavy_oil_cracking,
		light_oil_cracking,
		solid_fuel_from_light_oil,
		solid_fuel_from_petroleum_gas,
		solid_fuel_from_heavy_oil,
		storage_tank,
		offshore_pump,
		pumpjack,
		heavy_armor,
		inserter,
		iron_plate,
		iron_stick,
		logistic_science_pack,
		car,
		tank,
		spidertron,
		spidertron_remote,
		pump,
		poison_capsule,
		repair_pack,
		shotgun,
		shotgun_shell,
		combat_shotgun,
		piercing_shotgun_shell,
		boiler,
		steam_engine,
		steel_furnace,
		logistic_chest_active_provider,
		logistic_chest_passive_provider,
		logistic_chest_storage,
		logistic_chest_buffer,
		logistic_chest_requester,
		gun_turret,
		laser_turret,
		flamethrower_turret,
		artillery_turret,
		artillery_targeting_remote,
		underground_belt,
		fast_underground_belt,
		express_underground_belt,
		red_wire,
		green_wire,
		assembling_machine_3,
		belt_immunity_equipment,
		arithmetic_combinator,
		decider_combinator,
		constant_combinator,
		copper_plate,
		effectivity_module,
		effectivity_module_2,
		effectivity_module_3,
		electric_furnace,
		empty_crude_oil_barrel,
		empty_heavy_oil_barrel,
		empty_light_oil_barrel,
		empty_lubricant_barrel,
		empty_petroleum_gas_barrel,
		empty_sulfuric_acid_barrel,
		empty_water_barrel,
		iron_gear_wheel,
		landfill,
		long_handed_inserter,
		military_science_pack,
		modular_armor,
		productivity_module,
		productivity_module_2,
		productivity_module_3,
		roboport,
		slowdown_capsule,
		splitter,
		fast_splitter,
		express_splitter,
		cannon_shell,
		explosive_cannon_shell,
		uranium_cannon_shell,
		chemical_science_pack,
		cliff_explosives,
		defender_capsule,
		empty_barrel,
		exoskeleton_equipment,
		explosive_uranium_cannon_shell,
		artillery_shell,
		fast_inserter,
		power_switch,
		programmable_speaker,
		power_armor,
		radar,
		oil_refinery,
		rocket_launcher,
		rocket,
		explosive_rocket,
		atomic_bomb,
		solar_panel,
		steel_plate,
		accumulator,
		chemical_plant,
		distractor_capsule,
		electronic_circuit,
		filter_inserter,
		flamethrower,
		flamethrower_ammo,
		lubricant,
		power_armor_mk2,
		production_science_pack,
		personal_roboport_equipment,
		personal_roboport_mk2_equipment,
		rocket_silo,
		advanced_circuit,
		destroyer_capsule,
		land_mine,
		night_vision_equipment,
		nuclear_reactor,
		heat_pipe,
		heat_exchanger,
		steam_turbine,
		plastic_bar,
		stack_inserter,
		utility_science_pack,
		centrifuge,
		lab,
		processing_unit,
		stack_filter_inserter,
		sulfur,
		battery,
		engine_unit,
		electric_engine_unit,
		explosives,
		uranium_processing,
		flying_robot_frame,
		satellite,
		rocket_control_unit,
		low_density_structure,
		rocket_fuel,
		nuclear_fuel,
		uranium_fuel_cell,
		nuclear_fuel_reprocessing,
		kovarex_enrichment_process,
	} type;

	int made_in;
	vector<Ingredient> ingredients;

	// Simple lookup for name that matches the recipe type
	string Name();
	// Returns true if this recipe can be made in that machine. 
	// Some recipes can be made in several crafting machines.
	bool IsMadeBy(CRAFTING::CraftingMachines machine);
	// Gets a new ingredient vector with only ingredients that are item
	vector<Ingredient> GetItemIngredients();
	
	static inline const vector<string> RecipeNames = {
		"None",
		"Assembling machine 1",
		"Automation science pack",
		"Firearm magazine",
		"Pistol",
		"Piercing rounds magazine",
		"Submachine gun",
		"Uranium rounds magazine",
		"Beacon",
		"Burner inserter",
		"Copper cable",
		"Electric energy interface",
		"Portable solar panel",
		"Portable fusion reactor",
		"Small electric pole",
		"Medium electric pole",
		"Big electric pole",
		"Substation",
		"Sulfuric acid",
		"Grenade",
		"Cluster grenade",
		"Burner mining drill",
		"Wooden chest",
		"Electric mining drill",
		"Iron chest",
		"Steel chest",
		"Light armor",
		"Lamp",
		"Basic oil processing",
		"Advanced oil processing",
		"Coal liquefaction",
		"Pipe",
		"Pipe to ground",
		"Logistic robot",
		"Construction robot",
		"Energy shield",
		"Energy shield MK2",
		"Speed module",
		"Speed module 2",
		"Speed module 3",
		"Stone brick",
		"Stone furnace",
		"Wall",
		"Rail",
		"Train stop",
		"Rail signal",
		"Rail chain signal",
		"Locomotive",
		"Cargo wagon",
		"Fluid wagon",
		"Artillery wagon",
		"Transport belt",
		"Fast transport belt",
		"Express transport belt",
		"Gate",
		"Personal laser defense",
		"Discharge defense",
		"Discharge defense remote",
		"Assembling machine 2",
		"Personal battery",
		"Personal battery MK2",
		"Concrete",
		"Hazard concrete",
		"Refined concrete",
		"Refined hazard concrete",
		"Fill Crude oil barrel",
		"Fill Heavy oil barrel",
		"Fill Light oil barrel",
		"Fill Lubricant barrel",
		"Fill Petroleum gas barrel",
		"Fill Sulfuric acid barrel",
		"Fill Water barrel",
		"Heavy oil cracking to light oil",
		"Light oil cracking to petroleum gas",
		"Solid fuel",
		"Solid fuel",
		"Solid fuel",
		"Storage tank",
		"Offshore pump",
		"Pumpjack",
		"Heavy armor",
		"Inserter",
		"Iron plate",
		"Iron stick",
		"Logistic science pack",
		"Car",
		"Tank",
		"Spidertron",
		"Spidertron remote",
		"Pump",
		"Poison capsule",
		"Repair pack",
		"Shotgun",
		"Shotgun shells",
		"Combat shotgun",
		"Piercing shotgun shells",
		"Boiler",
		"Steam engine",
		"Steel furnace",
		"Active provider chest",
		"Passive provider chest",
		"Storage chest",
		"Buffer chest",
		"Requester chest",
		"Gun turret",
		"Laser turret",
		"Flamethrower turret",
		"Artillery turret",
		"Artillery targeting remote",
		"Underground belt",
		"Fast underground belt",
		"Express underground belt",
		"Red wire",
		"Green wire",
		"Assembling machine 3",
		"Belt immunity equipment",
		"Arithmetic combinator",
		"Decider combinator",
		"Constant combinator",
		"Copper plate",
		"Efficiency module",
		"Efficiency module 2",
		"Efficiency module 3",
		"Electric furnace",
		"Empty Crude oil barrel",
		"Empty Heavy oil barrel",
		"Empty Light oil barrel",
		"Empty Lubricant barrel",
		"Empty Petroleum gas barrel",
		"Empty Sulfuric acid barrel",
		"Empty Water barrel",
		"Iron gear wheel",
		"Landfill",
		"Long-handed inserter",
		"Military science pack",
		"Modular armor",
		"Productivity module",
		"Productivity module 2",
		"Productivity module 3",
		"Roboport",
		"Slowdown capsule",
		"Splitter",
		"Fast splitter",
		"Express splitter",
		"Cannon shell",
		"Explosive cannon shell",
		"Uranium cannon shell",
		"Chemical science pack",
		"Cliff explosives",
		"Defender capsule",
		"Empty barrel",
		"Exoskeleton",
		"Explosive uranium cannon shell",
		"Artillery shell",
		"Fast inserter",
		"Power switch",
		"Programmable speaker",
		"Power armor",
		"Radar",
		"Oil refinery",
		"Rocket launcher",
		"Rocket",
		"Explosive rocket",
		"Atomic bomb",
		"Solar panel",
		"Steel plate",
		"Accumulator",
		"Chemical plant",
		"Distractor capsule",
		"Electronic circuit",
		"Filter inserter",
		"Flamethrower",
		"Flamethrower ammo",
		"Lubricant",
		"Power armor MK2",
		"Production science pack",
		"Personal roboport",
		"Personal roboport MK2",
		"Rocket silo",
		"Advanced circuit",
		"Destroyer capsule",
		"Land mine",
		"Nightvision",
		"Nuclear reactor",
		"Heat pipe",
		"Heat exchanger",
		"Steam turbine",
		"Plastic bar",
		"Stack inserter",
		"Utility science pack",
		"Centrifuge",
		"Lab",
		"Processing unit",
		"Stack filter inserter",
		"Sulfur",
		"Battery",
		"Engine unit",
		"Electric engine unit",
		"Explosives",
		"Uranium processing",
		"Flying robot frame",
		"Satellite",
		"Rocket control unit",
		"Low density structure",
		"Rocket fuel",
		"Nuclear fuel",
		"Uranium fuel cell",
		"Nuclear fuel reprocessing",
		"Kovarex enrichment process",
	};

	static inline const map<string, RecipeType> map_recipename_to_recipetype = {
		{RecipeNames[RecipeType::none], RecipeType::none},
		{to_lower(RecipeNames[RecipeType::none]), RecipeType::none},

		{RecipeNames[RecipeType::assembling_machine_1], RecipeType::assembling_machine_1},
		{RecipeNames[RecipeType::automation_science_pack], RecipeType::automation_science_pack},
		{RecipeNames[RecipeType::firearm_magazine], RecipeType::firearm_magazine},
		{RecipeNames[RecipeType::pistol], RecipeType::pistol},
		{RecipeNames[RecipeType::piercing_rounds_magazine], RecipeType::piercing_rounds_magazine},
		{RecipeNames[RecipeType::submachine_gun], RecipeType::submachine_gun},
		{RecipeNames[RecipeType::uranium_rounds_magazine], RecipeType::uranium_rounds_magazine},
		{RecipeNames[RecipeType::beacon], RecipeType::beacon},
		{RecipeNames[RecipeType::burner_inserter], RecipeType::burner_inserter},
		{RecipeNames[RecipeType::copper_cable], RecipeType::copper_cable},
		{RecipeNames[RecipeType::electric_energy_interface], RecipeType::electric_energy_interface},
		{RecipeNames[RecipeType::solar_panel_equipment], RecipeType::solar_panel_equipment},
		{RecipeNames[RecipeType::fusion_reactor_equipment], RecipeType::fusion_reactor_equipment},
		{RecipeNames[RecipeType::small_electric_pole], RecipeType::small_electric_pole},
		{RecipeNames[RecipeType::medium_electric_pole], RecipeType::medium_electric_pole},
		{RecipeNames[RecipeType::big_electric_pole], RecipeType::big_electric_pole},
		{RecipeNames[RecipeType::substation], RecipeType::substation},
		{RecipeNames[RecipeType::sulfuric_acid], RecipeType::sulfuric_acid},
		{RecipeNames[RecipeType::grenade], RecipeType::grenade},
		{RecipeNames[RecipeType::cluster_grenade], RecipeType::cluster_grenade},
		{RecipeNames[RecipeType::burner_mining_drill], RecipeType::burner_mining_drill},
		{RecipeNames[RecipeType::wooden_chest], RecipeType::wooden_chest},
		{RecipeNames[RecipeType::electric_mining_drill], RecipeType::electric_mining_drill},
		{RecipeNames[RecipeType::iron_chest], RecipeType::iron_chest},
		{RecipeNames[RecipeType::steel_chest], RecipeType::steel_chest},
		{RecipeNames[RecipeType::light_armor], RecipeType::light_armor},
		{RecipeNames[RecipeType::small_lamp], RecipeType::small_lamp},
		{RecipeNames[RecipeType::basic_oil_processing], RecipeType::basic_oil_processing},
		{RecipeNames[RecipeType::advanced_oil_processing], RecipeType::advanced_oil_processing},
		{RecipeNames[RecipeType::coal_liquefaction], RecipeType::coal_liquefaction},
		{RecipeNames[RecipeType::pipe], RecipeType::pipe},
		{RecipeNames[RecipeType::pipe_to_ground], RecipeType::pipe_to_ground},
		{RecipeNames[RecipeType::logistic_robot], RecipeType::logistic_robot},
		{RecipeNames[RecipeType::construction_robot], RecipeType::construction_robot},
		{RecipeNames[RecipeType::energy_shield_equipment], RecipeType::energy_shield_equipment},
		{RecipeNames[RecipeType::energy_shield_mk2_equipment], RecipeType::energy_shield_mk2_equipment},
		{RecipeNames[RecipeType::speed_module], RecipeType::speed_module},
		{RecipeNames[RecipeType::speed_module_2], RecipeType::speed_module_2},
		{RecipeNames[RecipeType::speed_module_3], RecipeType::speed_module_3},
		{RecipeNames[RecipeType::stone_brick], RecipeType::stone_brick},
		{RecipeNames[RecipeType::stone_furnace], RecipeType::stone_furnace},
		{RecipeNames[RecipeType::stone_wall], RecipeType::stone_wall},
		{RecipeNames[RecipeType::rail], RecipeType::rail},
		{RecipeNames[RecipeType::train_stop], RecipeType::train_stop},
		{RecipeNames[RecipeType::rail_signal], RecipeType::rail_signal},
		{RecipeNames[RecipeType::rail_chain_signal], RecipeType::rail_chain_signal},
		{RecipeNames[RecipeType::locomotive], RecipeType::locomotive},
		{RecipeNames[RecipeType::cargo_wagon], RecipeType::cargo_wagon},
		{RecipeNames[RecipeType::fluid_wagon], RecipeType::fluid_wagon},
		{RecipeNames[RecipeType::artillery_wagon], RecipeType::artillery_wagon},
		{RecipeNames[RecipeType::transport_belt], RecipeType::transport_belt},
		{RecipeNames[RecipeType::fast_transport_belt], RecipeType::fast_transport_belt},
		{RecipeNames[RecipeType::express_transport_belt], RecipeType::express_transport_belt},
		{RecipeNames[RecipeType::gate], RecipeType::gate},
		{RecipeNames[RecipeType::personal_laser_defense_equipment], RecipeType::personal_laser_defense_equipment},
		{RecipeNames[RecipeType::discharge_defense_equipment], RecipeType::discharge_defense_equipment},
		{RecipeNames[RecipeType::discharge_defense_remote], RecipeType::discharge_defense_remote},
		{RecipeNames[RecipeType::assembling_machine_2], RecipeType::assembling_machine_2},
		{RecipeNames[RecipeType::battery_equipment], RecipeType::battery_equipment},
		{RecipeNames[RecipeType::battery_mk2_equipment], RecipeType::battery_mk2_equipment},
		{RecipeNames[RecipeType::concrete], RecipeType::concrete},
		{RecipeNames[RecipeType::hazard_concrete], RecipeType::hazard_concrete},
		{RecipeNames[RecipeType::refined_concrete], RecipeType::refined_concrete},
		{RecipeNames[RecipeType::refined_hazard_concrete], RecipeType::refined_hazard_concrete},
		{RecipeNames[RecipeType::fill_crude_oil_barrel], RecipeType::fill_crude_oil_barrel},
		{RecipeNames[RecipeType::fill_heavy_oil_barrel], RecipeType::fill_heavy_oil_barrel},
		{RecipeNames[RecipeType::fill_light_oil_barrel], RecipeType::fill_light_oil_barrel},
		{RecipeNames[RecipeType::fill_lubricant_barrel], RecipeType::fill_lubricant_barrel},
		{RecipeNames[RecipeType::fill_petroleum_gas_barrel], RecipeType::fill_petroleum_gas_barrel},
		{RecipeNames[RecipeType::fill_sulfuric_acid_barrel], RecipeType::fill_sulfuric_acid_barrel},
		{RecipeNames[RecipeType::fill_water_barrel], RecipeType::fill_water_barrel},
		{RecipeNames[RecipeType::heavy_oil_cracking], RecipeType::heavy_oil_cracking},
		{RecipeNames[RecipeType::light_oil_cracking], RecipeType::light_oil_cracking},
		{RecipeNames[RecipeType::solid_fuel_from_light_oil], RecipeType::solid_fuel_from_light_oil},
		{RecipeNames[RecipeType::solid_fuel_from_petroleum_gas], RecipeType::solid_fuel_from_petroleum_gas},
		{RecipeNames[RecipeType::solid_fuel_from_heavy_oil], RecipeType::solid_fuel_from_heavy_oil},
		{RecipeNames[RecipeType::storage_tank], RecipeType::storage_tank},
		{RecipeNames[RecipeType::offshore_pump], RecipeType::offshore_pump},
		{RecipeNames[RecipeType::pumpjack], RecipeType::pumpjack},
		{RecipeNames[RecipeType::heavy_armor], RecipeType::heavy_armor},
		{RecipeNames[RecipeType::inserter], RecipeType::inserter},
		{RecipeNames[RecipeType::iron_plate], RecipeType::iron_plate},
		{RecipeNames[RecipeType::iron_stick], RecipeType::iron_stick},
		{RecipeNames[RecipeType::logistic_science_pack], RecipeType::logistic_science_pack},
		{RecipeNames[RecipeType::car], RecipeType::car},
		{RecipeNames[RecipeType::tank], RecipeType::tank},
		{RecipeNames[RecipeType::spidertron], RecipeType::spidertron},
		{RecipeNames[RecipeType::spidertron_remote], RecipeType::spidertron_remote},
		{RecipeNames[RecipeType::pump], RecipeType::pump},
		{RecipeNames[RecipeType::poison_capsule], RecipeType::poison_capsule},
		{RecipeNames[RecipeType::repair_pack], RecipeType::repair_pack},
		{RecipeNames[RecipeType::shotgun], RecipeType::shotgun},
		{RecipeNames[RecipeType::shotgun_shell], RecipeType::shotgun_shell},
		{RecipeNames[RecipeType::combat_shotgun], RecipeType::combat_shotgun},
		{RecipeNames[RecipeType::piercing_shotgun_shell], RecipeType::piercing_shotgun_shell},
		{RecipeNames[RecipeType::boiler], RecipeType::boiler},
		{RecipeNames[RecipeType::steam_engine], RecipeType::steam_engine},
		{RecipeNames[RecipeType::steel_furnace], RecipeType::steel_furnace},
		{RecipeNames[RecipeType::logistic_chest_active_provider], RecipeType::logistic_chest_active_provider},
		{RecipeNames[RecipeType::logistic_chest_passive_provider], RecipeType::logistic_chest_passive_provider},
		{RecipeNames[RecipeType::logistic_chest_storage], RecipeType::logistic_chest_storage},
		{RecipeNames[RecipeType::logistic_chest_buffer], RecipeType::logistic_chest_buffer},
		{RecipeNames[RecipeType::logistic_chest_requester], RecipeType::logistic_chest_requester},
		{RecipeNames[RecipeType::gun_turret], RecipeType::gun_turret},
		{RecipeNames[RecipeType::laser_turret], RecipeType::laser_turret},
		{RecipeNames[RecipeType::flamethrower_turret], RecipeType::flamethrower_turret},
		{RecipeNames[RecipeType::artillery_turret], RecipeType::artillery_turret},
		{RecipeNames[RecipeType::artillery_targeting_remote], RecipeType::artillery_targeting_remote},
		{RecipeNames[RecipeType::underground_belt], RecipeType::underground_belt},
		{RecipeNames[RecipeType::fast_underground_belt], RecipeType::fast_underground_belt},
		{RecipeNames[RecipeType::express_underground_belt], RecipeType::express_underground_belt},
		{RecipeNames[RecipeType::red_wire], RecipeType::red_wire},
		{RecipeNames[RecipeType::green_wire], RecipeType::green_wire},
		{RecipeNames[RecipeType::assembling_machine_3], RecipeType::assembling_machine_3},
		{RecipeNames[RecipeType::belt_immunity_equipment], RecipeType::belt_immunity_equipment},
		{RecipeNames[RecipeType::arithmetic_combinator], RecipeType::arithmetic_combinator},
		{RecipeNames[RecipeType::decider_combinator], RecipeType::decider_combinator},
		{RecipeNames[RecipeType::constant_combinator], RecipeType::constant_combinator},
		{RecipeNames[RecipeType::copper_plate], RecipeType::copper_plate},
		{RecipeNames[RecipeType::effectivity_module], RecipeType::effectivity_module},
		{RecipeNames[RecipeType::effectivity_module_2], RecipeType::effectivity_module_2},
		{RecipeNames[RecipeType::effectivity_module_3], RecipeType::effectivity_module_3},
		{RecipeNames[RecipeType::electric_furnace], RecipeType::electric_furnace},
		{RecipeNames[RecipeType::empty_crude_oil_barrel], RecipeType::empty_crude_oil_barrel},
		{RecipeNames[RecipeType::empty_heavy_oil_barrel], RecipeType::empty_heavy_oil_barrel},
		{RecipeNames[RecipeType::empty_light_oil_barrel], RecipeType::empty_light_oil_barrel},
		{RecipeNames[RecipeType::empty_lubricant_barrel], RecipeType::empty_lubricant_barrel},
		{RecipeNames[RecipeType::empty_petroleum_gas_barrel], RecipeType::empty_petroleum_gas_barrel},
		{RecipeNames[RecipeType::empty_sulfuric_acid_barrel], RecipeType::empty_sulfuric_acid_barrel},
		{RecipeNames[RecipeType::empty_water_barrel], RecipeType::empty_water_barrel},
		{RecipeNames[RecipeType::iron_gear_wheel], RecipeType::iron_gear_wheel},
		{RecipeNames[RecipeType::landfill], RecipeType::landfill},
		{RecipeNames[RecipeType::long_handed_inserter], RecipeType::long_handed_inserter},
		{RecipeNames[RecipeType::military_science_pack], RecipeType::military_science_pack},
		{RecipeNames[RecipeType::modular_armor], RecipeType::modular_armor},
		{RecipeNames[RecipeType::productivity_module], RecipeType::productivity_module},
		{RecipeNames[RecipeType::productivity_module_2], RecipeType::productivity_module_2},
		{RecipeNames[RecipeType::productivity_module_3], RecipeType::productivity_module_3},
		{RecipeNames[RecipeType::roboport], RecipeType::roboport},
		{RecipeNames[RecipeType::slowdown_capsule], RecipeType::slowdown_capsule},
		{RecipeNames[RecipeType::splitter], RecipeType::splitter},
		{RecipeNames[RecipeType::fast_splitter], RecipeType::fast_splitter},
		{RecipeNames[RecipeType::express_splitter], RecipeType::express_splitter},
		{RecipeNames[RecipeType::cannon_shell], RecipeType::cannon_shell},
		{RecipeNames[RecipeType::explosive_cannon_shell], RecipeType::explosive_cannon_shell},
		{RecipeNames[RecipeType::uranium_cannon_shell], RecipeType::uranium_cannon_shell},
		{RecipeNames[RecipeType::chemical_science_pack], RecipeType::chemical_science_pack},
		{RecipeNames[RecipeType::cliff_explosives], RecipeType::cliff_explosives},
		{RecipeNames[RecipeType::defender_capsule], RecipeType::defender_capsule},
		{RecipeNames[RecipeType::empty_barrel], RecipeType::empty_barrel},
		{RecipeNames[RecipeType::exoskeleton_equipment], RecipeType::exoskeleton_equipment},
		{RecipeNames[RecipeType::explosive_uranium_cannon_shell], RecipeType::explosive_uranium_cannon_shell},
		{RecipeNames[RecipeType::artillery_shell], RecipeType::artillery_shell},
		{RecipeNames[RecipeType::fast_inserter], RecipeType::fast_inserter},
		{RecipeNames[RecipeType::power_switch], RecipeType::power_switch},
		{RecipeNames[RecipeType::programmable_speaker], RecipeType::programmable_speaker},
		{RecipeNames[RecipeType::power_armor], RecipeType::power_armor},
		{RecipeNames[RecipeType::radar], RecipeType::radar},
		{RecipeNames[RecipeType::oil_refinery], RecipeType::oil_refinery},
		{RecipeNames[RecipeType::rocket_launcher], RecipeType::rocket_launcher},
		{RecipeNames[RecipeType::rocket], RecipeType::rocket},
		{RecipeNames[RecipeType::explosive_rocket], RecipeType::explosive_rocket},
		{RecipeNames[RecipeType::atomic_bomb], RecipeType::atomic_bomb},
		{RecipeNames[RecipeType::solar_panel], RecipeType::solar_panel},
		{RecipeNames[RecipeType::steel_plate], RecipeType::steel_plate},
		{RecipeNames[RecipeType::accumulator], RecipeType::accumulator},
		{RecipeNames[RecipeType::chemical_plant], RecipeType::chemical_plant},
		{RecipeNames[RecipeType::distractor_capsule], RecipeType::distractor_capsule},
		{RecipeNames[RecipeType::electronic_circuit], RecipeType::electronic_circuit},
		{RecipeNames[RecipeType::filter_inserter], RecipeType::filter_inserter},
		{RecipeNames[RecipeType::flamethrower], RecipeType::flamethrower},
		{RecipeNames[RecipeType::flamethrower_ammo], RecipeType::flamethrower_ammo},
		{RecipeNames[RecipeType::lubricant], RecipeType::lubricant},
		{RecipeNames[RecipeType::power_armor_mk2], RecipeType::power_armor_mk2},
		{RecipeNames[RecipeType::production_science_pack], RecipeType::production_science_pack},
		{RecipeNames[RecipeType::personal_roboport_equipment], RecipeType::personal_roboport_equipment},
		{RecipeNames[RecipeType::personal_roboport_mk2_equipment], RecipeType::personal_roboport_mk2_equipment},
		{RecipeNames[RecipeType::rocket_silo], RecipeType::rocket_silo},
		{RecipeNames[RecipeType::advanced_circuit], RecipeType::advanced_circuit},
		{RecipeNames[RecipeType::destroyer_capsule], RecipeType::destroyer_capsule},
		{RecipeNames[RecipeType::land_mine], RecipeType::land_mine},
		{RecipeNames[RecipeType::night_vision_equipment], RecipeType::night_vision_equipment},
		{RecipeNames[RecipeType::nuclear_reactor], RecipeType::nuclear_reactor},
		{RecipeNames[RecipeType::heat_pipe], RecipeType::heat_pipe},
		{RecipeNames[RecipeType::heat_exchanger], RecipeType::heat_exchanger},
		{RecipeNames[RecipeType::steam_turbine], RecipeType::steam_turbine},
		{RecipeNames[RecipeType::plastic_bar], RecipeType::plastic_bar},
		{RecipeNames[RecipeType::stack_inserter], RecipeType::stack_inserter},
		{RecipeNames[RecipeType::utility_science_pack], RecipeType::utility_science_pack},
		{RecipeNames[RecipeType::centrifuge], RecipeType::centrifuge},
		{RecipeNames[RecipeType::lab], RecipeType::lab},
		{RecipeNames[RecipeType::processing_unit], RecipeType::processing_unit},
		{RecipeNames[RecipeType::stack_filter_inserter], RecipeType::stack_filter_inserter},
		{RecipeNames[RecipeType::sulfur], RecipeType::sulfur},
		{RecipeNames[RecipeType::battery], RecipeType::battery},
		{RecipeNames[RecipeType::engine_unit], RecipeType::engine_unit},
		{RecipeNames[RecipeType::electric_engine_unit], RecipeType::electric_engine_unit},
		{RecipeNames[RecipeType::explosives], RecipeType::explosives},
		{RecipeNames[RecipeType::uranium_processing], RecipeType::uranium_processing},
		{RecipeNames[RecipeType::flying_robot_frame], RecipeType::flying_robot_frame},
		{RecipeNames[RecipeType::satellite], RecipeType::satellite},
		{RecipeNames[RecipeType::rocket_control_unit], RecipeType::rocket_control_unit},
		{RecipeNames[RecipeType::low_density_structure], RecipeType::low_density_structure},
		{RecipeNames[RecipeType::rocket_fuel], RecipeType::rocket_fuel},
		{RecipeNames[RecipeType::nuclear_fuel], RecipeType::nuclear_fuel},
		{RecipeNames[RecipeType::uranium_fuel_cell], RecipeType::uranium_fuel_cell},
		{RecipeNames[RecipeType::nuclear_fuel_reprocessing], RecipeType::nuclear_fuel_reprocessing},
		{RecipeNames[RecipeType::kovarex_enrichment_process], RecipeType::kovarex_enrichment_process},

		{to_lower(RecipeNames[RecipeType::assembling_machine_1]), RecipeType::assembling_machine_1},
		{to_lower(RecipeNames[RecipeType::automation_science_pack]), RecipeType::automation_science_pack},
		{to_lower(RecipeNames[RecipeType::firearm_magazine]), RecipeType::firearm_magazine},
		{to_lower(RecipeNames[RecipeType::pistol]), RecipeType::pistol},
		{to_lower(RecipeNames[RecipeType::piercing_rounds_magazine]), RecipeType::piercing_rounds_magazine},
		{to_lower(RecipeNames[RecipeType::submachine_gun]), RecipeType::submachine_gun},
		{to_lower(RecipeNames[RecipeType::uranium_rounds_magazine]), RecipeType::uranium_rounds_magazine},
		{to_lower(RecipeNames[RecipeType::beacon]), RecipeType::beacon},
		{to_lower(RecipeNames[RecipeType::burner_inserter]), RecipeType::burner_inserter},
		{to_lower(RecipeNames[RecipeType::copper_cable]), RecipeType::copper_cable},
		{to_lower(RecipeNames[RecipeType::electric_energy_interface]), RecipeType::electric_energy_interface},
		{to_lower(RecipeNames[RecipeType::solar_panel_equipment]), RecipeType::solar_panel_equipment},
		{to_lower(RecipeNames[RecipeType::fusion_reactor_equipment]), RecipeType::fusion_reactor_equipment},
		{to_lower(RecipeNames[RecipeType::small_electric_pole]), RecipeType::small_electric_pole},
		{to_lower(RecipeNames[RecipeType::medium_electric_pole]), RecipeType::medium_electric_pole},
		{to_lower(RecipeNames[RecipeType::big_electric_pole]), RecipeType::big_electric_pole},
		{to_lower(RecipeNames[RecipeType::substation]), RecipeType::substation},
		{to_lower(RecipeNames[RecipeType::sulfuric_acid]), RecipeType::sulfuric_acid},
		{to_lower(RecipeNames[RecipeType::grenade]), RecipeType::grenade},
		{to_lower(RecipeNames[RecipeType::cluster_grenade]), RecipeType::cluster_grenade},
		{to_lower(RecipeNames[RecipeType::burner_mining_drill]), RecipeType::burner_mining_drill},
		{to_lower(RecipeNames[RecipeType::wooden_chest]), RecipeType::wooden_chest},
		{to_lower(RecipeNames[RecipeType::electric_mining_drill]), RecipeType::electric_mining_drill},
		{to_lower(RecipeNames[RecipeType::iron_chest]), RecipeType::iron_chest},
		{to_lower(RecipeNames[RecipeType::steel_chest]), RecipeType::steel_chest},
		{to_lower(RecipeNames[RecipeType::light_armor]), RecipeType::light_armor},
		{to_lower(RecipeNames[RecipeType::small_lamp]), RecipeType::small_lamp},
		{to_lower(RecipeNames[RecipeType::basic_oil_processing]), RecipeType::basic_oil_processing},
		{to_lower(RecipeNames[RecipeType::advanced_oil_processing]), RecipeType::advanced_oil_processing},
		{to_lower(RecipeNames[RecipeType::coal_liquefaction]), RecipeType::coal_liquefaction},
		{to_lower(RecipeNames[RecipeType::pipe]), RecipeType::pipe},
		{to_lower(RecipeNames[RecipeType::pipe_to_ground]), RecipeType::pipe_to_ground},
		{to_lower(RecipeNames[RecipeType::logistic_robot]), RecipeType::logistic_robot},
		{to_lower(RecipeNames[RecipeType::construction_robot]), RecipeType::construction_robot},
		{to_lower(RecipeNames[RecipeType::energy_shield_equipment]), RecipeType::energy_shield_equipment},
		{to_lower(RecipeNames[RecipeType::energy_shield_mk2_equipment]), RecipeType::energy_shield_mk2_equipment},
		{to_lower(RecipeNames[RecipeType::speed_module]), RecipeType::speed_module},
		{to_lower(RecipeNames[RecipeType::speed_module_2]), RecipeType::speed_module_2},
		{to_lower(RecipeNames[RecipeType::speed_module_3]), RecipeType::speed_module_3},
		{to_lower(RecipeNames[RecipeType::stone_brick]), RecipeType::stone_brick},
		{to_lower(RecipeNames[RecipeType::stone_furnace]), RecipeType::stone_furnace},
		{to_lower(RecipeNames[RecipeType::stone_wall]), RecipeType::stone_wall},
		{to_lower(RecipeNames[RecipeType::rail]), RecipeType::rail},
		{to_lower(RecipeNames[RecipeType::train_stop]), RecipeType::train_stop},
		{to_lower(RecipeNames[RecipeType::rail_signal]), RecipeType::rail_signal},
		{to_lower(RecipeNames[RecipeType::rail_chain_signal]), RecipeType::rail_chain_signal},
		{to_lower(RecipeNames[RecipeType::locomotive]), RecipeType::locomotive},
		{to_lower(RecipeNames[RecipeType::cargo_wagon]), RecipeType::cargo_wagon},
		{to_lower(RecipeNames[RecipeType::fluid_wagon]), RecipeType::fluid_wagon},
		{to_lower(RecipeNames[RecipeType::artillery_wagon]), RecipeType::artillery_wagon},
		{to_lower(RecipeNames[RecipeType::transport_belt]), RecipeType::transport_belt},
		{to_lower(RecipeNames[RecipeType::fast_transport_belt]), RecipeType::fast_transport_belt},
		{to_lower(RecipeNames[RecipeType::express_transport_belt]), RecipeType::express_transport_belt},
		{to_lower(RecipeNames[RecipeType::gate]), RecipeType::gate},
		{to_lower(RecipeNames[RecipeType::personal_laser_defense_equipment]), RecipeType::personal_laser_defense_equipment},
		{to_lower(RecipeNames[RecipeType::discharge_defense_equipment]), RecipeType::discharge_defense_equipment},
		{to_lower(RecipeNames[RecipeType::discharge_defense_remote]), RecipeType::discharge_defense_remote},
		{to_lower(RecipeNames[RecipeType::assembling_machine_2]), RecipeType::assembling_machine_2},
		{to_lower(RecipeNames[RecipeType::battery_equipment]), RecipeType::battery_equipment},
		{to_lower(RecipeNames[RecipeType::battery_mk2_equipment]), RecipeType::battery_mk2_equipment},
		{to_lower(RecipeNames[RecipeType::concrete]), RecipeType::concrete},
		{to_lower(RecipeNames[RecipeType::hazard_concrete]), RecipeType::hazard_concrete},
		{to_lower(RecipeNames[RecipeType::refined_concrete]), RecipeType::refined_concrete},
		{to_lower(RecipeNames[RecipeType::refined_hazard_concrete]), RecipeType::refined_hazard_concrete},
		{to_lower(RecipeNames[RecipeType::fill_crude_oil_barrel]), RecipeType::fill_crude_oil_barrel},
		{to_lower(RecipeNames[RecipeType::fill_heavy_oil_barrel]), RecipeType::fill_heavy_oil_barrel},
		{to_lower(RecipeNames[RecipeType::fill_light_oil_barrel]), RecipeType::fill_light_oil_barrel},
		{to_lower(RecipeNames[RecipeType::fill_lubricant_barrel]), RecipeType::fill_lubricant_barrel},
		{to_lower(RecipeNames[RecipeType::fill_petroleum_gas_barrel]), RecipeType::fill_petroleum_gas_barrel},
		{to_lower(RecipeNames[RecipeType::fill_sulfuric_acid_barrel]), RecipeType::fill_sulfuric_acid_barrel},
		{to_lower(RecipeNames[RecipeType::fill_water_barrel]), RecipeType::fill_water_barrel},
		{to_lower(RecipeNames[RecipeType::heavy_oil_cracking]), RecipeType::heavy_oil_cracking},
		{to_lower(RecipeNames[RecipeType::light_oil_cracking]), RecipeType::light_oil_cracking},
		{to_lower(RecipeNames[RecipeType::solid_fuel_from_light_oil]), RecipeType::solid_fuel_from_light_oil},
		{to_lower(RecipeNames[RecipeType::solid_fuel_from_petroleum_gas]), RecipeType::solid_fuel_from_petroleum_gas},
		{to_lower(RecipeNames[RecipeType::solid_fuel_from_heavy_oil]), RecipeType::solid_fuel_from_heavy_oil},
		{to_lower(RecipeNames[RecipeType::storage_tank]), RecipeType::storage_tank},
		{to_lower(RecipeNames[RecipeType::offshore_pump]), RecipeType::offshore_pump},
		{to_lower(RecipeNames[RecipeType::pumpjack]), RecipeType::pumpjack},
		{to_lower(RecipeNames[RecipeType::heavy_armor]), RecipeType::heavy_armor},
		{to_lower(RecipeNames[RecipeType::inserter]), RecipeType::inserter},
		{to_lower(RecipeNames[RecipeType::iron_plate]), RecipeType::iron_plate},
		{to_lower(RecipeNames[RecipeType::iron_stick]), RecipeType::iron_stick},
		{to_lower(RecipeNames[RecipeType::logistic_science_pack]), RecipeType::logistic_science_pack},
		{to_lower(RecipeNames[RecipeType::car]), RecipeType::car},
		{to_lower(RecipeNames[RecipeType::tank]), RecipeType::tank},
		{to_lower(RecipeNames[RecipeType::spidertron]), RecipeType::spidertron},
		{to_lower(RecipeNames[RecipeType::spidertron_remote]), RecipeType::spidertron_remote},
		{to_lower(RecipeNames[RecipeType::pump]), RecipeType::pump},
		{to_lower(RecipeNames[RecipeType::poison_capsule]), RecipeType::poison_capsule},
		{to_lower(RecipeNames[RecipeType::repair_pack]), RecipeType::repair_pack},
		{to_lower(RecipeNames[RecipeType::shotgun]), RecipeType::shotgun},
		{to_lower(RecipeNames[RecipeType::shotgun_shell]), RecipeType::shotgun_shell},
		{to_lower(RecipeNames[RecipeType::combat_shotgun]), RecipeType::combat_shotgun},
		{to_lower(RecipeNames[RecipeType::piercing_shotgun_shell]), RecipeType::piercing_shotgun_shell},
		{to_lower(RecipeNames[RecipeType::boiler]), RecipeType::boiler},
		{to_lower(RecipeNames[RecipeType::steam_engine]), RecipeType::steam_engine},
		{to_lower(RecipeNames[RecipeType::steel_furnace]), RecipeType::steel_furnace},
		{to_lower(RecipeNames[RecipeType::logistic_chest_active_provider]), RecipeType::logistic_chest_active_provider},
		{to_lower(RecipeNames[RecipeType::logistic_chest_passive_provider]), RecipeType::logistic_chest_passive_provider},
		{to_lower(RecipeNames[RecipeType::logistic_chest_storage]), RecipeType::logistic_chest_storage},
		{to_lower(RecipeNames[RecipeType::logistic_chest_buffer]), RecipeType::logistic_chest_buffer},
		{to_lower(RecipeNames[RecipeType::logistic_chest_requester]), RecipeType::logistic_chest_requester},
		{to_lower(RecipeNames[RecipeType::gun_turret]), RecipeType::gun_turret},
		{to_lower(RecipeNames[RecipeType::laser_turret]), RecipeType::laser_turret},
		{to_lower(RecipeNames[RecipeType::flamethrower_turret]), RecipeType::flamethrower_turret},
		{to_lower(RecipeNames[RecipeType::artillery_turret]), RecipeType::artillery_turret},
		{to_lower(RecipeNames[RecipeType::artillery_targeting_remote]), RecipeType::artillery_targeting_remote},
		{to_lower(RecipeNames[RecipeType::underground_belt]), RecipeType::underground_belt},
		{to_lower(RecipeNames[RecipeType::fast_underground_belt]), RecipeType::fast_underground_belt},
		{to_lower(RecipeNames[RecipeType::express_underground_belt]), RecipeType::express_underground_belt},
		{to_lower(RecipeNames[RecipeType::red_wire]), RecipeType::red_wire},
		{to_lower(RecipeNames[RecipeType::green_wire]), RecipeType::green_wire},
		{to_lower(RecipeNames[RecipeType::assembling_machine_3]), RecipeType::assembling_machine_3},
		{to_lower(RecipeNames[RecipeType::belt_immunity_equipment]), RecipeType::belt_immunity_equipment},
		{to_lower(RecipeNames[RecipeType::arithmetic_combinator]), RecipeType::arithmetic_combinator},
		{to_lower(RecipeNames[RecipeType::decider_combinator]), RecipeType::decider_combinator},
		{to_lower(RecipeNames[RecipeType::constant_combinator]), RecipeType::constant_combinator},
		{to_lower(RecipeNames[RecipeType::copper_plate]), RecipeType::copper_plate},
		{to_lower(RecipeNames[RecipeType::effectivity_module]), RecipeType::effectivity_module},
		{to_lower(RecipeNames[RecipeType::effectivity_module_2]), RecipeType::effectivity_module_2},
		{to_lower(RecipeNames[RecipeType::effectivity_module_3]), RecipeType::effectivity_module_3},
		{to_lower(RecipeNames[RecipeType::electric_furnace]), RecipeType::electric_furnace},
		{to_lower(RecipeNames[RecipeType::empty_crude_oil_barrel]), RecipeType::empty_crude_oil_barrel},
		{to_lower(RecipeNames[RecipeType::empty_heavy_oil_barrel]), RecipeType::empty_heavy_oil_barrel},
		{to_lower(RecipeNames[RecipeType::empty_light_oil_barrel]), RecipeType::empty_light_oil_barrel},
		{to_lower(RecipeNames[RecipeType::empty_lubricant_barrel]), RecipeType::empty_lubricant_barrel},
		{to_lower(RecipeNames[RecipeType::empty_petroleum_gas_barrel]), RecipeType::empty_petroleum_gas_barrel},
		{to_lower(RecipeNames[RecipeType::empty_sulfuric_acid_barrel]), RecipeType::empty_sulfuric_acid_barrel},
		{to_lower(RecipeNames[RecipeType::empty_water_barrel]), RecipeType::empty_water_barrel},
		{to_lower(RecipeNames[RecipeType::iron_gear_wheel]), RecipeType::iron_gear_wheel},
		{to_lower(RecipeNames[RecipeType::landfill]), RecipeType::landfill},
		{to_lower(RecipeNames[RecipeType::long_handed_inserter]), RecipeType::long_handed_inserter},
		{to_lower(RecipeNames[RecipeType::military_science_pack]), RecipeType::military_science_pack},
		{to_lower(RecipeNames[RecipeType::modular_armor]), RecipeType::modular_armor},
		{to_lower(RecipeNames[RecipeType::productivity_module]), RecipeType::productivity_module},
		{to_lower(RecipeNames[RecipeType::productivity_module_2]), RecipeType::productivity_module_2},
		{to_lower(RecipeNames[RecipeType::productivity_module_3]), RecipeType::productivity_module_3},
		{to_lower(RecipeNames[RecipeType::roboport]), RecipeType::roboport},
		{to_lower(RecipeNames[RecipeType::slowdown_capsule]), RecipeType::slowdown_capsule},
		{to_lower(RecipeNames[RecipeType::splitter]), RecipeType::splitter},
		{to_lower(RecipeNames[RecipeType::fast_splitter]), RecipeType::fast_splitter},
		{to_lower(RecipeNames[RecipeType::express_splitter]), RecipeType::express_splitter},
		{to_lower(RecipeNames[RecipeType::cannon_shell]), RecipeType::cannon_shell},
		{to_lower(RecipeNames[RecipeType::explosive_cannon_shell]), RecipeType::explosive_cannon_shell},
		{to_lower(RecipeNames[RecipeType::uranium_cannon_shell]), RecipeType::uranium_cannon_shell},
		{to_lower(RecipeNames[RecipeType::chemical_science_pack]), RecipeType::chemical_science_pack},
		{to_lower(RecipeNames[RecipeType::cliff_explosives]), RecipeType::cliff_explosives},
		{to_lower(RecipeNames[RecipeType::defender_capsule]), RecipeType::defender_capsule},
		{to_lower(RecipeNames[RecipeType::empty_barrel]), RecipeType::empty_barrel},
		{to_lower(RecipeNames[RecipeType::exoskeleton_equipment]), RecipeType::exoskeleton_equipment},
		{to_lower(RecipeNames[RecipeType::explosive_uranium_cannon_shell]), RecipeType::explosive_uranium_cannon_shell},
		{to_lower(RecipeNames[RecipeType::artillery_shell]), RecipeType::artillery_shell},
		{to_lower(RecipeNames[RecipeType::fast_inserter]), RecipeType::fast_inserter},
		{to_lower(RecipeNames[RecipeType::power_switch]), RecipeType::power_switch},
		{to_lower(RecipeNames[RecipeType::programmable_speaker]), RecipeType::programmable_speaker},
		{to_lower(RecipeNames[RecipeType::power_armor]), RecipeType::power_armor},
		{to_lower(RecipeNames[RecipeType::radar]), RecipeType::radar},
		{to_lower(RecipeNames[RecipeType::oil_refinery]), RecipeType::oil_refinery},
		{to_lower(RecipeNames[RecipeType::rocket_launcher]), RecipeType::rocket_launcher},
		{to_lower(RecipeNames[RecipeType::rocket]), RecipeType::rocket},
		{to_lower(RecipeNames[RecipeType::explosive_rocket]), RecipeType::explosive_rocket},
		{to_lower(RecipeNames[RecipeType::atomic_bomb]), RecipeType::atomic_bomb},
		{to_lower(RecipeNames[RecipeType::solar_panel]), RecipeType::solar_panel},
		{to_lower(RecipeNames[RecipeType::steel_plate]), RecipeType::steel_plate},
		{to_lower(RecipeNames[RecipeType::accumulator]), RecipeType::accumulator},
		{to_lower(RecipeNames[RecipeType::chemical_plant]), RecipeType::chemical_plant},
		{to_lower(RecipeNames[RecipeType::distractor_capsule]), RecipeType::distractor_capsule},
		{to_lower(RecipeNames[RecipeType::electronic_circuit]), RecipeType::electronic_circuit},
		{to_lower(RecipeNames[RecipeType::filter_inserter]), RecipeType::filter_inserter},
		{to_lower(RecipeNames[RecipeType::flamethrower]), RecipeType::flamethrower},
		{to_lower(RecipeNames[RecipeType::flamethrower_ammo]), RecipeType::flamethrower_ammo},
		{to_lower(RecipeNames[RecipeType::lubricant]), RecipeType::lubricant},
		{to_lower(RecipeNames[RecipeType::power_armor_mk2]), RecipeType::power_armor_mk2},
		{to_lower(RecipeNames[RecipeType::production_science_pack]), RecipeType::production_science_pack},
		{to_lower(RecipeNames[RecipeType::personal_roboport_equipment]), RecipeType::personal_roboport_equipment},
		{to_lower(RecipeNames[RecipeType::personal_roboport_mk2_equipment]), RecipeType::personal_roboport_mk2_equipment},
		{to_lower(RecipeNames[RecipeType::rocket_silo]), RecipeType::rocket_silo},
		{to_lower(RecipeNames[RecipeType::advanced_circuit]), RecipeType::advanced_circuit},
		{to_lower(RecipeNames[RecipeType::destroyer_capsule]), RecipeType::destroyer_capsule},
		{to_lower(RecipeNames[RecipeType::land_mine]), RecipeType::land_mine},
		{to_lower(RecipeNames[RecipeType::night_vision_equipment]), RecipeType::night_vision_equipment},
		{to_lower(RecipeNames[RecipeType::nuclear_reactor]), RecipeType::nuclear_reactor},
		{to_lower(RecipeNames[RecipeType::heat_pipe]), RecipeType::heat_pipe},
		{to_lower(RecipeNames[RecipeType::heat_exchanger]), RecipeType::heat_exchanger},
		{to_lower(RecipeNames[RecipeType::steam_turbine]), RecipeType::steam_turbine},
		{to_lower(RecipeNames[RecipeType::plastic_bar]), RecipeType::plastic_bar},
		{to_lower(RecipeNames[RecipeType::stack_inserter]), RecipeType::stack_inserter},
		{to_lower(RecipeNames[RecipeType::utility_science_pack]), RecipeType::utility_science_pack},
		{to_lower(RecipeNames[RecipeType::centrifuge]), RecipeType::centrifuge},
		{to_lower(RecipeNames[RecipeType::lab]), RecipeType::lab},
		{to_lower(RecipeNames[RecipeType::processing_unit]), RecipeType::processing_unit},
		{to_lower(RecipeNames[RecipeType::stack_filter_inserter]), RecipeType::stack_filter_inserter},
		{to_lower(RecipeNames[RecipeType::sulfur]), RecipeType::sulfur},
		{to_lower(RecipeNames[RecipeType::battery]), RecipeType::battery},
		{to_lower(RecipeNames[RecipeType::engine_unit]), RecipeType::engine_unit},
		{to_lower(RecipeNames[RecipeType::electric_engine_unit]), RecipeType::electric_engine_unit},
		{to_lower(RecipeNames[RecipeType::explosives]), RecipeType::explosives},
		{to_lower(RecipeNames[RecipeType::uranium_processing]), RecipeType::uranium_processing},
		{to_lower(RecipeNames[RecipeType::flying_robot_frame]), RecipeType::flying_robot_frame},
		{to_lower(RecipeNames[RecipeType::satellite]), RecipeType::satellite},
		{to_lower(RecipeNames[RecipeType::rocket_control_unit]), RecipeType::rocket_control_unit},
		{to_lower(RecipeNames[RecipeType::low_density_structure]), RecipeType::low_density_structure},
		{to_lower(RecipeNames[RecipeType::rocket_fuel]), RecipeType::rocket_fuel},
		{to_lower(RecipeNames[RecipeType::nuclear_fuel]), RecipeType::nuclear_fuel},
		{to_lower(RecipeNames[RecipeType::uranium_fuel_cell]), RecipeType::uranium_fuel_cell},
		{to_lower(RecipeNames[RecipeType::nuclear_fuel_reprocessing]), RecipeType::nuclear_fuel_reprocessing},
		{to_lower(RecipeNames[RecipeType::kovarex_enrichment_process]), RecipeType::kovarex_enrichment_process},
	};


	static RecipeType MapStringToRecipeType(const string str);
	static RecipeType MapStringToRecipeType(const wxString str);
	static bool MapStringToRecipeType(const string str, RecipeType& type);
	static bool MapStringToRecipeType(const wxString str, RecipeType& type);
};

extern vector<Recipe> Recipes;


