#pragma once
#include <string>
#include <vector>
#include <map>

#include <wx/string.h>

#include "Shared functions/StringFunctions.h"

using std::string;
using std::vector;
using std::map;

/// <summary>
/// Simple container for holding a TechnologyType, 
/// provides methods translating to an from a string
/// </summary>
struct Technology
{
	enum TechnologyType
	{
		automation,
		automation_2,
		automation_3,
		electronics,
		fast_inserter,
		advanced_electronics,
		advanced_electronics_2,
		circuit_network,
		explosives,
		logistics,
		logistics_2,
		logistics_3,
		optics,
		laser,
		solar_energy,
		gun_turret,
		laser_turret,
		stone_wall,
		gate,
		engine,
		electric_engine,
		lubricant,
		battery,
		landfill,
		braking_force_1,
		braking_force_2,
		braking_force_3,
		braking_force_4,
		braking_force_5,
		braking_force_6,
		braking_force_7,
		chemical_science_pack,
		logistic_science_pack,
		military_science_pack,
		production_science_pack,
		space_science_pack,
		steel_processing,
		utility_science_pack,
		advanced_material_processing,
		steel_axe,
		advanced_material_processing_2,
		concrete,
		electric_energy_accumulators,
		electric_energy_distribution_1,
		electric_energy_distribution_2,
		railway,
		fluid_wagon,
		automated_rail_transportation,
		rail_signals,
		robotics,
		construction_robotics,
		logistic_robotics,
		logistic_system,
		personal_roboport_equipment,
		personal_roboport_mk2_equipment,
		worker_robots_speed_1,
		worker_robots_speed_2,
		worker_robots_speed_3,
		worker_robots_speed_4,
		mining_productivity_1,
		mining_productivity_2,
		mining_productivity_3,
		mining_productivity_4,
		worker_robots_speed_5,
		worker_robots_speed_6,
		worker_robots_storage_1,
		worker_robots_storage_2,
		worker_robots_storage_3,
		toolbelt,
		research_speed_1,
		research_speed_2,
		research_speed_3,
		research_speed_4,
		research_speed_5,
		research_speed_6,
		stack_inserter,
		inserter_capacity_bonus_1,
		inserter_capacity_bonus_2,
		inserter_capacity_bonus_3,
		inserter_capacity_bonus_4,
		inserter_capacity_bonus_5,
		inserter_capacity_bonus_6,
		inserter_capacity_bonus_7,
		oil_processing,
		fluid_handling,
		advanced_oil_processing,
		coal_liquefaction,
		sulfur_processing,
		plastics,
		artillery,
		spidertron,
		military,
		atomic_bomb,
		military_2,
		uranium_ammo,
		military_3,
		military_4,
		automobilism,
		flammables,
		flamethrower,
		tank,
		land_mine,
		rocketry,
		explosive_rocketry,
		energy_weapons_damage_1,
		refined_flammables_1,
		stronger_explosives_1,
		weapon_shooting_speed_1,
		artillery_shell_range_1,
		artillery_shell_speed_1,
		physical_projectile_damage_1,
		energy_weapons_damage_2,
		physical_projectile_damage_2,
		refined_flammables_2,
		stronger_explosives_2,
		weapon_shooting_speed_2,
		energy_weapons_damage_3,
		physical_projectile_damage_3,
		refined_flammables_3,
		stronger_explosives_3,
		weapon_shooting_speed_3,
		energy_weapons_damage_4,
		physical_projectile_damage_4,
		refined_flammables_4,
		stronger_explosives_4,
		weapon_shooting_speed_4,
		energy_weapons_damage_5,
		physical_projectile_damage_5,
		refined_flammables_5,
		stronger_explosives_5,
		weapon_shooting_speed_5,
		energy_weapons_damage_6,
		energy_weapons_damage_7,
		physical_projectile_damage_6,
		physical_projectile_damage_7,
		refined_flammables_6,
		refined_flammables_7,
		stronger_explosives_6,
		stronger_explosives_7,
		weapon_shooting_speed_6,
		laser_shooting_speed_1,
		laser_shooting_speed_2,
		laser_shooting_speed_3,
		laser_shooting_speed_4,
		laser_shooting_speed_5,
		laser_shooting_speed_6,
		laser_shooting_speed_7,
		defender,
		distractor,
		destroyer,
		follower_robot_count_1,
		follower_robot_count_2,
		follower_robot_count_3,
		follower_robot_count_4,
		follower_robot_count_5,
		follower_robot_count_6,
		follower_robot_count_7,
		kovarex_enrichment_process,
		nuclear_fuel_reprocessing,
		nuclear_power,
		uranium_processing,
		heavy_armor,
		modular_armor,
		power_armor,
		power_armor_mk2,
		energy_shield_equipment,
		energy_shield_mk2_equipment,
		night_vision_equipment,
		belt_immunity_equipment,
		exoskeleton_equipment,
		battery_equipment,
		battery_mk2_equipment,
		solar_panel_equipment,
		fusion_reactor_equipment,
		personal_laser_defense_equipment,
		discharge_defense_equipment,
		modules,
		speed_module,
		speed_module_2,
		speed_module_3,
		productivity_module,
		productivity_module_2,
		productivity_module_3,
		effectivity_module,
		effectivity_module_2,
		effectivity_module_3,
		effect_transmission,
		low_density_structure,
		rocket_control_unit,
		rocket_fuel,
		rocket_silo,
		cliff_explosives,
	} type;

	static inline const vector<string> TechnologyNames = {
		"Automation",
		"Automation 2",
		"Automation 3",
		"Electronics",
		"Fast inserter",
		"Advanced electronics",
		"Advanced electronics 2",
		"Circuit network",
		"Explosives",
		"Logistics",
		"Logistics 2",
		"Logistics 3",
		"Optics",
		"Laser",
		"Solar energy",
		"Gun turret",
		"Laser turret",
		"Stone wall",
		"Gate",
		"Engine",
		"Electric engine",
		"Lubricant",
		"Battery",
		"Landfill",
		"Braking force 1",
		"Braking force 2",
		"Braking force 3",
		"Braking force 4",
		"Braking force 5",
		"Braking force 6",
		"Braking force 7",
		"Chemical science pack",
		"Logistic science pack",
		"Military science pack",
		"Production science pack",
		"Space science pack",
		"Steel processing",
		"Utility science pack",
		"Advanced material processing",
		"Steel axe",
		"Advanced material processing 2",
		"Concrete",
		"Electric energy accumulators",
		"Electric energy distribution 1",
		"Electric energy distribution 2",
		"Railway",
		"Fluid wagon",
		"Automated rail transportation",
		"Rail signals",
		"Robotics",
		"Construction robotics",
		"Logistic robotics",
		"Logistic system",
		"Personal roboport",
		"Personal roboport MK2",
		"Worker robot speed 1",
		"Worker robot speed 2",
		"Worker robot speed 3",
		"Worker robot speed 4",
		"Mining productivity 1",
		"Mining productivity 2",
		"Mining productivity 3",
		"Mining productivity",
		"Worker robot speed 5",
		"Worker robot speed",
		"Worker robot cargo size 1",
		"Worker robot cargo size 2",
		"Worker robot cargo size 3",
		"Toolbelt",
		"Lab research speed 1",
		"Lab research speed 2",
		"Lab research speed 3",
		"Lab research speed 4",
		"Lab research speed 5",
		"Lab research speed 6",
		"Stack inserter",
		"Inserter capacity bonus 1",
		"Inserter capacity bonus 2",
		"Inserter capacity bonus 3",
		"Inserter capacity bonus 4",
		"Inserter capacity bonus 5",
		"Inserter capacity bonus 6",
		"Inserter capacity bonus 7",
		"Oil processing",
		"Fluid handling",
		"Advanced oil processing",
		"Coal liquefaction",
		"Sulfur processing",
		"Plastics",
		"Artillery",
		"Spidertron",
		"Military",
		"Atomic bomb",
		"Military 2",
		"Uranium ammo",
		"Military 3",
		"Military 4",
		"Automobilism",
		"Flammables",
		"Flamethrower",
		"Tank",
		"Land mines",
		"Rocketry",
		"Explosive rocketry",
		"Energy weapons damage 1",
		"Refined flammables 1",
		"Stronger explosives 1",
		"Weapon shooting speed 1",
		"Artillery shell range",
		"Artillery shell shooting speed",
		"Physical projectile damage 1",
		"Energy weapons damage 2",
		"Physical projectile damage 2",
		"Refined flammables 2",
		"Stronger explosives 2",
		"Weapon shooting speed 2",
		"Energy weapons damage 3",
		"Physical projectile damage 3",
		"Refined flammables 3",
		"Stronger explosives 3",
		"Weapon shooting speed 3",
		"Energy weapons damage 4",
		"Physical projectile damage 4",
		"Refined flammables 4",
		"Stronger explosives 4",
		"Weapon shooting speed 4",
		"Energy weapons damage 5",
		"Physical projectile damage 5",
		"Refined flammables 5",
		"Stronger explosives 5",
		"Weapon shooting speed 5",
		"Energy weapons damage 6",
		"Energy weapons damage",
		"Physical projectile damage 6",
		"Physical projectile damage",
		"Refined flammables 6",
		"Refined flammables",
		"Stronger explosives 6",
		"Stronger explosives",
		"Weapon shooting speed 6",
		"Laser shooting speed 1",
		"Laser shooting speed 2",
		"Laser shooting speed 3",
		"Laser shooting speed 4",
		"Laser shooting speed 5",
		"Laser shooting speed 6",
		"Laser shooting speed 7",
		"Defender",
		"Distractor",
		"Destroyer",
		"Follower robot count 1",
		"Follower robot count 2",
		"Follower robot count 3",
		"Follower robot count 4",
		"Follower robot count 5",
		"Follower robot count 6",
		"Follower robot count",
		"Kovarex enrichment process",
		"Nuclear fuel reprocessing",
		"Nuclear power",
		"Uranium processing",
		"Heavy armor",
		"Modular armor",
		"Power armor",
		"Power armor MK2",
		"Energy shield equipment",
		"Energy shield MK2 equipment",
		"Nightvision equipment",
		"Belt immunity equipment",
		"Exoskeleton equipment",
		"Personal battery",
		"Personal battery MK2",
		"Portable solar panel",
		"Portable fusion reactor",
		"Personal laser defense",
		"Discharge defense",
		"Modules",
		"Speed module",
		"Speed module 2",
		"Speed module 3",
		"Productivity module",
		"Productivity module 2",
		"Productivity module 3",
		"Efficiency module",
		"Efficiency module 2",
		"Efficiency module 3",
		"Effect transmission",
		"Low density structure",
		"Rocket control unit",
		"Rocket fuel",
		"Rocket silo",
		"Cliff explosives",
	};

	static inline const vector<string> TechnologyType_to_LuaName = {
		"automation",
		"automation-2",
		"automation-3",
		"electronics",
		"fast-inserter",
		"advanced-electronics",
		"advanced-electronics-2",
		"circuit-network",
		"explosives",
		"logistics",
		"logistics-2",
		"logistics-3",
		"optics",
		"laser",
		"solar-energy",
		"gun-turret",
		"laser-turret",
		"stone-wall",
		"gate",
		"engine",
		"electric-engine",
		"lubricant",
		"battery",
		"landfill",
		"braking-force-1",
		"braking-force-2",
		"braking-force-3",
		"braking-force-4",
		"braking-force-5",
		"braking-force-6",
		"braking-force-7",
		"chemical-science-pack",
		"logistic-science-pack",
		"military-science-pack",
		"production-science-pack",
		"space-science-pack",
		"steel-processing",
		"utility-science-pack",
		"advanced-material-processing",
		"steel-axe",
		"advanced-material-processing-2",
		"concrete",
		"electric-energy-accumulators",
		"electric-energy-distribution-1",
		"electric-energy-distribution-2",
		"railway",
		"fluid-wagon",
		"automated-rail-transportation",
		"rail-signals",
		"robotics",
		"construction-robotics",
		"logistic-robotics",
		"logistic-system",
		"personal-roboport-equipment",
		"personal-roboport-mk2-equipment",
		"worker-robots-speed-1",
		"worker-robots-speed-2",
		"worker-robots-speed-3",
		"worker-robots-speed-4",
		"mining-productivity-1",
		"mining-productivity-2",
		"mining-productivity-3",
		"mining-productivity-4",
		"worker-robots-speed-5",
		"worker-robots-speed-6",
		"worker-robots-storage-1",
		"worker-robots-storage-2",
		"worker-robots-storage-3",
		"toolbelt",
		"research-speed-1",
		"research-speed-2",
		"research-speed-3",
		"research-speed-4",
		"research-speed-5",
		"research-speed-6",
		"stack-inserter",
		"inserter-capacity-bonus-1",
		"inserter-capacity-bonus-2",
		"inserter-capacity-bonus-3",
		"inserter-capacity-bonus-4",
		"inserter-capacity-bonus-5",
		"inserter-capacity-bonus-6",
		"inserter-capacity-bonus-7",
		"oil-processing",
		"fluid-handling",
		"advanced-oil-processing",
		"coal-liquefaction",
		"sulfur-processing",
		"plastics",
		"artillery",
		"spidertron",
		"military",
		"atomic-bomb",
		"military-2",
		"uranium-ammo",
		"military-3",
		"military-4",
		"automobilism",
		"flammables",
		"flamethrower",
		"tank",
		"land-mine",
		"rocketry",
		"explosive-rocketry",
		"energy-weapons-damage-1",
		"refined-flammables-1",
		"stronger-explosives-1",
		"weapon-shooting-speed-1",
		"artillery-shell-range-1",
		"artillery-shell-speed-1",
		"physical-projectile-damage-1",
		"energy-weapons-damage-2",
		"physical-projectile-damage-2",
		"refined-flammables-2",
		"stronger-explosives-2",
		"weapon-shooting-speed-2",
		"energy-weapons-damage-3",
		"physical-projectile-damage-3",
		"refined-flammables-3",
		"stronger-explosives-3",
		"weapon-shooting-speed-3",
		"energy-weapons-damage-4",
		"physical-projectile-damage-4",
		"refined-flammables-4",
		"stronger-explosives-4",
		"weapon-shooting-speed-4",
		"energy-weapons-damage-5",
		"physical-projectile-damage-5",
		"refined-flammables-5",
		"stronger-explosives-5",
		"weapon-shooting-speed-5",
		"energy-weapons-damage-6",
		"energy-weapons-damage-7",
		"physical-projectile-damage-6",
		"physical-projectile-damage-7",
		"refined-flammables-6",
		"refined-flammables-7",
		"stronger-explosives-6",
		"stronger-explosives-7",
		"weapon-shooting-speed-6",
		"laser-shooting-speed-1",
		"laser-shooting-speed-2",
		"laser-shooting-speed-3",
		"laser-shooting-speed-4",
		"laser-shooting-speed-5",
		"laser-shooting-speed-6",
		"laser-shooting-speed-7",
		"defender",
		"distractor",
		"destroyer",
		"follower-robot-count-1",
		"follower-robot-count-2",
		"follower-robot-count-3",
		"follower-robot-count-4",
		"follower-robot-count-5",
		"follower-robot-count-6",
		"follower-robot-count-7",
		"kovarex-enrichment-process",
		"nuclear-fuel-reprocessing",
		"nuclear-power",
		"uranium-processing",
		"heavy-armor",
		"modular-armor",
		"power-armor",
		"power-armor-mk2",
		"energy-shield-equipment",
		"energy-shield-mk2-equipment",
		"night-vision-equipment",
		"belt-immunity-equipment",
		"exoskeleton-equipment",
		"battery-equipment",
		"battery-mk2-equipment",
		"solar-panel-equipment",
		"fusion-reactor-equipment",
		"personal-laser-defense-equipment",
		"discharge-defense-equipment",
		"modules",
		"speed-module",
		"speed-module-2",
		"speed-module-3",
		"productivity-module",
		"productivity-module-2",
		"productivity-module-3",
		"effectivity-module",
		"effectivity-module-2",
		"effectivity-module-3",
		"effect-transmission",
		"low-density-structure",
		"rocket-control-unit",
		"rocket-fuel",
		"rocket-silo",
		"cliff-explosives",
	};

	static inline const map<string, TechnologyType> map_TechnologyName_to_TechnologyType = {
		{TechnologyNames[automation], automation},
		{TechnologyNames[automation_2], automation_2},
		{TechnologyNames[automation_3], automation_3},
		{TechnologyNames[electronics], electronics},
		{TechnologyNames[fast_inserter], fast_inserter},
		{TechnologyNames[advanced_electronics], advanced_electronics},
		{TechnologyNames[advanced_electronics_2], advanced_electronics_2},
		{TechnologyNames[circuit_network], circuit_network},
		{TechnologyNames[explosives], explosives},
		{TechnologyNames[logistics], logistics},
		{TechnologyNames[logistics_2], logistics_2},
		{TechnologyNames[logistics_3], logistics_3},
		{TechnologyNames[optics], optics},
		{TechnologyNames[laser], laser},
		{TechnologyNames[solar_energy], solar_energy},
		{TechnologyNames[gun_turret], gun_turret},
		{TechnologyNames[laser_turret], laser_turret},
		{TechnologyNames[stone_wall], stone_wall},
		{TechnologyNames[gate], gate},
		{TechnologyNames[engine], engine},
		{TechnologyNames[electric_engine], electric_engine},
		{TechnologyNames[lubricant], lubricant},
		{TechnologyNames[battery], battery},
		{TechnologyNames[landfill], landfill},
		{TechnologyNames[braking_force_1], braking_force_1},
		{TechnologyNames[braking_force_2], braking_force_2},
		{TechnologyNames[braking_force_3], braking_force_3},
		{TechnologyNames[braking_force_4], braking_force_4},
		{TechnologyNames[braking_force_5], braking_force_5},
		{TechnologyNames[braking_force_6], braking_force_6},
		{TechnologyNames[braking_force_7], braking_force_7},
		{TechnologyNames[chemical_science_pack], chemical_science_pack},
		{TechnologyNames[logistic_science_pack], logistic_science_pack},
		{TechnologyNames[military_science_pack], military_science_pack},
		{TechnologyNames[production_science_pack], production_science_pack},
		{TechnologyNames[space_science_pack], space_science_pack},
		{TechnologyNames[steel_processing], steel_processing},
		{TechnologyNames[utility_science_pack], utility_science_pack},
		{TechnologyNames[advanced_material_processing], advanced_material_processing},
		{TechnologyNames[steel_axe], steel_axe},
		{TechnologyNames[advanced_material_processing_2], advanced_material_processing_2},
		{TechnologyNames[concrete], concrete},
		{TechnologyNames[electric_energy_accumulators], electric_energy_accumulators},
		{TechnologyNames[electric_energy_distribution_1], electric_energy_distribution_1},
		{TechnologyNames[electric_energy_distribution_2], electric_energy_distribution_2},
		{TechnologyNames[railway], railway},
		{TechnologyNames[fluid_wagon], fluid_wagon},
		{TechnologyNames[automated_rail_transportation], automated_rail_transportation},
		{TechnologyNames[rail_signals], rail_signals},
		{TechnologyNames[robotics], robotics},
		{TechnologyNames[construction_robotics], construction_robotics},
		{TechnologyNames[logistic_robotics], logistic_robotics},
		{TechnologyNames[logistic_system], logistic_system},
		{TechnologyNames[personal_roboport_equipment], personal_roboport_equipment},
		{TechnologyNames[personal_roboport_mk2_equipment], personal_roboport_mk2_equipment},
		{TechnologyNames[worker_robots_speed_1], worker_robots_speed_1},
		{TechnologyNames[worker_robots_speed_2], worker_robots_speed_2},
		{TechnologyNames[worker_robots_speed_3], worker_robots_speed_3},
		{TechnologyNames[worker_robots_speed_4], worker_robots_speed_4},
		{TechnologyNames[mining_productivity_1], mining_productivity_1},
		{TechnologyNames[mining_productivity_2], mining_productivity_2},
		{TechnologyNames[mining_productivity_3], mining_productivity_3},
		{TechnologyNames[mining_productivity_4], mining_productivity_4},
		{TechnologyNames[worker_robots_speed_5], worker_robots_speed_5},
		{TechnologyNames[worker_robots_speed_6], worker_robots_speed_6},
		{TechnologyNames[worker_robots_storage_1], worker_robots_storage_1},
		{TechnologyNames[worker_robots_storage_2], worker_robots_storage_2},
		{TechnologyNames[worker_robots_storage_3], worker_robots_storage_3},
		{TechnologyNames[toolbelt], toolbelt},
		{TechnologyNames[research_speed_1], research_speed_1},
		{TechnologyNames[research_speed_2], research_speed_2},
		{TechnologyNames[research_speed_3], research_speed_3},
		{TechnologyNames[research_speed_4], research_speed_4},
		{TechnologyNames[research_speed_5], research_speed_5},
		{TechnologyNames[research_speed_6], research_speed_6},
		{TechnologyNames[stack_inserter], stack_inserter},
		{TechnologyNames[inserter_capacity_bonus_1], inserter_capacity_bonus_1},
		{TechnologyNames[inserter_capacity_bonus_2], inserter_capacity_bonus_2},
		{TechnologyNames[inserter_capacity_bonus_3], inserter_capacity_bonus_3},
		{TechnologyNames[inserter_capacity_bonus_4], inserter_capacity_bonus_4},
		{TechnologyNames[inserter_capacity_bonus_5], inserter_capacity_bonus_5},
		{TechnologyNames[inserter_capacity_bonus_6], inserter_capacity_bonus_6},
		{TechnologyNames[inserter_capacity_bonus_7], inserter_capacity_bonus_7},
		{TechnologyNames[oil_processing], oil_processing},
		{TechnologyNames[fluid_handling], fluid_handling},
		{TechnologyNames[advanced_oil_processing], advanced_oil_processing},
		{TechnologyNames[coal_liquefaction], coal_liquefaction},
		{TechnologyNames[sulfur_processing], sulfur_processing},
		{TechnologyNames[plastics], plastics},
		{TechnologyNames[artillery], artillery},
		{TechnologyNames[spidertron], spidertron},
		{TechnologyNames[military], military},
		{TechnologyNames[atomic_bomb], atomic_bomb},
		{TechnologyNames[military_2], military_2},
		{TechnologyNames[uranium_ammo], uranium_ammo},
		{TechnologyNames[military_3], military_3},
		{TechnologyNames[military_4], military_4},
		{TechnologyNames[automobilism], automobilism},
		{TechnologyNames[flammables], flammables},
		{TechnologyNames[flamethrower], flamethrower},
		{TechnologyNames[tank], tank},
		{TechnologyNames[land_mine], land_mine},
		{TechnologyNames[rocketry], rocketry},
		{TechnologyNames[explosive_rocketry], explosive_rocketry},
		{TechnologyNames[energy_weapons_damage_1], energy_weapons_damage_1},
		{TechnologyNames[refined_flammables_1], refined_flammables_1},
		{TechnologyNames[stronger_explosives_1], stronger_explosives_1},
		{TechnologyNames[weapon_shooting_speed_1], weapon_shooting_speed_1},
		{TechnologyNames[artillery_shell_range_1], artillery_shell_range_1},
		{TechnologyNames[artillery_shell_speed_1], artillery_shell_speed_1},
		{TechnologyNames[physical_projectile_damage_1], physical_projectile_damage_1},
		{TechnologyNames[energy_weapons_damage_2], energy_weapons_damage_2},
		{TechnologyNames[physical_projectile_damage_2], physical_projectile_damage_2},
		{TechnologyNames[refined_flammables_2], refined_flammables_2},
		{TechnologyNames[stronger_explosives_2], stronger_explosives_2},
		{TechnologyNames[weapon_shooting_speed_2], weapon_shooting_speed_2},
		{TechnologyNames[energy_weapons_damage_3], energy_weapons_damage_3},
		{TechnologyNames[physical_projectile_damage_3], physical_projectile_damage_3},
		{TechnologyNames[refined_flammables_3], refined_flammables_3},
		{TechnologyNames[stronger_explosives_3], stronger_explosives_3},
		{TechnologyNames[weapon_shooting_speed_3], weapon_shooting_speed_3},
		{TechnologyNames[energy_weapons_damage_4], energy_weapons_damage_4},
		{TechnologyNames[physical_projectile_damage_4], physical_projectile_damage_4},
		{TechnologyNames[refined_flammables_4], refined_flammables_4},
		{TechnologyNames[stronger_explosives_4], stronger_explosives_4},
		{TechnologyNames[weapon_shooting_speed_4], weapon_shooting_speed_4},
		{TechnologyNames[energy_weapons_damage_5], energy_weapons_damage_5},
		{TechnologyNames[physical_projectile_damage_5], physical_projectile_damage_5},
		{TechnologyNames[refined_flammables_5], refined_flammables_5},
		{TechnologyNames[stronger_explosives_5], stronger_explosives_5},
		{TechnologyNames[weapon_shooting_speed_5], weapon_shooting_speed_5},
		{TechnologyNames[energy_weapons_damage_6], energy_weapons_damage_6},
		{TechnologyNames[energy_weapons_damage_7], energy_weapons_damage_7},
		{TechnologyNames[physical_projectile_damage_6], physical_projectile_damage_6},
		{TechnologyNames[physical_projectile_damage_7], physical_projectile_damage_7},
		{TechnologyNames[refined_flammables_6], refined_flammables_6},
		{TechnologyNames[refined_flammables_7], refined_flammables_7},
		{TechnologyNames[stronger_explosives_6], stronger_explosives_6},
		{TechnologyNames[stronger_explosives_7], stronger_explosives_7},
		{TechnologyNames[weapon_shooting_speed_6], weapon_shooting_speed_6},
		{TechnologyNames[laser_shooting_speed_1], laser_shooting_speed_1},
		{TechnologyNames[laser_shooting_speed_2], laser_shooting_speed_2},
		{TechnologyNames[laser_shooting_speed_3], laser_shooting_speed_3},
		{TechnologyNames[laser_shooting_speed_4], laser_shooting_speed_4},
		{TechnologyNames[laser_shooting_speed_5], laser_shooting_speed_5},
		{TechnologyNames[laser_shooting_speed_6], laser_shooting_speed_6},
		{TechnologyNames[laser_shooting_speed_7], laser_shooting_speed_7},
		{TechnologyNames[defender], defender},
		{TechnologyNames[distractor], distractor},
		{TechnologyNames[destroyer], destroyer},
		{TechnologyNames[follower_robot_count_1], follower_robot_count_1},
		{TechnologyNames[follower_robot_count_2], follower_robot_count_2},
		{TechnologyNames[follower_robot_count_3], follower_robot_count_3},
		{TechnologyNames[follower_robot_count_4], follower_robot_count_4},
		{TechnologyNames[follower_robot_count_5], follower_robot_count_5},
		{TechnologyNames[follower_robot_count_6], follower_robot_count_6},
		{TechnologyNames[follower_robot_count_7], follower_robot_count_7},
		{TechnologyNames[kovarex_enrichment_process], kovarex_enrichment_process},
		{TechnologyNames[nuclear_fuel_reprocessing], nuclear_fuel_reprocessing},
		{TechnologyNames[nuclear_power], nuclear_power},
		{TechnologyNames[uranium_processing], uranium_processing},
		{TechnologyNames[heavy_armor], heavy_armor},
		{TechnologyNames[modular_armor], modular_armor},
		{TechnologyNames[power_armor], power_armor},
		{TechnologyNames[power_armor_mk2], power_armor_mk2},
		{TechnologyNames[energy_shield_equipment], energy_shield_equipment},
		{TechnologyNames[energy_shield_mk2_equipment], energy_shield_mk2_equipment},
		{TechnologyNames[night_vision_equipment], night_vision_equipment},
		{TechnologyNames[belt_immunity_equipment], belt_immunity_equipment},
		{TechnologyNames[exoskeleton_equipment], exoskeleton_equipment},
		{TechnologyNames[battery_equipment], battery_equipment},
		{TechnologyNames[battery_mk2_equipment], battery_mk2_equipment},
		{TechnologyNames[solar_panel_equipment], solar_panel_equipment},
		{TechnologyNames[fusion_reactor_equipment], fusion_reactor_equipment},
		{TechnologyNames[personal_laser_defense_equipment], personal_laser_defense_equipment},
		{TechnologyNames[discharge_defense_equipment], discharge_defense_equipment},
		{TechnologyNames[modules], modules},
		{TechnologyNames[speed_module], speed_module},
		{TechnologyNames[speed_module_2], speed_module_2},
		{TechnologyNames[speed_module_3], speed_module_3},
		{TechnologyNames[productivity_module], productivity_module},
		{TechnologyNames[productivity_module_2], productivity_module_2},
		{TechnologyNames[productivity_module_3], productivity_module_3},
		{TechnologyNames[effectivity_module], effectivity_module},
		{TechnologyNames[effectivity_module_2], effectivity_module_2},
		{TechnologyNames[effectivity_module_3], effectivity_module_3},
		{TechnologyNames[effect_transmission], effect_transmission},
		{TechnologyNames[low_density_structure], low_density_structure},
		{TechnologyNames[rocket_control_unit], rocket_control_unit},
		{TechnologyNames[rocket_fuel], rocket_fuel},
		{TechnologyNames[rocket_silo], rocket_silo},
		{TechnologyNames[cliff_explosives], cliff_explosives},


		{to_lower(TechnologyNames[automation]), automation},
		{to_lower(TechnologyNames[automation_2]), automation_2},
		{to_lower(TechnologyNames[automation_3]), automation_3},
		{to_lower(TechnologyNames[electronics]), electronics},
		{to_lower(TechnologyNames[fast_inserter]), fast_inserter},
		{to_lower(TechnologyNames[advanced_electronics]), advanced_electronics},
		{to_lower(TechnologyNames[advanced_electronics_2]), advanced_electronics_2},
		{to_lower(TechnologyNames[circuit_network]), circuit_network},
		{to_lower(TechnologyNames[explosives]), explosives},
		{to_lower(TechnologyNames[logistics]), logistics},
		{to_lower(TechnologyNames[logistics_2]), logistics_2},
		{to_lower(TechnologyNames[logistics_3]), logistics_3},
		{to_lower(TechnologyNames[optics]), optics},
		{to_lower(TechnologyNames[laser]), laser},
		{to_lower(TechnologyNames[solar_energy]), solar_energy},
		{to_lower(TechnologyNames[gun_turret]), gun_turret},
		{to_lower(TechnologyNames[laser_turret]), laser_turret},
		{to_lower(TechnologyNames[stone_wall]), stone_wall},
		{to_lower(TechnologyNames[gate]), gate},
		{to_lower(TechnologyNames[engine]), engine},
		{to_lower(TechnologyNames[electric_engine]), electric_engine},
		{to_lower(TechnologyNames[lubricant]), lubricant},
		{to_lower(TechnologyNames[battery]), battery},
		{to_lower(TechnologyNames[landfill]), landfill},
		{to_lower(TechnologyNames[braking_force_1]), braking_force_1},
		{to_lower(TechnologyNames[braking_force_2]), braking_force_2},
		{to_lower(TechnologyNames[braking_force_3]), braking_force_3},
		{to_lower(TechnologyNames[braking_force_4]), braking_force_4},
		{to_lower(TechnologyNames[braking_force_5]), braking_force_5},
		{to_lower(TechnologyNames[braking_force_6]), braking_force_6},
		{to_lower(TechnologyNames[braking_force_7]), braking_force_7},
		{to_lower(TechnologyNames[chemical_science_pack]), chemical_science_pack},
		{to_lower(TechnologyNames[logistic_science_pack]), logistic_science_pack},
		{to_lower(TechnologyNames[military_science_pack]), military_science_pack},
		{to_lower(TechnologyNames[production_science_pack]), production_science_pack},
		{to_lower(TechnologyNames[space_science_pack]), space_science_pack},
		{to_lower(TechnologyNames[steel_processing]), steel_processing},
		{to_lower(TechnologyNames[utility_science_pack]), utility_science_pack},
		{to_lower(TechnologyNames[advanced_material_processing]), advanced_material_processing},
		{to_lower(TechnologyNames[steel_axe]), steel_axe},
		{to_lower(TechnologyNames[advanced_material_processing_2]), advanced_material_processing_2},
		{to_lower(TechnologyNames[concrete]), concrete},
		{to_lower(TechnologyNames[electric_energy_accumulators]), electric_energy_accumulators},
		{to_lower(TechnologyNames[electric_energy_distribution_1]), electric_energy_distribution_1},
		{to_lower(TechnologyNames[electric_energy_distribution_2]), electric_energy_distribution_2},
		{to_lower(TechnologyNames[railway]), railway},
		{to_lower(TechnologyNames[fluid_wagon]), fluid_wagon},
		{to_lower(TechnologyNames[automated_rail_transportation]), automated_rail_transportation},
		{to_lower(TechnologyNames[rail_signals]), rail_signals},
		{to_lower(TechnologyNames[robotics]), robotics},
		{to_lower(TechnologyNames[construction_robotics]), construction_robotics},
		{to_lower(TechnologyNames[logistic_robotics]), logistic_robotics},
		{to_lower(TechnologyNames[logistic_system]), logistic_system},
		{to_lower(TechnologyNames[personal_roboport_equipment]), personal_roboport_equipment},
		{to_lower(TechnologyNames[personal_roboport_mk2_equipment]), personal_roboport_mk2_equipment},
		{to_lower(TechnologyNames[worker_robots_speed_1]), worker_robots_speed_1},
		{to_lower(TechnologyNames[worker_robots_speed_2]), worker_robots_speed_2},
		{to_lower(TechnologyNames[worker_robots_speed_3]), worker_robots_speed_3},
		{to_lower(TechnologyNames[worker_robots_speed_4]), worker_robots_speed_4},
		{to_lower(TechnologyNames[mining_productivity_1]), mining_productivity_1},
		{to_lower(TechnologyNames[mining_productivity_2]), mining_productivity_2},
		{to_lower(TechnologyNames[mining_productivity_3]), mining_productivity_3},
		{to_lower(TechnologyNames[mining_productivity_4]), mining_productivity_4},
		{to_lower(TechnologyNames[worker_robots_speed_5]), worker_robots_speed_5},
		{to_lower(TechnologyNames[worker_robots_speed_6]), worker_robots_speed_6},
		{to_lower(TechnologyNames[worker_robots_storage_1]), worker_robots_storage_1},
		{to_lower(TechnologyNames[worker_robots_storage_2]), worker_robots_storage_2},
		{to_lower(TechnologyNames[worker_robots_storage_3]), worker_robots_storage_3},
		{to_lower(TechnologyNames[toolbelt]), toolbelt},
		{to_lower(TechnologyNames[research_speed_1]), research_speed_1},
		{to_lower(TechnologyNames[research_speed_2]), research_speed_2},
		{to_lower(TechnologyNames[research_speed_3]), research_speed_3},
		{to_lower(TechnologyNames[research_speed_4]), research_speed_4},
		{to_lower(TechnologyNames[research_speed_5]), research_speed_5},
		{to_lower(TechnologyNames[research_speed_6]), research_speed_6},
		{to_lower(TechnologyNames[stack_inserter]), stack_inserter},
		{to_lower(TechnologyNames[inserter_capacity_bonus_1]), inserter_capacity_bonus_1},
		{to_lower(TechnologyNames[inserter_capacity_bonus_2]), inserter_capacity_bonus_2},
		{to_lower(TechnologyNames[inserter_capacity_bonus_3]), inserter_capacity_bonus_3},
		{to_lower(TechnologyNames[inserter_capacity_bonus_4]), inserter_capacity_bonus_4},
		{to_lower(TechnologyNames[inserter_capacity_bonus_5]), inserter_capacity_bonus_5},
		{to_lower(TechnologyNames[inserter_capacity_bonus_6]), inserter_capacity_bonus_6},
		{to_lower(TechnologyNames[inserter_capacity_bonus_7]), inserter_capacity_bonus_7},
		{to_lower(TechnologyNames[oil_processing]), oil_processing},
		{to_lower(TechnologyNames[fluid_handling]), fluid_handling},
		{to_lower(TechnologyNames[advanced_oil_processing]), advanced_oil_processing},
		{to_lower(TechnologyNames[coal_liquefaction]), coal_liquefaction},
		{to_lower(TechnologyNames[sulfur_processing]), sulfur_processing},
		{to_lower(TechnologyNames[plastics]), plastics},
		{to_lower(TechnologyNames[artillery]), artillery},
		{to_lower(TechnologyNames[spidertron]), spidertron},
		{to_lower(TechnologyNames[military]), military},
		{to_lower(TechnologyNames[atomic_bomb]), atomic_bomb},
		{to_lower(TechnologyNames[military_2]), military_2},
		{to_lower(TechnologyNames[uranium_ammo]), uranium_ammo},
		{to_lower(TechnologyNames[military_3]), military_3},
		{to_lower(TechnologyNames[military_4]), military_4},
		{to_lower(TechnologyNames[automobilism]), automobilism},
		{to_lower(TechnologyNames[flammables]), flammables},
		{to_lower(TechnologyNames[flamethrower]), flamethrower},
		{to_lower(TechnologyNames[tank]), tank},
		{to_lower(TechnologyNames[land_mine]), land_mine},
		{to_lower(TechnologyNames[rocketry]), rocketry},
		{to_lower(TechnologyNames[explosive_rocketry]), explosive_rocketry},
		{to_lower(TechnologyNames[energy_weapons_damage_1]), energy_weapons_damage_1},
		{to_lower(TechnologyNames[refined_flammables_1]), refined_flammables_1},
		{to_lower(TechnologyNames[stronger_explosives_1]), stronger_explosives_1},
		{to_lower(TechnologyNames[weapon_shooting_speed_1]), weapon_shooting_speed_1},
		{to_lower(TechnologyNames[artillery_shell_range_1]), artillery_shell_range_1},
		{to_lower(TechnologyNames[artillery_shell_speed_1]), artillery_shell_speed_1},
		{to_lower(TechnologyNames[physical_projectile_damage_1]), physical_projectile_damage_1},
		{to_lower(TechnologyNames[energy_weapons_damage_2]), energy_weapons_damage_2},
		{to_lower(TechnologyNames[physical_projectile_damage_2]), physical_projectile_damage_2},
		{to_lower(TechnologyNames[refined_flammables_2]), refined_flammables_2},
		{to_lower(TechnologyNames[stronger_explosives_2]), stronger_explosives_2},
		{to_lower(TechnologyNames[weapon_shooting_speed_2]), weapon_shooting_speed_2},
		{to_lower(TechnologyNames[energy_weapons_damage_3]), energy_weapons_damage_3},
		{to_lower(TechnologyNames[physical_projectile_damage_3]), physical_projectile_damage_3},
		{to_lower(TechnologyNames[refined_flammables_3]), refined_flammables_3},
		{to_lower(TechnologyNames[stronger_explosives_3]), stronger_explosives_3},
		{to_lower(TechnologyNames[weapon_shooting_speed_3]), weapon_shooting_speed_3},
		{to_lower(TechnologyNames[energy_weapons_damage_4]), energy_weapons_damage_4},
		{to_lower(TechnologyNames[physical_projectile_damage_4]), physical_projectile_damage_4},
		{to_lower(TechnologyNames[refined_flammables_4]), refined_flammables_4},
		{to_lower(TechnologyNames[stronger_explosives_4]), stronger_explosives_4},
		{to_lower(TechnologyNames[weapon_shooting_speed_4]), weapon_shooting_speed_4},
		{to_lower(TechnologyNames[energy_weapons_damage_5]), energy_weapons_damage_5},
		{to_lower(TechnologyNames[physical_projectile_damage_5]), physical_projectile_damage_5},
		{to_lower(TechnologyNames[refined_flammables_5]), refined_flammables_5},
		{to_lower(TechnologyNames[stronger_explosives_5]), stronger_explosives_5},
		{to_lower(TechnologyNames[weapon_shooting_speed_5]), weapon_shooting_speed_5},
		{to_lower(TechnologyNames[energy_weapons_damage_6]), energy_weapons_damage_6},
		{to_lower(TechnologyNames[energy_weapons_damage_7]), energy_weapons_damage_7},
		{to_lower(TechnologyNames[physical_projectile_damage_6]), physical_projectile_damage_6},
		{to_lower(TechnologyNames[physical_projectile_damage_7]), physical_projectile_damage_7},
		{to_lower(TechnologyNames[refined_flammables_6]), refined_flammables_6},
		{to_lower(TechnologyNames[refined_flammables_7]), refined_flammables_7},
		{to_lower(TechnologyNames[stronger_explosives_6]), stronger_explosives_6},
		{to_lower(TechnologyNames[stronger_explosives_7]), stronger_explosives_7},
		{to_lower(TechnologyNames[weapon_shooting_speed_6]), weapon_shooting_speed_6},
		{to_lower(TechnologyNames[laser_shooting_speed_1]), laser_shooting_speed_1},
		{to_lower(TechnologyNames[laser_shooting_speed_2]), laser_shooting_speed_2},
		{to_lower(TechnologyNames[laser_shooting_speed_3]), laser_shooting_speed_3},
		{to_lower(TechnologyNames[laser_shooting_speed_4]), laser_shooting_speed_4},
		{to_lower(TechnologyNames[laser_shooting_speed_5]), laser_shooting_speed_5},
		{to_lower(TechnologyNames[laser_shooting_speed_6]), laser_shooting_speed_6},
		{to_lower(TechnologyNames[laser_shooting_speed_7]), laser_shooting_speed_7},
		{to_lower(TechnologyNames[defender]), defender},
		{to_lower(TechnologyNames[distractor]), distractor},
		{to_lower(TechnologyNames[destroyer]), destroyer},
		{to_lower(TechnologyNames[follower_robot_count_1]), follower_robot_count_1},
		{to_lower(TechnologyNames[follower_robot_count_2]), follower_robot_count_2},
		{to_lower(TechnologyNames[follower_robot_count_3]), follower_robot_count_3},
		{to_lower(TechnologyNames[follower_robot_count_4]), follower_robot_count_4},
		{to_lower(TechnologyNames[follower_robot_count_5]), follower_robot_count_5},
		{to_lower(TechnologyNames[follower_robot_count_6]), follower_robot_count_6},
		{to_lower(TechnologyNames[follower_robot_count_7]), follower_robot_count_7},
		{to_lower(TechnologyNames[kovarex_enrichment_process]), kovarex_enrichment_process},
		{to_lower(TechnologyNames[nuclear_fuel_reprocessing]), nuclear_fuel_reprocessing},
		{to_lower(TechnologyNames[nuclear_power]), nuclear_power},
		{to_lower(TechnologyNames[uranium_processing]), uranium_processing},
		{to_lower(TechnologyNames[heavy_armor]), heavy_armor},
		{to_lower(TechnologyNames[modular_armor]), modular_armor},
		{to_lower(TechnologyNames[power_armor]), power_armor},
		{to_lower(TechnologyNames[power_armor_mk2]), power_armor_mk2},
		{to_lower(TechnologyNames[energy_shield_equipment]), energy_shield_equipment},
		{to_lower(TechnologyNames[energy_shield_mk2_equipment]), energy_shield_mk2_equipment},
		{to_lower(TechnologyNames[night_vision_equipment]), night_vision_equipment},
		{to_lower(TechnologyNames[belt_immunity_equipment]), belt_immunity_equipment},
		{to_lower(TechnologyNames[exoskeleton_equipment]), exoskeleton_equipment},
		{to_lower(TechnologyNames[battery_equipment]), battery_equipment},
		{to_lower(TechnologyNames[battery_mk2_equipment]), battery_mk2_equipment},
		{to_lower(TechnologyNames[solar_panel_equipment]), solar_panel_equipment},
		{to_lower(TechnologyNames[fusion_reactor_equipment]), fusion_reactor_equipment},
		{to_lower(TechnologyNames[personal_laser_defense_equipment]), personal_laser_defense_equipment},
		{to_lower(TechnologyNames[discharge_defense_equipment]), discharge_defense_equipment},
		{to_lower(TechnologyNames[modules]), modules},
		{to_lower(TechnologyNames[speed_module]), speed_module},
		{to_lower(TechnologyNames[speed_module_2]), speed_module_2},
		{to_lower(TechnologyNames[speed_module_3]), speed_module_3},
		{to_lower(TechnologyNames[productivity_module]), productivity_module},
		{to_lower(TechnologyNames[productivity_module_2]), productivity_module_2},
		{to_lower(TechnologyNames[productivity_module_3]), productivity_module_3},
		{to_lower(TechnologyNames[effectivity_module]), effectivity_module},
		{to_lower(TechnologyNames[effectivity_module_2]), effectivity_module_2},
		{to_lower(TechnologyNames[effectivity_module_3]), effectivity_module_3},
		{to_lower(TechnologyNames[effect_transmission]), effect_transmission},
		{to_lower(TechnologyNames[low_density_structure]), low_density_structure},
		{to_lower(TechnologyNames[rocket_control_unit]), rocket_control_unit},
		{to_lower(TechnologyNames[rocket_fuel]), rocket_fuel},
		{to_lower(TechnologyNames[rocket_silo]), rocket_silo},
		{to_lower(TechnologyNames[cliff_explosives]), cliff_explosives},
	};

	string Name() const;
	string LuaName() const;

	// Finds the Technology matching or throws an error
	static Technology MapStringToTech(const string str);
	// Finds the Technology matching or throws an error
	static Technology MapStringToTech(const wxString str);
	// Finds the Technology matching and assigns it to tech. Returns whether an Technology was found
	static bool MapStringToTech(const string str, Technology& tech);
	// Finds the Technology matching and assigns it to tech. Returns whether an Technology was found
	static bool MapStringToTech(const wxString str, Technology& tech);
};

/*
* LUA script
game.write_file(file,"")

	--
	game.write_file(file, "\nenum TechnologyType\n{\n", true)
	for _, prototype in pairs(game.technology_prototypes) do
		game.write_file(file, string.format("\t%s,\n", prototype.name:gsub("-", "_")),true)
	end
	game.write_file(file, "};\n", true)--]]

	--
	game.write_file(file, "\nstatic inline const vector<string> TechnologyNames = {\n", true)
	for _, prototype in pairs(game.technology_prototypes) do
		game.write_file(file, string.format("\t\"", prototype.name),true)
		game.write_file(file, prototype.localised_name,true)
		game.write_file(file, string.format("\",\n", prototype.name),true)
	end
	game.write_file(file, "};\n", true) --]]

	--
	game.write_file(file, "\nstatic inline const vector<string> TechnologyType_to_LuaName{\n", true)
	for _, prototype in pairs(game.technology_prototypes) do
		game.write_file(file, string.format("\t\"%s\",\n", prototype.name),true)
	end
	game.write_file(file, "};\n", true) --]]

	--
	game.write_file(file, "\nstatic inline const map<string, TechnologyType> map_TechnologyName_to_TechnologyType = {\n", true)
	for _, prototype in pairs(game.technology_prototypes) do
		game.write_file(file, string.format("\t{TechnologyNames[%s], %s},\n", prototype.name:gsub("-", "_"), prototype.name:gsub("-", "_")),true)
	end

	for _, prototype in pairs(game.technology_prototypes) do
		game.write_file(file, string.format("\t{to_lower(TechnologyNames[%s]), %s},\n", prototype.name:gsub("-", "_"), prototype.name:gsub("-", "_")),true)
	end

	game.write_file(file, "};\n", true)--]]

*/
