#pragma once
#include <string>
#include <vector>
#include <map>

#include <wx/string.h>

#include "Shared functions/StringFunctions.h"

using std::string;
using std::vector;
using std::map;

/// <summary>
/// Simple container for holding a TechnologyType,
/// provides methods translating to an from a string
/// </summary>
struct Technology
{
	string Name() const;
	string LuaName() const;

	// Finds the Technology matching or throws an error
	static Technology MapStringToTech(const string str);
	// Finds the Technology matching or throws an error
	static Technology MapStringToTech(const wxString str);
	// Finds the Technology matching and assigns it to tech. Returns whether an Technology was found
	static bool MapStringToTech(const string str, Technology& tech);
	// Finds the Technology matching and assigns it to tech. Returns whether an Technology was found
	static bool MapStringToTech(const wxString str, Technology& tech);
	/*
	* LUA script
		helpers.write_file(file,"")

		--
		helpers.write_file(file, "\nenum TechnologyType\n{\n", true)
		for _, prototype in pairs(prototypes.technology) do
			helpers.write_file(file, string.format("\t%s,\n", prototype.name:gsub("-", "_")),true)
		end
		helpers.write_file(file, "} type;\n", true)

		--
		helpers.write_file(file, "\nstatic inline const vector<string> TechnologyNames = {\n", true)
		for _, prototype in pairs(prototypes.technology) do
			helpers.write_file(file, "\t\"",true)
			helpers.write_file(file, prototype.localised_name,true)
			helpers.write_file(file, "\",\n",true)
		end
		helpers.write_file(file, "};\n", true)

		--
		helpers.write_file(file, "\nstatic inline const vector<string> TechnologyType_to_LuaName{\n", true)
		for _, prototype in pairs(prototypes.technology) do
			helpers.write_file(file, string.format("\t\"%s\",\n", prototype.name),true)
		end
		helpers.write_file(file, "};\n", true)

		--
		helpers.write_file(file, "\nstatic inline const map<string, TechnologyType> map_TechnologyName_to_TechnologyType = {\n", true)
		for _, prototype in pairs(prototypes.technology) do
			local name = prototype.name:gsub("-", "_")
			helpers.write_file(file, string.format("\t{TechnologyNames[%s], %s},\n", name, name),true)
		end

		for _, prototype in pairs(prototypes.technology) do
			helpers.write_file(file, string.format("\t{to_lower(TechnologyNames[%s]), %s},\n", name, name),true)
		end

		helpers.write_file(file, "};\n", true)

	*/
	enum TechnologyType
	{
		advanced_circuit,
		advanced_combinators,
		advanced_material_processing,
		advanced_material_processing_2,
		advanced_oil_processing,
		artillery,
		artillery_shell_range_1,
		artillery_shell_speed_1,
		atomic_bomb,
		automated_rail_transportation,
		automation,
		automation_2,
		automation_3,
		automation_science_pack,
		automobilism,
		battery,
		battery_equipment,
		battery_mk2_equipment,
		belt_immunity_equipment,
		braking_force_1,
		braking_force_2,
		braking_force_3,
		braking_force_4,
		braking_force_5,
		braking_force_6,
		braking_force_7,
		bulk_inserter,
		chemical_science_pack,
		circuit_network,
		cliff_explosives,
		coal_liquefaction,
		concrete,
		construction_robotics,
		defender,
		destroyer,
		discharge_defense_equipment,
		distractor,
		effect_transmission,
		efficiency_module,
		efficiency_module_2,
		efficiency_module_3,
		electric_energy_accumulators,
		electric_energy_distribution_1,
		electric_energy_distribution_2,
		electric_engine,
		electric_mining_drill,
		electronics,
		energy_shield_equipment,
		energy_shield_mk2_equipment,
		engine,
		exoskeleton_equipment,
		explosive_rocketry,
		explosives,
		fast_inserter,
		fission_reactor_equipment,
		flamethrower,
		flammables,
		fluid_handling,
		fluid_wagon,
		follower_robot_count_1,
		follower_robot_count_2,
		follower_robot_count_3,
		follower_robot_count_4,
		follower_robot_count_5,
		gate,
		gun_turret,
		heavy_armor,
		inserter_capacity_bonus_1,
		inserter_capacity_bonus_2,
		inserter_capacity_bonus_3,
		inserter_capacity_bonus_4,
		inserter_capacity_bonus_5,
		inserter_capacity_bonus_6,
		inserter_capacity_bonus_7,
		kovarex_enrichment_process,
		lamp,
		land_mine,
		landfill,
		laser,
		laser_shooting_speed_1,
		laser_shooting_speed_2,
		laser_shooting_speed_3,
		laser_shooting_speed_4,
		laser_shooting_speed_5,
		laser_shooting_speed_6,
		laser_shooting_speed_7,
		laser_turret,
		laser_weapons_damage_1,
		laser_weapons_damage_2,
		laser_weapons_damage_3,
		laser_weapons_damage_4,
		laser_weapons_damage_5,
		laser_weapons_damage_6,
		laser_weapons_damage_7,
		logistic_robotics,
		logistic_science_pack,
		logistic_system,
		logistics,
		logistics_2,
		logistics_3,
		low_density_structure,
		lubricant,
		military,
		military_2,
		military_3,
		military_4,
		military_science_pack,
		mining_productivity_1,
		mining_productivity_2,
		mining_productivity_3,
		mining_productivity_4,
		modular_armor,
		modules,
		night_vision_equipment,
		nuclear_fuel_reprocessing,
		nuclear_power,
		oil_gathering,
		oil_processing,
		personal_laser_defense_equipment,
		personal_roboport_equipment,
		personal_roboport_mk2_equipment,
		physical_projectile_damage_1,
		physical_projectile_damage_2,
		physical_projectile_damage_3,
		physical_projectile_damage_4,
		physical_projectile_damage_5,
		physical_projectile_damage_6,
		physical_projectile_damage_7,
		plastics,
		power_armor,
		power_armor_mk2,
		processing_unit,
		production_science_pack,
		productivity_module,
		productivity_module_2,
		productivity_module_3,
		radar,
		railway,
		refined_flammables_1,
		refined_flammables_2,
		refined_flammables_3,
		refined_flammables_4,
		refined_flammables_5,
		refined_flammables_6,
		refined_flammables_7,
		repair_pack,
		research_speed_1,
		research_speed_2,
		research_speed_3,
		research_speed_4,
		research_speed_5,
		research_speed_6,
		robotics,
		rocket_fuel,
		rocket_silo,
		rocketry,
		solar_energy,
		solar_panel_equipment,
		space_science_pack,
		speed_module,
		speed_module_2,
		speed_module_3,
		spidertron,
		steam_power,
		steel_axe,
		steel_processing,
		stone_wall,
		stronger_explosives_1,
		stronger_explosives_2,
		stronger_explosives_3,
		stronger_explosives_4,
		stronger_explosives_5,
		stronger_explosives_6,
		stronger_explosives_7,
		sulfur_processing,
		tank,
		toolbelt,
		uranium_ammo,
		uranium_mining,
		uranium_processing,
		utility_science_pack,
		weapon_shooting_speed_1,
		weapon_shooting_speed_2,
		weapon_shooting_speed_3,
		weapon_shooting_speed_4,
		weapon_shooting_speed_5,
		weapon_shooting_speed_6,
		worker_robots_speed_1,
		worker_robots_speed_2,
		worker_robots_speed_3,
		worker_robots_speed_4,
		worker_robots_speed_5,
		worker_robots_speed_6,
		worker_robots_storage_1,
		worker_robots_storage_2,
		worker_robots_storage_3,
	} type;

	static inline const vector<string> TechnologyNames = {
		"Advanced circuit",
		"Advanced combinators",
		"Advanced material processing",
		"Advanced material processing 2",
		"Advanced oil processing",
		"Artillery",
		"Artillery shell range",
		"Artillery shell shooting speed",
		"Atomic bomb",
		"Automated rail transportation",
		"Automation",
		"Automation 2",
		"Automation 3",
		"Automation science pack",
		"Automobilism",
		"Battery",
		"Personal battery",
		"Personal battery MK2",
		"Belt immunity equipment",
		"Braking force 1",
		"Braking force 2",
		"Braking force 3",
		"Braking force 4",
		"Braking force 5",
		"Braking force 6",
		"Braking force 7",
		"Bulk inserter",
		"Chemical science pack",
		"Circuit network",
		"Cliff explosives",
		"Coal liquefaction",
		"Concrete",
		"Construction robotics",
		"Defender",
		"Destroyer",
		"Discharge defense",
		"Distractor",
		"Effect transmission",
		"Efficiency module",
		"Efficiency module 2",
		"Efficiency module 3",
		"Electric energy accumulators",
		"Electric energy distribution 1",
		"Electric energy distribution 2",
		"Electric engine",
		"Electric mining drill",
		"Electronics",
		"Energy shield equipment",
		"Energy shield MK2 equipment",
		"Engine",
		"Exoskeleton equipment",
		"Explosive rocketry",
		"Explosives",
		"Fast inserter",
		"Portable fission reactor",
		"Flamethrower",
		"Flammables",
		"Fluid handling",
		"Fluid wagon",
		"Follower robot count 1",
		"Follower robot count 2",
		"Follower robot count 3",
		"Follower robot count 4",
		"Follower robot count",
		"Gate",
		"Gun turret",
		"Heavy armor",
		"Inserter capacity bonus 1",
		"Inserter capacity bonus 2",
		"Inserter capacity bonus 3",
		"Inserter capacity bonus 4",
		"Inserter capacity bonus 5",
		"Inserter capacity bonus 6",
		"Inserter capacity bonus 7",
		"Kovarex enrichment process",
		"Lamp",
		"Land mines",
		"Landfill",
		"Laser",
		"Laser shooting speed 1",
		"Laser shooting speed 2",
		"Laser shooting speed 3",
		"Laser shooting speed 4",
		"Laser shooting speed 5",
		"Laser shooting speed 6",
		"Laser shooting speed 7",
		"Laser turret",
		"Energy weapons damage 1",
		"Energy weapons damage 2",
		"Energy weapons damage 3",
		"Energy weapons damage 4",
		"Energy weapons damage 5",
		"Energy weapons damage 6",
		"Energy weapons damage",
		"Logistic robotics",
		"Logistic science pack",
		"Logistic system",
		"Logistics",
		"Logistics 2",
		"Logistics 3",
		"Low density structure",
		"Lubricant",
		"Military",
		"Military 2",
		"Military 3",
		"Military 4",
		"Military science pack",
		"Mining productivity 1",
		"Mining productivity 2",
		"Mining productivity 3",
		"Mining productivity",
		"Modular armor",
		"Modules",
		"Nightvision equipment",
		"Nuclear fuel reprocessing",
		"Nuclear power",
		"Oil gathering",
		"Oil processing",
		"Personal laser defense",
		"Personal roboport",
		"Personal roboport MK2",
		"Physical projectile damage 1",
		"Physical projectile damage 2",
		"Physical projectile damage 3",
		"Physical projectile damage 4",
		"Physical projectile damage 5",
		"Physical projectile damage 6",
		"Physical projectile damage",
		"Plastics",
		"Power armor",
		"Power armor MK2",
		"Processing unit",
		"Production science pack",
		"Productivity module",
		"Productivity module 2",
		"Productivity module 3",
		"Radar",
		"Railway",
		"Refined flammables 1",
		"Refined flammables 2",
		"Refined flammables 3",
		"Refined flammables 4",
		"Refined flammables 5",
		"Refined flammables 6",
		"Refined flammables",
		"Repair pack",
		"Lab research speed 1",
		"Lab research speed 2",
		"Lab research speed 3",
		"Lab research speed 4",
		"Lab research speed 5",
		"Lab research speed 6",
		"Robotics",
		"Rocket fuel",
		"Rocket silo",
		"Rocketry",
		"Solar energy",
		"Portable solar panel",
		"Space science pack",
		"Speed module",
		"Speed module 2",
		"Speed module 3",
		"Spidertron",
		"Steam power",
		"Steel axe",
		"Steel processing",
		"Stone wall",
		"Stronger explosives 1",
		"Stronger explosives 2",
		"Stronger explosives 3",
		"Stronger explosives 4",
		"Stronger explosives 5",
		"Stronger explosives 6",
		"Stronger explosives",
		"Sulfur processing",
		"Tank",
		"Toolbelt",
		"Uranium ammo",
		"Uranium mining",
		"Uranium processing",
		"Utility science pack",
		"Weapon shooting speed 1",
		"Weapon shooting speed 2",
		"Weapon shooting speed 3",
		"Weapon shooting speed 4",
		"Weapon shooting speed 5",
		"Weapon shooting speed 6",
		"Worker robot speed 1",
		"Worker robot speed 2",
		"Worker robot speed 3",
		"Worker robot speed 4",
		"Worker robot speed 5",
		"Worker robot speed",
		"Worker robot cargo size 1",
		"Worker robot cargo size 2",
		"Worker robot cargo size 3",
	};

	static inline const vector<string> TechnologyType_to_LuaName{
		"advanced-circuit",
		"advanced-combinators",
		"advanced-material-processing",
		"advanced-material-processing-2",
		"advanced-oil-processing",
		"artillery",
		"artillery-shell-range-1",
		"artillery-shell-speed-1",
		"atomic-bomb",
		"automated-rail-transportation",
		"automation",
		"automation-2",
		"automation-3",
		"automation-science-pack",
		"automobilism",
		"battery",
		"battery-equipment",
		"battery-mk2-equipment",
		"belt-immunity-equipment",
		"braking-force-1",
		"braking-force-2",
		"braking-force-3",
		"braking-force-4",
		"braking-force-5",
		"braking-force-6",
		"braking-force-7",
		"bulk-inserter",
		"chemical-science-pack",
		"circuit-network",
		"cliff-explosives",
		"coal-liquefaction",
		"concrete",
		"construction-robotics",
		"defender",
		"destroyer",
		"discharge-defense-equipment",
		"distractor",
		"effect-transmission",
		"efficiency-module",
		"efficiency-module-2",
		"efficiency-module-3",
		"electric-energy-accumulators",
		"electric-energy-distribution-1",
		"electric-energy-distribution-2",
		"electric-engine",
		"electric-mining-drill",
		"electronics",
		"energy-shield-equipment",
		"energy-shield-mk2-equipment",
		"engine",
		"exoskeleton-equipment",
		"explosive-rocketry",
		"explosives",
		"fast-inserter",
		"fission-reactor-equipment",
		"flamethrower",
		"flammables",
		"fluid-handling",
		"fluid-wagon",
		"follower-robot-count-1",
		"follower-robot-count-2",
		"follower-robot-count-3",
		"follower-robot-count-4",
		"follower-robot-count-5",
		"gate",
		"gun-turret",
		"heavy-armor",
		"inserter-capacity-bonus-1",
		"inserter-capacity-bonus-2",
		"inserter-capacity-bonus-3",
		"inserter-capacity-bonus-4",
		"inserter-capacity-bonus-5",
		"inserter-capacity-bonus-6",
		"inserter-capacity-bonus-7",
		"kovarex-enrichment-process",
		"lamp",
		"land-mine",
		"landfill",
		"laser",
		"laser-shooting-speed-1",
		"laser-shooting-speed-2",
		"laser-shooting-speed-3",
		"laser-shooting-speed-4",
		"laser-shooting-speed-5",
		"laser-shooting-speed-6",
		"laser-shooting-speed-7",
		"laser-turret",
		"laser-weapons-damage-1",
		"laser-weapons-damage-2",
		"laser-weapons-damage-3",
		"laser-weapons-damage-4",
		"laser-weapons-damage-5",
		"laser-weapons-damage-6",
		"laser-weapons-damage-7",
		"logistic-robotics",
		"logistic-science-pack",
		"logistic-system",
		"logistics",
		"logistics-2",
		"logistics-3",
		"low-density-structure",
		"lubricant",
		"military",
		"military-2",
		"military-3",
		"military-4",
		"military-science-pack",
		"mining-productivity-1",
		"mining-productivity-2",
		"mining-productivity-3",
		"mining-productivity-4",
		"modular-armor",
		"modules",
		"night-vision-equipment",
		"nuclear-fuel-reprocessing",
		"nuclear-power",
		"oil-gathering",
		"oil-processing",
		"personal-laser-defense-equipment",
		"personal-roboport-equipment",
		"personal-roboport-mk2-equipment",
		"physical-projectile-damage-1",
		"physical-projectile-damage-2",
		"physical-projectile-damage-3",
		"physical-projectile-damage-4",
		"physical-projectile-damage-5",
		"physical-projectile-damage-6",
		"physical-projectile-damage-7",
		"plastics",
		"power-armor",
		"power-armor-mk2",
		"processing-unit",
		"production-science-pack",
		"productivity-module",
		"productivity-module-2",
		"productivity-module-3",
		"radar",
		"railway",
		"refined-flammables-1",
		"refined-flammables-2",
		"refined-flammables-3",
		"refined-flammables-4",
		"refined-flammables-5",
		"refined-flammables-6",
		"refined-flammables-7",
		"repair-pack",
		"research-speed-1",
		"research-speed-2",
		"research-speed-3",
		"research-speed-4",
		"research-speed-5",
		"research-speed-6",
		"robotics",
		"rocket-fuel",
		"rocket-silo",
		"rocketry",
		"solar-energy",
		"solar-panel-equipment",
		"space-science-pack",
		"speed-module",
		"speed-module-2",
		"speed-module-3",
		"spidertron",
		"steam-power",
		"steel-axe",
		"steel-processing",
		"stone-wall",
		"stronger-explosives-1",
		"stronger-explosives-2",
		"stronger-explosives-3",
		"stronger-explosives-4",
		"stronger-explosives-5",
		"stronger-explosives-6",
		"stronger-explosives-7",
		"sulfur-processing",
		"tank",
		"toolbelt",
		"uranium-ammo",
		"uranium-mining",
		"uranium-processing",
		"utility-science-pack",
		"weapon-shooting-speed-1",
		"weapon-shooting-speed-2",
		"weapon-shooting-speed-3",
		"weapon-shooting-speed-4",
		"weapon-shooting-speed-5",
		"weapon-shooting-speed-6",
		"worker-robots-speed-1",
		"worker-robots-speed-2",
		"worker-robots-speed-3",
		"worker-robots-speed-4",
		"worker-robots-speed-5",
		"worker-robots-speed-6",
		"worker-robots-storage-1",
		"worker-robots-storage-2",
		"worker-robots-storage-3",
	};

	static inline const map<string, TechnologyType> map_TechnologyName_to_TechnologyType = {
		{TechnologyNames[advanced_circuit], advanced_circuit},
		{TechnologyNames[advanced_combinators], advanced_combinators},
		{TechnologyNames[advanced_material_processing], advanced_material_processing},
		{TechnologyNames[advanced_material_processing_2], advanced_material_processing_2},
		{TechnologyNames[advanced_oil_processing], advanced_oil_processing},
		{TechnologyNames[artillery], artillery},
		{TechnologyNames[artillery_shell_range_1], artillery_shell_range_1},
		{TechnologyNames[artillery_shell_speed_1], artillery_shell_speed_1},
		{TechnologyNames[atomic_bomb], atomic_bomb},
		{TechnologyNames[automated_rail_transportation], automated_rail_transportation},
		{TechnologyNames[automation], automation},
		{TechnologyNames[automation_2], automation_2},
		{TechnologyNames[automation_3], automation_3},
		{TechnologyNames[automation_science_pack], automation_science_pack},
		{TechnologyNames[automobilism], automobilism},
		{TechnologyNames[battery], battery},
		{TechnologyNames[battery_equipment], battery_equipment},
		{TechnologyNames[battery_mk2_equipment], battery_mk2_equipment},
		{TechnologyNames[belt_immunity_equipment], belt_immunity_equipment},
		{TechnologyNames[braking_force_1], braking_force_1},
		{TechnologyNames[braking_force_2], braking_force_2},
		{TechnologyNames[braking_force_3], braking_force_3},
		{TechnologyNames[braking_force_4], braking_force_4},
		{TechnologyNames[braking_force_5], braking_force_5},
		{TechnologyNames[braking_force_6], braking_force_6},
		{TechnologyNames[braking_force_7], braking_force_7},
		{TechnologyNames[bulk_inserter], bulk_inserter},
		{TechnologyNames[chemical_science_pack], chemical_science_pack},
		{TechnologyNames[circuit_network], circuit_network},
		{TechnologyNames[cliff_explosives], cliff_explosives},
		{TechnologyNames[coal_liquefaction], coal_liquefaction},
		{TechnologyNames[concrete], concrete},
		{TechnologyNames[construction_robotics], construction_robotics},
		{TechnologyNames[defender], defender},
		{TechnologyNames[destroyer], destroyer},
		{TechnologyNames[discharge_defense_equipment], discharge_defense_equipment},
		{TechnologyNames[distractor], distractor},
		{TechnologyNames[effect_transmission], effect_transmission},
		{TechnologyNames[efficiency_module], efficiency_module},
		{TechnologyNames[efficiency_module_2], efficiency_module_2},
		{TechnologyNames[efficiency_module_3], efficiency_module_3},
		{TechnologyNames[electric_energy_accumulators], electric_energy_accumulators},
		{TechnologyNames[electric_energy_distribution_1], electric_energy_distribution_1},
		{TechnologyNames[electric_energy_distribution_2], electric_energy_distribution_2},
		{TechnologyNames[electric_engine], electric_engine},
		{TechnologyNames[electric_mining_drill], electric_mining_drill},
		{TechnologyNames[electronics], electronics},
		{TechnologyNames[energy_shield_equipment], energy_shield_equipment},
		{TechnologyNames[energy_shield_mk2_equipment], energy_shield_mk2_equipment},
		{TechnologyNames[engine], engine},
		{TechnologyNames[exoskeleton_equipment], exoskeleton_equipment},
		{TechnologyNames[explosive_rocketry], explosive_rocketry},
		{TechnologyNames[explosives], explosives},
		{TechnologyNames[fast_inserter], fast_inserter},
		{TechnologyNames[fission_reactor_equipment], fission_reactor_equipment},
		{TechnologyNames[flamethrower], flamethrower},
		{TechnologyNames[flammables], flammables},
		{TechnologyNames[fluid_handling], fluid_handling},
		{TechnologyNames[fluid_wagon], fluid_wagon},
		{TechnologyNames[follower_robot_count_1], follower_robot_count_1},
		{TechnologyNames[follower_robot_count_2], follower_robot_count_2},
		{TechnologyNames[follower_robot_count_3], follower_robot_count_3},
		{TechnologyNames[follower_robot_count_4], follower_robot_count_4},
		{TechnologyNames[follower_robot_count_5], follower_robot_count_5},
		{TechnologyNames[gate], gate},
		{TechnologyNames[gun_turret], gun_turret},
		{TechnologyNames[heavy_armor], heavy_armor},
		{TechnologyNames[inserter_capacity_bonus_1], inserter_capacity_bonus_1},
		{TechnologyNames[inserter_capacity_bonus_2], inserter_capacity_bonus_2},
		{TechnologyNames[inserter_capacity_bonus_3], inserter_capacity_bonus_3},
		{TechnologyNames[inserter_capacity_bonus_4], inserter_capacity_bonus_4},
		{TechnologyNames[inserter_capacity_bonus_5], inserter_capacity_bonus_5},
		{TechnologyNames[inserter_capacity_bonus_6], inserter_capacity_bonus_6},
		{TechnologyNames[inserter_capacity_bonus_7], inserter_capacity_bonus_7},
		{TechnologyNames[kovarex_enrichment_process], kovarex_enrichment_process},
		{TechnologyNames[lamp], lamp},
		{TechnologyNames[land_mine], land_mine},
		{TechnologyNames[landfill], landfill},
		{TechnologyNames[laser], laser},
		{TechnologyNames[laser_shooting_speed_1], laser_shooting_speed_1},
		{TechnologyNames[laser_shooting_speed_2], laser_shooting_speed_2},
		{TechnologyNames[laser_shooting_speed_3], laser_shooting_speed_3},
		{TechnologyNames[laser_shooting_speed_4], laser_shooting_speed_4},
		{TechnologyNames[laser_shooting_speed_5], laser_shooting_speed_5},
		{TechnologyNames[laser_shooting_speed_6], laser_shooting_speed_6},
		{TechnologyNames[laser_shooting_speed_7], laser_shooting_speed_7},
		{TechnologyNames[laser_turret], laser_turret},
		{TechnologyNames[laser_weapons_damage_1], laser_weapons_damage_1},
		{TechnologyNames[laser_weapons_damage_2], laser_weapons_damage_2},
		{TechnologyNames[laser_weapons_damage_3], laser_weapons_damage_3},
		{TechnologyNames[laser_weapons_damage_4], laser_weapons_damage_4},
		{TechnologyNames[laser_weapons_damage_5], laser_weapons_damage_5},
		{TechnologyNames[laser_weapons_damage_6], laser_weapons_damage_6},
		{TechnologyNames[laser_weapons_damage_7], laser_weapons_damage_7},
		{TechnologyNames[logistic_robotics], logistic_robotics},
		{TechnologyNames[logistic_science_pack], logistic_science_pack},
		{TechnologyNames[logistic_system], logistic_system},
		{TechnologyNames[logistics], logistics},
		{TechnologyNames[logistics_2], logistics_2},
		{TechnologyNames[logistics_3], logistics_3},
		{TechnologyNames[low_density_structure], low_density_structure},
		{TechnologyNames[lubricant], lubricant},
		{TechnologyNames[military], military},
		{TechnologyNames[military_2], military_2},
		{TechnologyNames[military_3], military_3},
		{TechnologyNames[military_4], military_4},
		{TechnologyNames[military_science_pack], military_science_pack},
		{TechnologyNames[mining_productivity_1], mining_productivity_1},
		{TechnologyNames[mining_productivity_2], mining_productivity_2},
		{TechnologyNames[mining_productivity_3], mining_productivity_3},
		{TechnologyNames[mining_productivity_4], mining_productivity_4},
		{TechnologyNames[modular_armor], modular_armor},
		{TechnologyNames[modules], modules},
		{TechnologyNames[night_vision_equipment], night_vision_equipment},
		{TechnologyNames[nuclear_fuel_reprocessing], nuclear_fuel_reprocessing},
		{TechnologyNames[nuclear_power], nuclear_power},
		{TechnologyNames[oil_gathering], oil_gathering},
		{TechnologyNames[oil_processing], oil_processing},
		{TechnologyNames[personal_laser_defense_equipment], personal_laser_defense_equipment},
		{TechnologyNames[personal_roboport_equipment], personal_roboport_equipment},
		{TechnologyNames[personal_roboport_mk2_equipment], personal_roboport_mk2_equipment},
		{TechnologyNames[physical_projectile_damage_1], physical_projectile_damage_1},
		{TechnologyNames[physical_projectile_damage_2], physical_projectile_damage_2},
		{TechnologyNames[physical_projectile_damage_3], physical_projectile_damage_3},
		{TechnologyNames[physical_projectile_damage_4], physical_projectile_damage_4},
		{TechnologyNames[physical_projectile_damage_5], physical_projectile_damage_5},
		{TechnologyNames[physical_projectile_damage_6], physical_projectile_damage_6},
		{TechnologyNames[physical_projectile_damage_7], physical_projectile_damage_7},
		{TechnologyNames[plastics], plastics},
		{TechnologyNames[power_armor], power_armor},
		{TechnologyNames[power_armor_mk2], power_armor_mk2},
		{TechnologyNames[processing_unit], processing_unit},
		{TechnologyNames[production_science_pack], production_science_pack},
		{TechnologyNames[productivity_module], productivity_module},
		{TechnologyNames[productivity_module_2], productivity_module_2},
		{TechnologyNames[productivity_module_3], productivity_module_3},
		{TechnologyNames[radar], radar},
		{TechnologyNames[railway], railway},
		{TechnologyNames[refined_flammables_1], refined_flammables_1},
		{TechnologyNames[refined_flammables_2], refined_flammables_2},
		{TechnologyNames[refined_flammables_3], refined_flammables_3},
		{TechnologyNames[refined_flammables_4], refined_flammables_4},
		{TechnologyNames[refined_flammables_5], refined_flammables_5},
		{TechnologyNames[refined_flammables_6], refined_flammables_6},
		{TechnologyNames[refined_flammables_7], refined_flammables_7},
		{TechnologyNames[repair_pack], repair_pack},
		{TechnologyNames[research_speed_1], research_speed_1},
		{TechnologyNames[research_speed_2], research_speed_2},
		{TechnologyNames[research_speed_3], research_speed_3},
		{TechnologyNames[research_speed_4], research_speed_4},
		{TechnologyNames[research_speed_5], research_speed_5},
		{TechnologyNames[research_speed_6], research_speed_6},
		{TechnologyNames[robotics], robotics},
		{TechnologyNames[rocket_fuel], rocket_fuel},
		{TechnologyNames[rocket_silo], rocket_silo},
		{TechnologyNames[rocketry], rocketry},
		{TechnologyNames[solar_energy], solar_energy},
		{TechnologyNames[solar_panel_equipment], solar_panel_equipment},
		{TechnologyNames[space_science_pack], space_science_pack},
		{TechnologyNames[speed_module], speed_module},
		{TechnologyNames[speed_module_2], speed_module_2},
		{TechnologyNames[speed_module_3], speed_module_3},
		{TechnologyNames[spidertron], spidertron},
		{TechnologyNames[steam_power], steam_power},
		{TechnologyNames[steel_axe], steel_axe},
		{TechnologyNames[steel_processing], steel_processing},
		{TechnologyNames[stone_wall], stone_wall},
		{TechnologyNames[stronger_explosives_1], stronger_explosives_1},
		{TechnologyNames[stronger_explosives_2], stronger_explosives_2},
		{TechnologyNames[stronger_explosives_3], stronger_explosives_3},
		{TechnologyNames[stronger_explosives_4], stronger_explosives_4},
		{TechnologyNames[stronger_explosives_5], stronger_explosives_5},
		{TechnologyNames[stronger_explosives_6], stronger_explosives_6},
		{TechnologyNames[stronger_explosives_7], stronger_explosives_7},
		{TechnologyNames[sulfur_processing], sulfur_processing},
		{TechnologyNames[tank], tank},
		{TechnologyNames[toolbelt], toolbelt},
		{TechnologyNames[uranium_ammo], uranium_ammo},
		{TechnologyNames[uranium_mining], uranium_mining},
		{TechnologyNames[uranium_processing], uranium_processing},
		{TechnologyNames[utility_science_pack], utility_science_pack},
		{TechnologyNames[weapon_shooting_speed_1], weapon_shooting_speed_1},
		{TechnologyNames[weapon_shooting_speed_2], weapon_shooting_speed_2},
		{TechnologyNames[weapon_shooting_speed_3], weapon_shooting_speed_3},
		{TechnologyNames[weapon_shooting_speed_4], weapon_shooting_speed_4},
		{TechnologyNames[weapon_shooting_speed_5], weapon_shooting_speed_5},
		{TechnologyNames[weapon_shooting_speed_6], weapon_shooting_speed_6},
		{TechnologyNames[worker_robots_speed_1], worker_robots_speed_1},
		{TechnologyNames[worker_robots_speed_2], worker_robots_speed_2},
		{TechnologyNames[worker_robots_speed_3], worker_robots_speed_3},
		{TechnologyNames[worker_robots_speed_4], worker_robots_speed_4},
		{TechnologyNames[worker_robots_speed_5], worker_robots_speed_5},
		{TechnologyNames[worker_robots_speed_6], worker_robots_speed_6},
		{TechnologyNames[worker_robots_storage_1], worker_robots_storage_1},
		{TechnologyNames[worker_robots_storage_2], worker_robots_storage_2},
		{TechnologyNames[worker_robots_storage_3], worker_robots_storage_3},
		{to_lower(TechnologyNames[advanced_circuit]), advanced_circuit},
		{to_lower(TechnologyNames[advanced_combinators]), advanced_combinators},
		{to_lower(TechnologyNames[advanced_material_processing]), advanced_material_processing},
		{to_lower(TechnologyNames[advanced_material_processing_2]), advanced_material_processing_2},
		{to_lower(TechnologyNames[advanced_oil_processing]), advanced_oil_processing},
		{to_lower(TechnologyNames[artillery]), artillery},
		{to_lower(TechnologyNames[artillery_shell_range_1]), artillery_shell_range_1},
		{to_lower(TechnologyNames[artillery_shell_speed_1]), artillery_shell_speed_1},
		{to_lower(TechnologyNames[atomic_bomb]), atomic_bomb},
		{to_lower(TechnologyNames[automated_rail_transportation]), automated_rail_transportation},
		{to_lower(TechnologyNames[automation]), automation},
		{to_lower(TechnologyNames[automation_2]), automation_2},
		{to_lower(TechnologyNames[automation_3]), automation_3},
		{to_lower(TechnologyNames[automation_science_pack]), automation_science_pack},
		{to_lower(TechnologyNames[automobilism]), automobilism},
		{to_lower(TechnologyNames[battery]), battery},
		{to_lower(TechnologyNames[battery_equipment]), battery_equipment},
		{to_lower(TechnologyNames[battery_mk2_equipment]), battery_mk2_equipment},
		{to_lower(TechnologyNames[belt_immunity_equipment]), belt_immunity_equipment},
		{to_lower(TechnologyNames[braking_force_1]), braking_force_1},
		{to_lower(TechnologyNames[braking_force_2]), braking_force_2},
		{to_lower(TechnologyNames[braking_force_3]), braking_force_3},
		{to_lower(TechnologyNames[braking_force_4]), braking_force_4},
		{to_lower(TechnologyNames[braking_force_5]), braking_force_5},
		{to_lower(TechnologyNames[braking_force_6]), braking_force_6},
		{to_lower(TechnologyNames[braking_force_7]), braking_force_7},
		{to_lower(TechnologyNames[bulk_inserter]), bulk_inserter},
		{to_lower(TechnologyNames[chemical_science_pack]), chemical_science_pack},
		{to_lower(TechnologyNames[circuit_network]), circuit_network},
		{to_lower(TechnologyNames[cliff_explosives]), cliff_explosives},
		{to_lower(TechnologyNames[coal_liquefaction]), coal_liquefaction},
		{to_lower(TechnologyNames[concrete]), concrete},
		{to_lower(TechnologyNames[construction_robotics]), construction_robotics},
		{to_lower(TechnologyNames[defender]), defender},
		{to_lower(TechnologyNames[destroyer]), destroyer},
		{to_lower(TechnologyNames[discharge_defense_equipment]), discharge_defense_equipment},
		{to_lower(TechnologyNames[distractor]), distractor},
		{to_lower(TechnologyNames[effect_transmission]), effect_transmission},
		{to_lower(TechnologyNames[efficiency_module]), efficiency_module},
		{to_lower(TechnologyNames[efficiency_module_2]), efficiency_module_2},
		{to_lower(TechnologyNames[efficiency_module_3]), efficiency_module_3},
		{to_lower(TechnologyNames[electric_energy_accumulators]), electric_energy_accumulators},
		{to_lower(TechnologyNames[electric_energy_distribution_1]), electric_energy_distribution_1},
		{to_lower(TechnologyNames[electric_energy_distribution_2]), electric_energy_distribution_2},
		{to_lower(TechnologyNames[electric_engine]), electric_engine},
		{to_lower(TechnologyNames[electric_mining_drill]), electric_mining_drill},
		{to_lower(TechnologyNames[electronics]), electronics},
		{to_lower(TechnologyNames[energy_shield_equipment]), energy_shield_equipment},
		{to_lower(TechnologyNames[energy_shield_mk2_equipment]), energy_shield_mk2_equipment},
		{to_lower(TechnologyNames[engine]), engine},
		{to_lower(TechnologyNames[exoskeleton_equipment]), exoskeleton_equipment},
		{to_lower(TechnologyNames[explosive_rocketry]), explosive_rocketry},
		{to_lower(TechnologyNames[explosives]), explosives},
		{to_lower(TechnologyNames[fast_inserter]), fast_inserter},
		{to_lower(TechnologyNames[fission_reactor_equipment]), fission_reactor_equipment},
		{to_lower(TechnologyNames[flamethrower]), flamethrower},
		{to_lower(TechnologyNames[flammables]), flammables},
		{to_lower(TechnologyNames[fluid_handling]), fluid_handling},
		{to_lower(TechnologyNames[fluid_wagon]), fluid_wagon},
		{to_lower(TechnologyNames[follower_robot_count_1]), follower_robot_count_1},
		{to_lower(TechnologyNames[follower_robot_count_2]), follower_robot_count_2},
		{to_lower(TechnologyNames[follower_robot_count_3]), follower_robot_count_3},
		{to_lower(TechnologyNames[follower_robot_count_4]), follower_robot_count_4},
		{to_lower(TechnologyNames[follower_robot_count_5]), follower_robot_count_5},
		{to_lower(TechnologyNames[gate]), gate},
		{to_lower(TechnologyNames[gun_turret]), gun_turret},
		{to_lower(TechnologyNames[heavy_armor]), heavy_armor},
		{to_lower(TechnologyNames[inserter_capacity_bonus_1]), inserter_capacity_bonus_1},
		{to_lower(TechnologyNames[inserter_capacity_bonus_2]), inserter_capacity_bonus_2},
		{to_lower(TechnologyNames[inserter_capacity_bonus_3]), inserter_capacity_bonus_3},
		{to_lower(TechnologyNames[inserter_capacity_bonus_4]), inserter_capacity_bonus_4},
		{to_lower(TechnologyNames[inserter_capacity_bonus_5]), inserter_capacity_bonus_5},
		{to_lower(TechnologyNames[inserter_capacity_bonus_6]), inserter_capacity_bonus_6},
		{to_lower(TechnologyNames[inserter_capacity_bonus_7]), inserter_capacity_bonus_7},
		{to_lower(TechnologyNames[kovarex_enrichment_process]), kovarex_enrichment_process},
		{to_lower(TechnologyNames[lamp]), lamp},
		{to_lower(TechnologyNames[land_mine]), land_mine},
		{to_lower(TechnologyNames[landfill]), landfill},
		{to_lower(TechnologyNames[laser]), laser},
		{to_lower(TechnologyNames[laser_shooting_speed_1]), laser_shooting_speed_1},
		{to_lower(TechnologyNames[laser_shooting_speed_2]), laser_shooting_speed_2},
		{to_lower(TechnologyNames[laser_shooting_speed_3]), laser_shooting_speed_3},
		{to_lower(TechnologyNames[laser_shooting_speed_4]), laser_shooting_speed_4},
		{to_lower(TechnologyNames[laser_shooting_speed_5]), laser_shooting_speed_5},
		{to_lower(TechnologyNames[laser_shooting_speed_6]), laser_shooting_speed_6},
		{to_lower(TechnologyNames[laser_shooting_speed_7]), laser_shooting_speed_7},
		{to_lower(TechnologyNames[laser_turret]), laser_turret},
		{to_lower(TechnologyNames[laser_weapons_damage_1]), laser_weapons_damage_1},
		{to_lower(TechnologyNames[laser_weapons_damage_2]), laser_weapons_damage_2},
		{to_lower(TechnologyNames[laser_weapons_damage_3]), laser_weapons_damage_3},
		{to_lower(TechnologyNames[laser_weapons_damage_4]), laser_weapons_damage_4},
		{to_lower(TechnologyNames[laser_weapons_damage_5]), laser_weapons_damage_5},
		{to_lower(TechnologyNames[laser_weapons_damage_6]), laser_weapons_damage_6},
		{to_lower(TechnologyNames[laser_weapons_damage_7]), laser_weapons_damage_7},
		{to_lower(TechnologyNames[logistic_robotics]), logistic_robotics},
		{to_lower(TechnologyNames[logistic_science_pack]), logistic_science_pack},
		{to_lower(TechnologyNames[logistic_system]), logistic_system},
		{to_lower(TechnologyNames[logistics]), logistics},
		{to_lower(TechnologyNames[logistics_2]), logistics_2},
		{to_lower(TechnologyNames[logistics_3]), logistics_3},
		{to_lower(TechnologyNames[low_density_structure]), low_density_structure},
		{to_lower(TechnologyNames[lubricant]), lubricant},
		{to_lower(TechnologyNames[military]), military},
		{to_lower(TechnologyNames[military_2]), military_2},
		{to_lower(TechnologyNames[military_3]), military_3},
		{to_lower(TechnologyNames[military_4]), military_4},
		{to_lower(TechnologyNames[military_science_pack]), military_science_pack},
		{to_lower(TechnologyNames[mining_productivity_1]), mining_productivity_1},
		{to_lower(TechnologyNames[mining_productivity_2]), mining_productivity_2},
		{to_lower(TechnologyNames[mining_productivity_3]), mining_productivity_3},
		{to_lower(TechnologyNames[mining_productivity_4]), mining_productivity_4},
		{to_lower(TechnologyNames[modular_armor]), modular_armor},
		{to_lower(TechnologyNames[modules]), modules},
		{to_lower(TechnologyNames[night_vision_equipment]), night_vision_equipment},
		{to_lower(TechnologyNames[nuclear_fuel_reprocessing]), nuclear_fuel_reprocessing},
		{to_lower(TechnologyNames[nuclear_power]), nuclear_power},
		{to_lower(TechnologyNames[oil_gathering]), oil_gathering},
		{to_lower(TechnologyNames[oil_processing]), oil_processing},
		{to_lower(TechnologyNames[personal_laser_defense_equipment]), personal_laser_defense_equipment},
		{to_lower(TechnologyNames[personal_roboport_equipment]), personal_roboport_equipment},
		{to_lower(TechnologyNames[personal_roboport_mk2_equipment]), personal_roboport_mk2_equipment},
		{to_lower(TechnologyNames[physical_projectile_damage_1]), physical_projectile_damage_1},
		{to_lower(TechnologyNames[physical_projectile_damage_2]), physical_projectile_damage_2},
		{to_lower(TechnologyNames[physical_projectile_damage_3]), physical_projectile_damage_3},
		{to_lower(TechnologyNames[physical_projectile_damage_4]), physical_projectile_damage_4},
		{to_lower(TechnologyNames[physical_projectile_damage_5]), physical_projectile_damage_5},
		{to_lower(TechnologyNames[physical_projectile_damage_6]), physical_projectile_damage_6},
		{to_lower(TechnologyNames[physical_projectile_damage_7]), physical_projectile_damage_7},
		{to_lower(TechnologyNames[plastics]), plastics},
		{to_lower(TechnologyNames[power_armor]), power_armor},
		{to_lower(TechnologyNames[power_armor_mk2]), power_armor_mk2},
		{to_lower(TechnologyNames[processing_unit]), processing_unit},
		{to_lower(TechnologyNames[production_science_pack]), production_science_pack},
		{to_lower(TechnologyNames[productivity_module]), productivity_module},
		{to_lower(TechnologyNames[productivity_module_2]), productivity_module_2},
		{to_lower(TechnologyNames[productivity_module_3]), productivity_module_3},
		{to_lower(TechnologyNames[radar]), radar},
		{to_lower(TechnologyNames[railway]), railway},
		{to_lower(TechnologyNames[refined_flammables_1]), refined_flammables_1},
		{to_lower(TechnologyNames[refined_flammables_2]), refined_flammables_2},
		{to_lower(TechnologyNames[refined_flammables_3]), refined_flammables_3},
		{to_lower(TechnologyNames[refined_flammables_4]), refined_flammables_4},
		{to_lower(TechnologyNames[refined_flammables_5]), refined_flammables_5},
		{to_lower(TechnologyNames[refined_flammables_6]), refined_flammables_6},
		{to_lower(TechnologyNames[refined_flammables_7]), refined_flammables_7},
		{to_lower(TechnologyNames[repair_pack]), repair_pack},
		{to_lower(TechnologyNames[research_speed_1]), research_speed_1},
		{to_lower(TechnologyNames[research_speed_2]), research_speed_2},
		{to_lower(TechnologyNames[research_speed_3]), research_speed_3},
		{to_lower(TechnologyNames[research_speed_4]), research_speed_4},
		{to_lower(TechnologyNames[research_speed_5]), research_speed_5},
		{to_lower(TechnologyNames[research_speed_6]), research_speed_6},
		{to_lower(TechnologyNames[robotics]), robotics},
		{to_lower(TechnologyNames[rocket_fuel]), rocket_fuel},
		{to_lower(TechnologyNames[rocket_silo]), rocket_silo},
		{to_lower(TechnologyNames[rocketry]), rocketry},
		{to_lower(TechnologyNames[solar_energy]), solar_energy},
		{to_lower(TechnologyNames[solar_panel_equipment]), solar_panel_equipment},
		{to_lower(TechnologyNames[space_science_pack]), space_science_pack},
		{to_lower(TechnologyNames[speed_module]), speed_module},
		{to_lower(TechnologyNames[speed_module_2]), speed_module_2},
		{to_lower(TechnologyNames[speed_module_3]), speed_module_3},
		{to_lower(TechnologyNames[spidertron]), spidertron},
		{to_lower(TechnologyNames[steam_power]), steam_power},
		{to_lower(TechnologyNames[steel_axe]), steel_axe},
		{to_lower(TechnologyNames[steel_processing]), steel_processing},
		{to_lower(TechnologyNames[stone_wall]), stone_wall},
		{to_lower(TechnologyNames[stronger_explosives_1]), stronger_explosives_1},
		{to_lower(TechnologyNames[stronger_explosives_2]), stronger_explosives_2},
		{to_lower(TechnologyNames[stronger_explosives_3]), stronger_explosives_3},
		{to_lower(TechnologyNames[stronger_explosives_4]), stronger_explosives_4},
		{to_lower(TechnologyNames[stronger_explosives_5]), stronger_explosives_5},
		{to_lower(TechnologyNames[stronger_explosives_6]), stronger_explosives_6},
		{to_lower(TechnologyNames[stronger_explosives_7]), stronger_explosives_7},
		{to_lower(TechnologyNames[sulfur_processing]), sulfur_processing},
		{to_lower(TechnologyNames[tank]), tank},
		{to_lower(TechnologyNames[toolbelt]), toolbelt},
		{to_lower(TechnologyNames[uranium_ammo]), uranium_ammo},
		{to_lower(TechnologyNames[uranium_mining]), uranium_mining},
		{to_lower(TechnologyNames[uranium_processing]), uranium_processing},
		{to_lower(TechnologyNames[utility_science_pack]), utility_science_pack},
		{to_lower(TechnologyNames[weapon_shooting_speed_1]), weapon_shooting_speed_1},
		{to_lower(TechnologyNames[weapon_shooting_speed_2]), weapon_shooting_speed_2},
		{to_lower(TechnologyNames[weapon_shooting_speed_3]), weapon_shooting_speed_3},
		{to_lower(TechnologyNames[weapon_shooting_speed_4]), weapon_shooting_speed_4},
		{to_lower(TechnologyNames[weapon_shooting_speed_5]), weapon_shooting_speed_5},
		{to_lower(TechnologyNames[weapon_shooting_speed_6]), weapon_shooting_speed_6},
		{to_lower(TechnologyNames[worker_robots_speed_1]), worker_robots_speed_1},
		{to_lower(TechnologyNames[worker_robots_speed_2]), worker_robots_speed_2},
		{to_lower(TechnologyNames[worker_robots_speed_3]), worker_robots_speed_3},
		{to_lower(TechnologyNames[worker_robots_speed_4]), worker_robots_speed_4},
		{to_lower(TechnologyNames[worker_robots_speed_5]), worker_robots_speed_5},
		{to_lower(TechnologyNames[worker_robots_speed_6]), worker_robots_speed_6},
		{to_lower(TechnologyNames[worker_robots_storage_1]), worker_robots_storage_1},
		{to_lower(TechnologyNames[worker_robots_storage_2]), worker_robots_storage_2},
		{to_lower(TechnologyNames[worker_robots_storage_3]), worker_robots_storage_3},
	};
};
